/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as models from "../index.js";

export type OlapErrorData = {
  /**
   * Code
   */
  code: models.OlapErrorCode;
  /**
   * Message
   */
  message: string;
};

export class OlapError extends Error {
  /**
   * Code
   */
  code: models.OlapErrorCode;

  /** The original data that was passed to this error instance. */
  data$: OlapErrorData;

  constructor(err: OlapErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;

    this.name = "OlapError";
  }
}

/** @internal */
export const OlapError$inboundSchema: z.ZodType<
  OlapError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: models.OlapErrorCode$inboundSchema,
  message: z.string(),
})
  .transform((v) => {
    return new OlapError(v);
  });

/** @internal */
export type OlapError$Outbound = {
  code: string;
  message: string;
};

/** @internal */
export const OlapError$outboundSchema: z.ZodType<
  OlapError$Outbound,
  z.ZodTypeDef,
  OlapError
> = z.instanceof(OlapError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: models.OlapErrorCode$outboundSchema,
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OlapError$ {
  /** @deprecated use `OlapError$inboundSchema` instead. */
  export const inboundSchema = OlapError$inboundSchema;
  /** @deprecated use `OlapError$outboundSchema` instead. */
  export const outboundSchema = OlapError$outboundSchema;
  /** @deprecated use `OlapError$Outbound` instead. */
  export type Outbound = OlapError$Outbound;
}
