/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as models from "../index.js";

/**
 * Not Found
 */
export type UnionApiErrorEntityNotFoundData = {
  code?: models.UnionApiErrorEntityNotFoundCode;
  /**
   * Error message
   */
  message: string;
};

/**
 * Not Found
 */
export class UnionApiErrorEntityNotFound extends Error {
  code?: models.UnionApiErrorEntityNotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: UnionApiErrorEntityNotFoundData;

  constructor(err: UnionApiErrorEntityNotFoundData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.code != null) this.code = err.code;

    this.name = "UnionApiErrorEntityNotFound";
  }
}

/** @internal */
export const UnionApiErrorEntityNotFound$inboundSchema: z.ZodType<
  UnionApiErrorEntityNotFound,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: models.UnionApiErrorEntityNotFoundCode$inboundSchema.default(
    "NOT_FOUND",
  ),
  message: z.string(),
})
  .transform((v) => {
    return new UnionApiErrorEntityNotFound(v);
  });

/** @internal */
export type UnionApiErrorEntityNotFound$Outbound = {
  code?: string;
  message: string;
};

/** @internal */
export const UnionApiErrorEntityNotFound$outboundSchema: z.ZodType<
  UnionApiErrorEntityNotFound$Outbound,
  z.ZodTypeDef,
  UnionApiErrorEntityNotFound
> = z.instanceof(UnionApiErrorEntityNotFound)
  .transform(v => v.data$)
  .pipe(z.object({
    code: models.UnionApiErrorEntityNotFoundCode$outboundSchema.default(
      "NOT_FOUND",
    ),
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnionApiErrorEntityNotFound$ {
  /** @deprecated use `UnionApiErrorEntityNotFound$inboundSchema` instead. */
  export const inboundSchema = UnionApiErrorEntityNotFound$inboundSchema;
  /** @deprecated use `UnionApiErrorEntityNotFound$outboundSchema` instead. */
  export const outboundSchema = UnionApiErrorEntityNotFound$outboundSchema;
  /** @deprecated use `UnionApiErrorEntityNotFound$Outbound` instead. */
  export type Outbound = UnionApiErrorEntityNotFound$Outbound;
}
