/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as models from "../index.js";

/**
 * Bad Request
 */
export type UnionApiErrorBadRequestData = {
  code?: models.UnionApiErrorBadRequestCode;
  /**
   * Error message
   */
  message: string;
};

/**
 * Bad Request
 */
export class UnionApiErrorBadRequest extends Error {
  code?: models.UnionApiErrorBadRequestCode;

  /** The original data that was passed to this error instance. */
  data$: UnionApiErrorBadRequestData;

  constructor(err: UnionApiErrorBadRequestData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.code != null) this.code = err.code;

    this.name = "UnionApiErrorBadRequest";
  }
}

/** @internal */
export const UnionApiErrorBadRequest$inboundSchema: z.ZodType<
  UnionApiErrorBadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: models.UnionApiErrorBadRequestCode$inboundSchema.default("BAD_REQUEST"),
  message: z.string(),
})
  .transform((v) => {
    return new UnionApiErrorBadRequest(v);
  });

/** @internal */
export type UnionApiErrorBadRequest$Outbound = {
  code?: string;
  message: string;
};

/** @internal */
export const UnionApiErrorBadRequest$outboundSchema: z.ZodType<
  UnionApiErrorBadRequest$Outbound,
  z.ZodTypeDef,
  UnionApiErrorBadRequest
> = z.instanceof(UnionApiErrorBadRequest)
  .transform(v => v.data$)
  .pipe(z.object({
    code: models.UnionApiErrorBadRequestCode$outboundSchema.default(
      "BAD_REQUEST",
    ),
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnionApiErrorBadRequest$ {
  /** @deprecated use `UnionApiErrorBadRequest$inboundSchema` instead. */
  export const inboundSchema = UnionApiErrorBadRequest$inboundSchema;
  /** @deprecated use `UnionApiErrorBadRequest$outboundSchema` instead. */
  export const outboundSchema = UnionApiErrorBadRequest$outboundSchema;
  /** @deprecated use `UnionApiErrorBadRequest$Outbound` instead. */
  export type Outbound = UnionApiErrorBadRequest$Outbound;
}
