/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { chartsGetFloorPriceChart } from "../../funcs/chartsGetFloorPriceChart.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetFloorPriceChartRequest$inboundSchema,
};

export const tool$chartsGetFloorPriceChart: ToolDefinition<typeof args> = {
  name: "charts-get-floor-price-chart",
  description:
    `Get historical data of floor price for collection for charting purposes

Returns list of historical floor prices aggregated at even intervals in the specified time period - last day, last month etc.  Each points represents the aggregated value of the interval after it.  The last point represents the current floor price.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await chartsGetFloorPriceChart(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
