/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectionStatisticsGetBidsByPrice } from "../../funcs/collectionStatisticsGetBidsByPrice.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetBidsByPriceRequest$inboundSchema,
};

export const tool$collectionStatisticsGetBidsByPrice: ToolDefinition<
  typeof args
> = {
  name: "collection-statistics-get-bids-by-price",
  description: `Get distribution of the number of bids by price

Returns list of bid prices with number of bids and bidders`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await collectionStatisticsGetBidsByPrice(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
