/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectionStatisticsGetPeriodCollectionStatisticsByIds } from "../../funcs/collectionStatisticsGetPeriodCollectionStatisticsByIds.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.OlapPeriodCollectionsByIdsStatisticsRequest$inboundSchema,
};

export const tool$collectionStatisticsGetPeriodCollectionStatisticsByIds:
  ToolDefinition<typeof args> = {
    name: "collection-statistics-get-period-collection-statistics-by-ids",
    description: `Get period-based statistics by collection IDs

Period-based collection statistics by IDs`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await collectionStatisticsGetPeriodCollectionStatisticsByIds(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
