/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { domainLookupResolve } from "../../funcs/domainLookupResolve.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ResolveRequest$inboundSchema,
};

export const tool$domainLookupResolve: ToolDefinition<typeof args> = {
  name: "domain-lookup-resolve",
  description: `Resolve domain

Resolves domain's blockchain address by its name (for example, from ENS domains collection)`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await domainLookupResolve(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
