/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { encodeOperationsEncode } from "../../funcs/encodeOperationsEncode.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.OrderForm$inboundSchema,
};

export const tool$encodeOperationsEncode: ToolDefinition<typeof args> = {
  name: "encode-operations-encode",
  description: `Generate order encode data for sign operations

Generate order encode data for sign operations`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await encodeOperationsEncode(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
