/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { indexerBlocksGetLatestIndexedBlock } from "../../funcs/indexerBlocksGetLatestIndexedBlock.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetLatestIndexedBlockRequest$inboundSchema,
};

export const tool$indexerBlocksGetLatestIndexedBlock: ToolDefinition<
  typeof args
> = {
  name: "indexer-blocks-get-latest-indexed-block",
  description: `Get latest indexed block

Get latest indexed block for blockchain`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await indexerBlocksGetLatestIndexedBlock(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
