/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftActivitiesGetActivitiesByUsers } from "../../funcs/nftActivitiesGetActivitiesByUsers.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.ActivitiesByUsersRequest$inboundSchema,
};

export const tool$nftActivitiesGetActivitiesByUsers: ToolDefinition<
  typeof args
> = {
  name: "NFT-activities-get-activities-by-users",
  description: `Get users Activities

Returns users Activities (like transfers, mints, sells etc) sorted by date. This API is deprecated in favor of \`Search Activities\``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftActivitiesGetActivitiesByUsers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
