/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftActivitiesGetAllActivities } from "../../funcs/nftActivitiesGetAllActivities.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAllActivitiesRequest$inboundSchema,
};

export const tool$nftActivitiesGetAllActivities: ToolDefinition<typeof args> = {
  name: "NFT-activities-get-all-activities",
  description: `Get all Activities

Returns all Activities in accordance with specified filters and sorted by date. This API is deprecated in favor of \`Search Activities\``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftActivitiesGetAllActivities(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
