/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftActivitiesGetActivitiesByCollection } from "../../funcs/nftActivitiesGetActivitiesByCollection.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetActivitiesByCollectionRequest$inboundSchema,
};

export const tool$nftActivitiesGetActivitiesByCollection: ToolDefinition<
  typeof args
> = {
  name: "NFT-activities-get-activities-by-collection",
  description: `Get NFT Collection Activities

Returns Activities related to NFTs from specified Collection and sorted by date. This API is deprecated in favor of \`Search Activities\``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftActivitiesGetActivitiesByCollection(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
