/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftActivitiesGetAllActivitiesSync } from "../../funcs/nftActivitiesGetAllActivitiesSync.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAllActivitiesSyncRequest$inboundSchema,
};

export const tool$nftActivitiesGetAllActivitiesSync: ToolDefinition<
  typeof args
> = {
  name: "NFT-activities-get-all-activities-sync",
  description: `Get all Activities (for sync)

Returns all Activities in accordance with specified filters and sorted by \`db updated\` date. During internal updates (like migrations) Activities can be updated for technical reasons. In such case, \`date\` field won't be changed. If you want to store Activities in your own storage and keep it synced, use this method.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftActivitiesGetAllActivitiesSync(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
