/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftCollectionsGetAllCollections } from "../../funcs/nftCollectionsGetAllCollections.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAllCollectionsRequest$inboundSchema,
};

export const tool$nftCollectionsGetAllCollections: ToolDefinition<typeof args> =
  {
    name: "NFT-collections-get-all-collections",
    description: `Get all NFT Collections

Returns all NFT Collections in accordance with specified filters`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await nftCollectionsGetAllCollections(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
