/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftCollectionsGetCollectionById } from "../../funcs/nftCollectionsGetCollectionById.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetCollectionByIdRequest$inboundSchema,
};

export const tool$nftCollectionsGetCollectionById: ToolDefinition<typeof args> =
  {
    name: "NFT-collections-get-collection-by-id",
    description: `Get NFT Collection by Id

Returns NFT Collection by Id`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await nftCollectionsGetCollectionById(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
