/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftCollectionsResetCollectionMeta } from "../../funcs/nftCollectionsResetCollectionMeta.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ResetCollectionMetaRequest$inboundSchema,
};

export const tool$nftCollectionsResetCollectionMeta: ToolDefinition<
  typeof args
> = {
  name: "NFT-collections-reset-collection-meta",
  description: `Reset Collection metadata

Reloads metadata for Collection (NOT for collection's NFTs)`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftCollectionsResetCollectionMeta(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
