/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftDataAndHistoricalStatisticsGetGmv } from "../../funcs/nftDataAndHistoricalStatisticsGetGmv.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetGmvRequest$inboundSchema,
};

export const tool$nftDataAndHistoricalStatisticsGetGmv: ToolDefinition<
  typeof args
> = {
  name: "NFT-data-and-historical-statistics-get-gmv",
  description: `Get NFT Collections GVM

Get historical statistics about Collection gross merchandise value`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftDataAndHistoricalStatisticsGetGmv(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
