/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftDataAndHistoricalStatisticsGetTransactions } from "../../funcs/nftDataAndHistoricalStatisticsGetTransactions.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetTransactionsRequest$inboundSchema,
};

export const tool$nftDataAndHistoricalStatisticsGetTransactions: ToolDefinition<
  typeof args
> = {
  name: "NFT-data-and-historical-statistics-get-transactions",
  description: `Get NFT Collection tx stats

Get historical statistics about Collection transactions`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] =
      await nftDataAndHistoricalStatisticsGetTransactions(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
