/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftDataAndHistoricalStatisticsGetCollectionStatistics } from "../../funcs/nftDataAndHistoricalStatisticsGetCollectionStatistics.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetCollectionStatisticsRequest$inboundSchema,
};

export const tool$nftDataAndHistoricalStatisticsGetCollectionStatistics:
  ToolDefinition<typeof args> = {
    name: "NFT-data-and-historical-statistics-get-collection-statistics",
    description: `Get NFT Collection statistics

Get statistics about a collection`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await nftDataAndHistoricalStatisticsGetCollectionStatistics(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
