/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftDataAndHistoricalStatisticsGetBuyers } from "../../funcs/nftDataAndHistoricalStatisticsGetBuyers.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetBuyersRequest$inboundSchema,
};

export const tool$nftDataAndHistoricalStatisticsGetBuyers: ToolDefinition<
  typeof args
> = {
  name: "NFT-data-and-historical-statistics-get-buyers",
  description: `Get NFT Collection buyer stats

Get historical statistics about Collection buyers`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftDataAndHistoricalStatisticsGetBuyers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
