/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftDataAndHistoricalStatisticsGetSellers } from "../../funcs/nftDataAndHistoricalStatisticsGetSellers.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetSellersRequest$inboundSchema,
};

export const tool$nftDataAndHistoricalStatisticsGetSellers: ToolDefinition<
  typeof args
> = {
  name: "NFT-data-and-historical-statistics-get-sellers",
  description: `Get NFT Collection seller stats

Get historical statistics about Collection sellers`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftDataAndHistoricalStatisticsGetSellers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
