/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftItemsMintLazyItem } from "../../funcs/nftItemsMintLazyItem.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.LazyItemMintForm$inboundSchema,
};

export const tool$nftItemsMintLazyItem: ToolDefinition<typeof args> = {
  name: "NFT-items-mint-lazy-item",
  description: `Mint Lazy NFT

Create Lazy NFT (supported only for some blockchains)`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftItemsMintLazyItem(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
