/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftItemsGetItemsByCollection } from "../../funcs/nftItemsGetItemsByCollection.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetItemsByCollectionRequest$inboundSchema,
};

export const tool$nftItemsGetItemsByCollection: ToolDefinition<typeof args> = {
  name: "NFT-items-get-items-by-collection",
  description: `Get NFT from collection

Returns list of NFTs from specified collection and sorted by \`last updated\` date`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftItemsGetItemsByCollection(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
