/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftItemsQueryTraits } from "../../funcs/nftItemsQueryTraits.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.QueryTraitsRequest$inboundSchema,
};

export const tool$nftItemsQueryTraits: ToolDefinition<typeof args> = {
  name: "NFT-items-query-traits",
  description: `Get NFT collection traits

Returns aggregation of existing traits for specified collections with counter for each trait type/value.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftItemsQueryTraits(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
