/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftItemsGetLazyItemById } from "../../funcs/nftItemsGetLazyItemById.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetLazyItemByIdRequest$inboundSchema,
};

export const tool$nftItemsGetLazyItemById: ToolDefinition<typeof args> = {
  name: "NFT-items-get-lazy-item-by-id",
  description: `Get Lazy NFT

Returns Lazy NFT Item by Id`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftItemsGetLazyItemById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
