/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftItemsGetItemByIds } from "../../funcs/nftItemsGetItemByIds.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.ItemIds$inboundSchema,
};

export const tool$nftItemsGetItemByIds: ToolDefinition<typeof args> = {
  name: "NFT-items-get-item-by-ids",
  description: `Get NFT by Ids

Returns NFT Items by specified list of Ids`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftItemsGetItemByIds(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
