/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftItemsBurnLazyItem } from "../../funcs/nftItemsBurnLazyItem.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.LazyItemBurnForm$inboundSchema,
};

export const tool$nftItemsBurnLazyItem: ToolDefinition<typeof args> = {
  name: "NFT-items-burn-lazy-item",
  description: `Burn Lazy NFT

Deletes Lazy NFT (supported only for some blockchains)`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftItemsBurnLazyItem(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
