/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftItemsQueryTraitsWithRarity } from "../../funcs/nftItemsQueryTraitsWithRarity.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.TraitsRarityRequest$inboundSchema,
};

export const tool$nftItemsQueryTraitsWithRarity: ToolDefinition<typeof args> = {
  name: "NFT-items-query-traits-with-rarity",
  description: `Get NFT traits rarity

Returns the rarity of the trait`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftItemsQueryTraitsWithRarity(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
