/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftOwnershipsGetOwnershipsByItem } from "../../funcs/nftOwnershipsGetOwnershipsByItem.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetOwnershipsByItemRequest$inboundSchema,
};

export const tool$nftOwnershipsGetOwnershipsByItem: ToolDefinition<
  typeof args
> = {
  name: "NFT-ownerships-get-ownerships-by-item",
  description: `Get NFTs Ownerships

Returns list of NFTs Ownerships for specified NFT and sorted by \`last updated\` date`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftOwnershipsGetOwnershipsByItem(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
