/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftOwnershipsGetCollectionsWithOwnedItems } from "../../funcs/nftOwnershipsGetCollectionsWithOwnedItems.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetCollectionsWithOwnedItemsRequest$inboundSchema,
};

export const tool$nftOwnershipsGetCollectionsWithOwnedItems: ToolDefinition<
  typeof args
> = {
  name: "NFT-ownerships-get-collections-with-owned-items",
  description: `Get collections owned items by owner

Returns list of collection with owned items by specified owner`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftOwnershipsGetCollectionsWithOwnedItems(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
