/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftOwnershipsGetOwnershipById } from "../../funcs/nftOwnershipsGetOwnershipById.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetOwnershipByIdRequest$inboundSchema,
};

export const tool$nftOwnershipsGetOwnershipById: ToolDefinition<typeof args> = {
  name: "NFT-ownerships-get-ownership-by-id",
  description: `Get NFT Ownership by Id

Returns Ownership by Id`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftOwnershipsGetOwnershipById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
