/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftSalesGetValidatedOrderById } from "../../funcs/nftSalesGetValidatedOrderById.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetValidatedOrderByIdRequest$inboundSchema,
};

export const tool$nftSalesGetValidatedOrderById: ToolDefinition<typeof args> = {
  name: "NFT-sales-get-validated-order-by-id",
  description: `Get validated Order by Id

Validates and returns order by Id. IMPORTANT - validation is time-consuming operation!`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftSalesGetValidatedOrderById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
