/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftSalesGetSellOrders } from "../../funcs/nftSalesGetSellOrders.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetSellOrdersRequest$inboundSchema,
};

export const tool$nftSalesGetSellOrders: ToolDefinition<typeof args> = {
  name: "NFT-sales-get-sell-orders",
  description: `Get sell Orders

Returns sell Orders satisfying specified filters and sorted by \`last update\` date`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftSalesGetSellOrders(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
