/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftSalesGetOrdersAll } from "../../funcs/nftSalesGetOrdersAll.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetOrdersAllRequest$inboundSchema,
};

export const tool$nftSalesGetOrdersAll: ToolDefinition<typeof args> = {
  name: "NFT-sales-get-orders-all",
  description: `Get all Orders

Returns all Orders in accordance with specified filters and sorted by \`last updated\` date`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftSalesGetOrdersAll(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
