/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftSalesGetOrdersByIds } from "../../funcs/nftSalesGetOrdersByIds.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.OrderIds$inboundSchema,
};

export const tool$nftSalesGetOrdersByIds: ToolDefinition<typeof args> = {
  name: "NFT-sales-get-orders-by-ids",
  description: `Get Orders by Ids

Returns Orders by specified list of Ids`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftSalesGetOrdersByIds(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
