/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftSalesGetOrderFloorBidsByCollection } from "../../funcs/nftSalesGetOrderFloorBidsByCollection.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetOrderFloorBidsByCollectionRequest$inboundSchema,
};

export const tool$nftSalesGetOrderFloorBidsByCollection: ToolDefinition<
  typeof args
> = {
  name: "NFT-sales-get-order-floor-bids-by-collection",
  description: `Get floor bids for Collection

Returns floor bids created for specified NFT Collection and sorted by price in USD (expensive first)`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nftSalesGetOrderFloorBidsByCollection(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
