/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { reconciliationGetReconciliationItems } from "../../funcs/reconciliationGetReconciliationItems.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetReconciliationItemsRequest$inboundSchema,
};

export const tool$reconciliationGetReconciliationItems: ToolDefinition<
  typeof args
> = {
  name: "reconciliation-get-reconciliation-items",
  description: `Get IDs of items updated after a specific datetime.

Return short view of items updated after a specific datetime.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await reconciliationGetReconciliationItems(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
