/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { searchAPISearchDuplicatedItems } from "../../funcs/searchAPISearchDuplicatedItems.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.DuplicatedItemsSearchRequest$inboundSchema,
};

export const tool$searchAPISearchDuplicatedItems: ToolDefinition<typeof args> =
  {
    name: "search-API-search-duplicated-items",
    description: `Search Duplicated NFTs

Advanced search returns NFTs satisfying provided filter and with duplicated traits`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await searchAPISearchDuplicatedItems(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
