/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { searchAPISearchTraits } from "../../funcs/searchAPISearchTraits.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SearchTraitsRequest$inboundSchema,
};

export const tool$searchAPISearchTraits: ToolDefinition<typeof args> = {
  name: "search-API-search-traits",
  description: `Search NFT collection traits

Returns aggregation of existing traits for specified collections with counter for each trait type/value.\  This is full-text-search, where you can specify filter for trait keys not precisely\  (for example, results \`back\` filter include \`Background\` trait)`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await searchAPISearchTraits(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
