/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { signatureOperationsGetInput } from "../../funcs/signatureOperationsGetInput.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.SignatureInputForm$inboundSchema,
};

export const tool$signatureOperationsGetInput: ToolDefinition<typeof args> = {
  name: "signature-operations-get-input",
  description: `Generate signed input

Generate input string to sign operation`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await signatureOperationsGetInput(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
