/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectionStatisticsGetBidsByPrice } from "../funcs/collectionStatisticsGetBidsByPrice.js";
import { collectionStatisticsGetGlobalCollectionStatistics } from "../funcs/collectionStatisticsGetGlobalCollectionStatistics.js";
import { collectionStatisticsGetGlobalCollectionStatisticsByIds } from "../funcs/collectionStatisticsGetGlobalCollectionStatisticsByIds.js";
import { collectionStatisticsGetOwners } from "../funcs/collectionStatisticsGetOwners.js";
import { collectionStatisticsGetPeriodCollectionStatistics } from "../funcs/collectionStatisticsGetPeriodCollectionStatistics.js";
import { collectionStatisticsGetPeriodCollectionStatisticsByIds } from "../funcs/collectionStatisticsGetPeriodCollectionStatisticsByIds.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class CollectionStatistics extends ClientSDK {
  /**
   * Get global (period-independent) statistics by collection ID
   *
   * @remarks
   * Global collection statistics by ID
   */
  async getGlobalCollectionStatistics(
    request: operations.GetGlobalCollectionStatisticsRequest,
    options?: RequestOptions,
  ): Promise<models.OlapGlobalCollectionStatisticsResponse> {
    return unwrapAsync(collectionStatisticsGetGlobalCollectionStatistics(
      this,
      request,
      options,
    ));
  }

  /**
   * Get global (period-independent) statistics by collection IDs
   *
   * @remarks
   * Global collection statistics by IDs
   */
  async getGlobalCollectionStatisticsByIds(
    request: Array<string>,
    options?: RequestOptions,
  ): Promise<Array<models.OlapGlobalCollectionStatisticsResponse>> {
    return unwrapAsync(collectionStatisticsGetGlobalCollectionStatisticsByIds(
      this,
      request,
      options,
    ));
  }

  /**
   * Get period-based statistics by collection ID
   *
   * @remarks
   * Period-based collection statistics by ID
   */
  async getPeriodCollectionStatistics(
    request: operations.GetPeriodCollectionStatisticsRequest,
    options?: RequestOptions,
  ): Promise<models.OlapPeriodCollectionStatisticsResponse> {
    return unwrapAsync(collectionStatisticsGetPeriodCollectionStatistics(
      this,
      request,
      options,
    ));
  }

  /**
   * Get period-based statistics by collection IDs
   *
   * @remarks
   * Period-based collection statistics by IDs
   */
  async getPeriodCollectionStatisticsByIds(
    request: models.OlapPeriodCollectionsByIdsStatisticsRequest,
    options?: RequestOptions,
  ): Promise<Array<models.OlapPeriodCollectionStatisticsResponse>> {
    return unwrapAsync(collectionStatisticsGetPeriodCollectionStatisticsByIds(
      this,
      request,
      options,
    ));
  }

  /**
   * Get distribution of the number of owned items by owner
   *
   * @remarks
   * Returns list of owners of items in the collection along with the number of owned items
   */
  async getOwners(
    request: operations.GetOwnersRequest,
    options?: RequestOptions,
  ): Promise<models.OlapOwnerStatistics> {
    return unwrapAsync(collectionStatisticsGetOwners(
      this,
      request,
      options,
    ));
  }

  /**
   * Get distribution of the number of bids by price
   *
   * @remarks
   * Returns list of bid prices with number of bids and bidders
   */
  async getBidsByPrice(
    request: operations.GetBidsByPriceRequest,
    options?: RequestOptions,
  ): Promise<models.OlapBidsByPriceStatistics> {
    return unwrapAsync(collectionStatisticsGetBidsByPrice(
      this,
      request,
      options,
    ));
  }
}
