/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectionLeaderBoardGetCollectionLeaderboard } from "../funcs/collectionLeaderBoardGetCollectionLeaderboard.js";
import { collectionLeaderBoardGetCollectionLeaderboardByOwner } from "../funcs/collectionLeaderBoardGetCollectionLeaderboardByOwner.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class CollectionLeaderBoard extends ClientSDK {
  /**
   * Get NFT Collections leaderboard
   *
   * @remarks
   * Collections leaderboard
   */
  async getCollectionLeaderboard(
    request: operations.GetCollectionLeaderboardRequest,
    options?: RequestOptions,
  ): Promise<models.OlapCollectionLeaderboardResponse> {
    return unwrapAsync(collectionLeaderBoardGetCollectionLeaderboard(
      this,
      request,
      options,
    ));
  }

  /**
   * Get NFT Collections leaderboard for a specific owner adresses
   *
   * @remarks
   * User collections leaderboard
   */
  async getCollectionLeaderboardByOwner(
    request: operations.GetCollectionLeaderboardByOwnerRequest,
    options?: RequestOptions,
  ): Promise<models.OlapCollectionLeaderboardResponse> {
    return unwrapAsync(collectionLeaderBoardGetCollectionLeaderboardByOwner(
      this,
      request,
      options,
    ));
  }
}
