/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { encodeOperationsEncode } from "../funcs/encodeOperationsEncode.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class EncodeOperations extends ClientSDK {
  /**
   * Generate order encode data for sign operations
   *
   * @remarks
   * Generate order encode data for sign operations
   */
  async encode(
    request: models.OrderForm,
    options?: RequestOptions,
  ): Promise<models.EncodedOrder> {
    return unwrapAsync(encodeOperationsEncode(
      this,
      request,
      options,
    ));
  }
}
