/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nftCollectionsGenerateTokenId } from "../funcs/nftCollectionsGenerateTokenId.js";
import { nftCollectionsGetAllCollections } from "../funcs/nftCollectionsGetAllCollections.js";
import { nftCollectionsGetCollectionById } from "../funcs/nftCollectionsGetCollectionById.js";
import { nftCollectionsGetCollectionsByOwner } from "../funcs/nftCollectionsGetCollectionsByOwner.js";
import { nftCollectionsRefreshCollectionItemsMeta } from "../funcs/nftCollectionsRefreshCollectionItemsMeta.js";
import { nftCollectionsResetCollectionMeta } from "../funcs/nftCollectionsResetCollectionMeta.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class NFTCollections extends ClientSDK {
  /**
   * Get NFT Collection by Id
   *
   * @remarks
   * Returns NFT Collection by Id
   */
  async getCollectionById(
    request: operations.GetCollectionByIdRequest,
    options?: RequestOptions,
  ): Promise<models.Collection> {
    return unwrapAsync(nftCollectionsGetCollectionById(
      this,
      request,
      options,
    ));
  }

  /**
   * Generate TokenId
   *
   * @remarks
   * Returns next available TokenId for specified minter
   */
  async generateTokenId(
    request: operations.GenerateTokenIdRequest,
    options?: RequestOptions,
  ): Promise<models.CollectionTokenId> {
    return unwrapAsync(nftCollectionsGenerateTokenId(
      this,
      request,
      options,
    ));
  }

  /**
   * Reset NFT metadata
   *
   * @remarks
   * Reloads metadata for all NFTs in the Collection (see 'Reset NFT metadata' API)
   */
  async refreshCollectionItemsMeta(
    request: operations.RefreshCollectionItemsMetaRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(nftCollectionsRefreshCollectionItemsMeta(
      this,
      request,
      options,
    ));
  }

  /**
   * Reset Collection metadata
   *
   * @remarks
   * Reloads metadata for Collection (NOT for collection's NFTs)
   */
  async resetCollectionMeta(
    request: operations.ResetCollectionMetaRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(nftCollectionsResetCollectionMeta(
      this,
      request,
      options,
    ));
  }

  /**
   * Get NFT Collections owned by user
   *
   * @remarks
   * Returns list of NFT Collections belong to specified user
   */
  async getCollectionsByOwner(
    request: operations.GetCollectionsByOwnerRequest,
    options?: RequestOptions,
  ): Promise<models.Collections> {
    return unwrapAsync(nftCollectionsGetCollectionsByOwner(
      this,
      request,
      options,
    ));
  }

  /**
   * Get all NFT Collections
   *
   * @remarks
   * Returns all NFT Collections in accordance with specified filters
   */
  async getAllCollections(
    request: operations.GetAllCollectionsRequest,
    options?: RequestOptions,
  ): Promise<models.Collections> {
    return unwrapAsync(nftCollectionsGetAllCollections(
      this,
      request,
      options,
    ));
  }
}
