/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { reconciliationGetReconciliationItems } from "../funcs/reconciliationGetReconciliationItems.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Reconciliation extends ClientSDK {
  /**
   * Get IDs of items updated after a specific datetime.
   *
   * @remarks
   * Return short view of items updated after a specific datetime.
   */
  async getReconciliationItems(
    request: operations.GetReconciliationItemsRequest,
    options?: RequestOptions,
  ): Promise<models.ReconciliationEntities> {
    return unwrapAsync(reconciliationGetReconciliationItems(
      this,
      request,
      options,
    ));
  }
}
