/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { searchAPISearchActivities } from "../funcs/searchAPISearchActivities.js";
import { searchAPISearchCollection } from "../funcs/searchAPISearchCollection.js";
import { searchAPISearchDuplicatedItems } from "../funcs/searchAPISearchDuplicatedItems.js";
import { searchAPISearchItems } from "../funcs/searchAPISearchItems.js";
import { searchAPISearchOwnerships } from "../funcs/searchAPISearchOwnerships.js";
import { searchAPISearchTraits } from "../funcs/searchAPISearchTraits.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SearchAPI extends ClientSDK {
  /**
   * Search NFT collection traits
   *
   * @remarks
   * Returns aggregation of existing traits for specified collections with counter for each trait type/value.\  This is full-text-search, where you can specify filter for trait keys not precisely\  (for example, results `back` filter include `Background` trait)
   */
  async searchTraits(
    request: operations.SearchTraitsRequest,
    options?: RequestOptions,
  ): Promise<models.Traits> {
    return unwrapAsync(searchAPISearchTraits(
      this,
      request,
      options,
    ));
  }

  /**
   * Search NFTs
   *
   * @remarks
   * Advanced search returns NFTs satisfying provided filter
   */
  async searchItems(
    request: models.ItemsSearchRequest,
    options?: RequestOptions,
  ): Promise<models.Items> {
    return unwrapAsync(searchAPISearchItems(
      this,
      request,
      options,
    ));
  }

  /**
   * Search Duplicated NFTs
   *
   * @remarks
   * Advanced search returns NFTs satisfying provided filter and with duplicated traits
   */
  async searchDuplicatedItems(
    request: models.DuplicatedItemsSearchRequest,
    options?: RequestOptions,
  ): Promise<models.DuplicatedItemGroups> {
    return unwrapAsync(searchAPISearchDuplicatedItems(
      this,
      request,
      options,
    ));
  }

  /**
   * Search NFT Ownerships
   *
   * @remarks
   * Advanced search returns NFT Ownerships satisfying provided filter
   */
  async searchOwnerships(
    request: models.OwnershipSearchRequest,
    options?: RequestOptions,
  ): Promise<models.Ownerships> {
    return unwrapAsync(searchAPISearchOwnerships(
      this,
      request,
      options,
    ));
  }

  /**
   * Search Activities
   *
   * @remarks
   * Advanced search returns Activities satisfying provided filter
   */
  async searchActivities(
    request: models.ActivitySearchRequest,
    options?: RequestOptions,
  ): Promise<models.Activities> {
    return unwrapAsync(searchAPISearchActivities(
      this,
      request,
      options,
    ));
  }

  /**
   * Search NFT Collections
   *
   * @remarks
   * Advanced search returns NFT Collections satisfying provided filter
   */
  async searchCollection(
    request: models.CollectionsSearchRequest,
    options?: RequestOptions,
  ): Promise<models.Collections> {
    return unwrapAsync(searchAPISearchCollection(
      this,
      request,
      options,
    ));
  }
}
