/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { signatureOperationsGetInput } from "../funcs/signatureOperationsGetInput.js";
import { signatureOperationsValidate } from "../funcs/signatureOperationsValidate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SignatureOperations extends ClientSDK {
  /**
   * Check Order's signature
   *
   * @remarks
   * Checks if Order's signature is valid and returns 'true' if it so, 'false' otherwise
   */
  async validate(
    request: models.SignatureValidationForm,
    options?: RequestOptions,
  ): Promise<boolean> {
    return unwrapAsync(signatureOperationsValidate(
      this,
      request,
      options,
    ));
  }

  /**
   * Generate signed input
   *
   * @remarks
   * Generate input string to sign operation
   */
  async getInput(
    request: models.SignatureInputForm,
    options?: RequestOptions,
  ): Promise<models.SignatureInput> {
    return unwrapAsync(signatureOperationsGetInput(
      this,
      request,
      options,
    ));
  }
}
