/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userBalancesGetBalance } from "../funcs/userBalancesGetBalance.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class UserBalances extends ClientSDK {
  /**
   * Get balance
   *
   * @remarks
   * Return user's balance of specified currency
   */
  async getBalance(
    request: operations.GetBalanceRequest,
    options?: RequestOptions,
  ): Promise<models.Balance> {
    return unwrapAsync(userBalancesGetBalance(
      this,
      request,
      options,
    ));
  }
}
