/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GenerateTokenIdRequest = {
  /**
   * Address of the NFT collection
   */
  collection: string;
  /**
   * Minter address
   */
  minter: string;
};

/** @internal */
export const GenerateTokenIdRequest$inboundSchema: z.ZodType<
  GenerateTokenIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection: z.string(),
  minter: z.string(),
});

/** @internal */
export type GenerateTokenIdRequest$Outbound = {
  collection: string;
  minter: string;
};

/** @internal */
export const GenerateTokenIdRequest$outboundSchema: z.ZodType<
  GenerateTokenIdRequest$Outbound,
  z.ZodTypeDef,
  GenerateTokenIdRequest
> = z.object({
  collection: z.string(),
  minter: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GenerateTokenIdRequest$ {
  /** @deprecated use `GenerateTokenIdRequest$inboundSchema` instead. */
  export const inboundSchema = GenerateTokenIdRequest$inboundSchema;
  /** @deprecated use `GenerateTokenIdRequest$outboundSchema` instead. */
  export const outboundSchema = GenerateTokenIdRequest$outboundSchema;
  /** @deprecated use `GenerateTokenIdRequest$Outbound` instead. */
  export type Outbound = GenerateTokenIdRequest$Outbound;
}

export function generateTokenIdRequestToJSON(
  generateTokenIdRequest: GenerateTokenIdRequest,
): string {
  return JSON.stringify(
    GenerateTokenIdRequest$outboundSchema.parse(generateTokenIdRequest),
  );
}

export function generateTokenIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GenerateTokenIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenerateTokenIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenerateTokenIdRequest' from JSON`,
  );
}
