/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetAllActivitiesSyncRequest = {
  /**
   * Type of the blockchain network
   */
  blockchain: models.Blockchain;
  /**
   * Continuation token from the previous response
   */
  continuation?: string | undefined;
  /**
   * The number of items to return
   */
  size?: number | undefined;
  /**
   * Sorting by data base update time
   */
  sort?: models.SyncSort | undefined;
  /**
   * Filtering by activity type
   */
  type?: models.SyncType | undefined;
};

/** @internal */
export const GetAllActivitiesSyncRequest$inboundSchema: z.ZodType<
  GetAllActivitiesSyncRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  blockchain: models.Blockchain$inboundSchema,
  continuation: z.string().optional(),
  size: z.number().int().optional(),
  sort: models.SyncSort$inboundSchema.optional(),
  type: models.SyncType$inboundSchema.optional(),
});

/** @internal */
export type GetAllActivitiesSyncRequest$Outbound = {
  blockchain: string;
  continuation?: string | undefined;
  size?: number | undefined;
  sort?: string | undefined;
  type?: string | undefined;
};

/** @internal */
export const GetAllActivitiesSyncRequest$outboundSchema: z.ZodType<
  GetAllActivitiesSyncRequest$Outbound,
  z.ZodTypeDef,
  GetAllActivitiesSyncRequest
> = z.object({
  blockchain: models.Blockchain$outboundSchema,
  continuation: z.string().optional(),
  size: z.number().int().optional(),
  sort: models.SyncSort$outboundSchema.optional(),
  type: models.SyncType$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAllActivitiesSyncRequest$ {
  /** @deprecated use `GetAllActivitiesSyncRequest$inboundSchema` instead. */
  export const inboundSchema = GetAllActivitiesSyncRequest$inboundSchema;
  /** @deprecated use `GetAllActivitiesSyncRequest$outboundSchema` instead. */
  export const outboundSchema = GetAllActivitiesSyncRequest$outboundSchema;
  /** @deprecated use `GetAllActivitiesSyncRequest$Outbound` instead. */
  export type Outbound = GetAllActivitiesSyncRequest$Outbound;
}

export function getAllActivitiesSyncRequestToJSON(
  getAllActivitiesSyncRequest: GetAllActivitiesSyncRequest,
): string {
  return JSON.stringify(
    GetAllActivitiesSyncRequest$outboundSchema.parse(
      getAllActivitiesSyncRequest,
    ),
  );
}

export function getAllActivitiesSyncRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAllActivitiesSyncRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllActivitiesSyncRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllActivitiesSyncRequest' from JSON`,
  );
}
