/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetActivitiesByUserRequest = {
  /**
   * Activity type
   */
  type: Array<models.UserActivityType>;
  blockchains?: Array<models.Blockchain> | undefined;
  /**
   * Addresses of the users
   */
  user: Array<string>;
  /**
   * Currency for BID and CANCEL_BID activity types
   */
  bidCurrencies?: Array<string> | undefined;
  /**
   * Lower time border of data
   */
  from?: Date | undefined;
  /**
   * Upper time border of data
   */
  to?: Date | undefined;
  /**
   * Continuation token from the previous response
   */
  continuation?: string | undefined;
  /**
   * Combined continuation token from the previous response
   */
  cursor?: string | undefined;
  /**
   * The number of items to return
   */
  size?: number | undefined;
  /**
   * Sorting by data update time
   */
  sort?: models.ActivitySort | undefined;
};

/** @internal */
export const GetActivitiesByUserRequest$inboundSchema: z.ZodType<
  GetActivitiesByUserRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.array(models.UserActivityType$inboundSchema),
  blockchains: z.array(models.Blockchain$inboundSchema).optional(),
  user: z.array(z.string()),
  bidCurrencies: z.array(z.string()).optional(),
  from: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  to: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  continuation: z.string().optional(),
  cursor: z.string().optional(),
  size: z.number().int().optional(),
  sort: models.ActivitySort$inboundSchema.optional(),
});

/** @internal */
export type GetActivitiesByUserRequest$Outbound = {
  type: Array<string>;
  blockchains?: Array<string> | undefined;
  user: Array<string>;
  bidCurrencies?: Array<string> | undefined;
  from?: string | undefined;
  to?: string | undefined;
  continuation?: string | undefined;
  cursor?: string | undefined;
  size?: number | undefined;
  sort?: string | undefined;
};

/** @internal */
export const GetActivitiesByUserRequest$outboundSchema: z.ZodType<
  GetActivitiesByUserRequest$Outbound,
  z.ZodTypeDef,
  GetActivitiesByUserRequest
> = z.object({
  type: z.array(models.UserActivityType$outboundSchema),
  blockchains: z.array(models.Blockchain$outboundSchema).optional(),
  user: z.array(z.string()),
  bidCurrencies: z.array(z.string()).optional(),
  from: z.date().transform(v => v.toISOString()).optional(),
  to: z.date().transform(v => v.toISOString()).optional(),
  continuation: z.string().optional(),
  cursor: z.string().optional(),
  size: z.number().int().optional(),
  sort: models.ActivitySort$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetActivitiesByUserRequest$ {
  /** @deprecated use `GetActivitiesByUserRequest$inboundSchema` instead. */
  export const inboundSchema = GetActivitiesByUserRequest$inboundSchema;
  /** @deprecated use `GetActivitiesByUserRequest$outboundSchema` instead. */
  export const outboundSchema = GetActivitiesByUserRequest$outboundSchema;
  /** @deprecated use `GetActivitiesByUserRequest$Outbound` instead. */
  export type Outbound = GetActivitiesByUserRequest$Outbound;
}

export function getActivitiesByUserRequestToJSON(
  getActivitiesByUserRequest: GetActivitiesByUserRequest,
): string {
  return JSON.stringify(
    GetActivitiesByUserRequest$outboundSchema.parse(getActivitiesByUserRequest),
  );
}

export function getActivitiesByUserRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetActivitiesByUserRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetActivitiesByUserRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetActivitiesByUserRequest' from JSON`,
  );
}
