/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetBidsByPriceRequest = {
  /**
   * Collection ID
   */
  id: string;
  /**
   * Continuation token from the previous response
   */
  continuation?: string | undefined;
  /**
   * The number of results to return
   */
  size?: number | undefined;
  /**
   * Result sorting
   */
  sort?: models.OlapBidsByPriceSort | undefined;
};

/** @internal */
export const GetBidsByPriceRequest$inboundSchema: z.ZodType<
  GetBidsByPriceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  continuation: z.string().optional(),
  size: z.number().int().optional(),
  sort: models.OlapBidsByPriceSort$inboundSchema.default("PRICE"),
});

/** @internal */
export type GetBidsByPriceRequest$Outbound = {
  id: string;
  continuation?: string | undefined;
  size?: number | undefined;
  sort: string;
};

/** @internal */
export const GetBidsByPriceRequest$outboundSchema: z.ZodType<
  GetBidsByPriceRequest$Outbound,
  z.ZodTypeDef,
  GetBidsByPriceRequest
> = z.object({
  id: z.string(),
  continuation: z.string().optional(),
  size: z.number().int().optional(),
  sort: models.OlapBidsByPriceSort$outboundSchema.default("PRICE"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBidsByPriceRequest$ {
  /** @deprecated use `GetBidsByPriceRequest$inboundSchema` instead. */
  export const inboundSchema = GetBidsByPriceRequest$inboundSchema;
  /** @deprecated use `GetBidsByPriceRequest$outboundSchema` instead. */
  export const outboundSchema = GetBidsByPriceRequest$outboundSchema;
  /** @deprecated use `GetBidsByPriceRequest$Outbound` instead. */
  export type Outbound = GetBidsByPriceRequest$Outbound;
}

export function getBidsByPriceRequestToJSON(
  getBidsByPriceRequest: GetBidsByPriceRequest,
): string {
  return JSON.stringify(
    GetBidsByPriceRequest$outboundSchema.parse(getBidsByPriceRequest),
  );
}

export function getBidsByPriceRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetBidsByPriceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBidsByPriceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBidsByPriceRequest' from JSON`,
  );
}
