/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetCollectionStatsRequest = {
  /**
   * Identifier of collection
   */
  collection: string;
  /**
   * Currency of statistics
   */
  currency?: models.OlapCurrencyType | undefined;
};

/** @internal */
export const GetCollectionStatsRequest$inboundSchema: z.ZodType<
  GetCollectionStatsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection: z.string(),
  currency: models.OlapCurrencyType$inboundSchema.default("USD"),
});

/** @internal */
export type GetCollectionStatsRequest$Outbound = {
  collection: string;
  currency: string;
};

/** @internal */
export const GetCollectionStatsRequest$outboundSchema: z.ZodType<
  GetCollectionStatsRequest$Outbound,
  z.ZodTypeDef,
  GetCollectionStatsRequest
> = z.object({
  collection: z.string(),
  currency: models.OlapCurrencyType$outboundSchema.default("USD"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCollectionStatsRequest$ {
  /** @deprecated use `GetCollectionStatsRequest$inboundSchema` instead. */
  export const inboundSchema = GetCollectionStatsRequest$inboundSchema;
  /** @deprecated use `GetCollectionStatsRequest$outboundSchema` instead. */
  export const outboundSchema = GetCollectionStatsRequest$outboundSchema;
  /** @deprecated use `GetCollectionStatsRequest$Outbound` instead. */
  export type Outbound = GetCollectionStatsRequest$Outbound;
}

export function getCollectionStatsRequestToJSON(
  getCollectionStatsRequest: GetCollectionStatsRequest,
): string {
  return JSON.stringify(
    GetCollectionStatsRequest$outboundSchema.parse(getCollectionStatsRequest),
  );
}

export function getCollectionStatsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetCollectionStatsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCollectionStatsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCollectionStatsRequest' from JSON`,
  );
}
