/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetCollectionLeaderboardRequest = {
  /**
   * Blockchain networks
   */
  blockchains?: Array<models.OlapBlockchain> | undefined;
  /**
   * Time period for aggregation
   */
  period?: models.OlapPeriod | undefined;
  /**
   * Collections sorting
   */
  sort?: models.OlapLeaderboardSort | undefined;
  /**
   * Collections sorting direction
   */
  direction?: models.OlapLeaderboardSortDirection | undefined;
  /**
   * Limit of records in leaderboard
   */
  limit?: number | undefined;
  /**
   * Offset reference
   */
  offset?: number | undefined;
};

/** @internal */
export const GetCollectionLeaderboardRequest$inboundSchema: z.ZodType<
  GetCollectionLeaderboardRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  blockchains: z.array(models.OlapBlockchain$inboundSchema).optional(),
  period: models.OlapPeriod$inboundSchema.optional(),
  sort: models.OlapLeaderboardSort$inboundSchema.default("VOLUME"),
  direction: models.OlapLeaderboardSortDirection$inboundSchema.default("DESC"),
  limit: z.number().int().default(10),
  offset: z.number().int().default(0),
});

/** @internal */
export type GetCollectionLeaderboardRequest$Outbound = {
  blockchains?: Array<string> | undefined;
  period?: string | undefined;
  sort: string;
  direction: string;
  limit: number;
  offset: number;
};

/** @internal */
export const GetCollectionLeaderboardRequest$outboundSchema: z.ZodType<
  GetCollectionLeaderboardRequest$Outbound,
  z.ZodTypeDef,
  GetCollectionLeaderboardRequest
> = z.object({
  blockchains: z.array(models.OlapBlockchain$outboundSchema).optional(),
  period: models.OlapPeriod$outboundSchema.optional(),
  sort: models.OlapLeaderboardSort$outboundSchema.default("VOLUME"),
  direction: models.OlapLeaderboardSortDirection$outboundSchema.default("DESC"),
  limit: z.number().int().default(10),
  offset: z.number().int().default(0),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCollectionLeaderboardRequest$ {
  /** @deprecated use `GetCollectionLeaderboardRequest$inboundSchema` instead. */
  export const inboundSchema = GetCollectionLeaderboardRequest$inboundSchema;
  /** @deprecated use `GetCollectionLeaderboardRequest$outboundSchema` instead. */
  export const outboundSchema = GetCollectionLeaderboardRequest$outboundSchema;
  /** @deprecated use `GetCollectionLeaderboardRequest$Outbound` instead. */
  export type Outbound = GetCollectionLeaderboardRequest$Outbound;
}

export function getCollectionLeaderboardRequestToJSON(
  getCollectionLeaderboardRequest: GetCollectionLeaderboardRequest,
): string {
  return JSON.stringify(
    GetCollectionLeaderboardRequest$outboundSchema.parse(
      getCollectionLeaderboardRequest,
    ),
  );
}

export function getCollectionLeaderboardRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetCollectionLeaderboardRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCollectionLeaderboardRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCollectionLeaderboardRequest' from JSON`,
  );
}
