/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetFloorPriceRequest = {
  /**
   * Identifier of collection
   */
  collection: string;
  /**
   * Currency of statistics
   */
  currency?: models.OlapCurrencyType | undefined;
  /**
   * Filters of statistics
   */
  filters?: string | undefined;
};

/** @internal */
export const GetFloorPriceRequest$inboundSchema: z.ZodType<
  GetFloorPriceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection: z.string(),
  currency: models.OlapCurrencyType$inboundSchema.default("USD"),
  filters: z.string().optional(),
});

/** @internal */
export type GetFloorPriceRequest$Outbound = {
  collection: string;
  currency: string;
  filters?: string | undefined;
};

/** @internal */
export const GetFloorPriceRequest$outboundSchema: z.ZodType<
  GetFloorPriceRequest$Outbound,
  z.ZodTypeDef,
  GetFloorPriceRequest
> = z.object({
  collection: z.string(),
  currency: models.OlapCurrencyType$outboundSchema.default("USD"),
  filters: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetFloorPriceRequest$ {
  /** @deprecated use `GetFloorPriceRequest$inboundSchema` instead. */
  export const inboundSchema = GetFloorPriceRequest$inboundSchema;
  /** @deprecated use `GetFloorPriceRequest$outboundSchema` instead. */
  export const outboundSchema = GetFloorPriceRequest$outboundSchema;
  /** @deprecated use `GetFloorPriceRequest$Outbound` instead. */
  export type Outbound = GetFloorPriceRequest$Outbound;
}

export function getFloorPriceRequestToJSON(
  getFloorPriceRequest: GetFloorPriceRequest,
): string {
  return JSON.stringify(
    GetFloorPriceRequest$outboundSchema.parse(getFloorPriceRequest),
  );
}

export function getFloorPriceRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetFloorPriceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetFloorPriceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetFloorPriceRequest' from JSON`,
  );
}
