/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetGmvRequest = {
  /**
   * Identifier of collection
   */
  collection: string;
  /**
   * Currency of statistics
   */
  currency?: models.OlapCurrencyType | undefined;
  /**
   * Time period of statistics. Default: D1
   */
  period?: models.OlapPeriod | undefined;
  /**
   * Filters of statistics
   */
  filters?: string | undefined;
};

/** @internal */
export const GetGmvRequest$inboundSchema: z.ZodType<
  GetGmvRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection: z.string(),
  currency: models.OlapCurrencyType$inboundSchema.default("USD"),
  period: models.OlapPeriod$inboundSchema.optional(),
  filters: z.string().optional(),
});

/** @internal */
export type GetGmvRequest$Outbound = {
  collection: string;
  currency: string;
  period?: string | undefined;
  filters?: string | undefined;
};

/** @internal */
export const GetGmvRequest$outboundSchema: z.ZodType<
  GetGmvRequest$Outbound,
  z.ZodTypeDef,
  GetGmvRequest
> = z.object({
  collection: z.string(),
  currency: models.OlapCurrencyType$outboundSchema.default("USD"),
  period: models.OlapPeriod$outboundSchema.optional(),
  filters: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetGmvRequest$ {
  /** @deprecated use `GetGmvRequest$inboundSchema` instead. */
  export const inboundSchema = GetGmvRequest$inboundSchema;
  /** @deprecated use `GetGmvRequest$outboundSchema` instead. */
  export const outboundSchema = GetGmvRequest$outboundSchema;
  /** @deprecated use `GetGmvRequest$Outbound` instead. */
  export type Outbound = GetGmvRequest$Outbound;
}

export function getGmvRequestToJSON(getGmvRequest: GetGmvRequest): string {
  return JSON.stringify(GetGmvRequest$outboundSchema.parse(getGmvRequest));
}

export function getGmvRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetGmvRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGmvRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGmvRequest' from JSON`,
  );
}
