/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetItemsByCollectionRequest = {
  /**
   * Address of the collection
   */
  collection: string;
  /**
   * Continuation token from the previous response
   */
  continuation?: string | undefined;
  /**
   * The number of items to return
   */
  size?: number | undefined;
  /**
   * Search engine to use for search
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  searchEngine?: models.SearchEngine | undefined;
};

/** @internal */
export const GetItemsByCollectionRequest$inboundSchema: z.ZodType<
  GetItemsByCollectionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection: z.string(),
  continuation: z.string().optional(),
  size: z.number().int().optional(),
  searchEngine: models.SearchEngine$inboundSchema.optional(),
});

/** @internal */
export type GetItemsByCollectionRequest$Outbound = {
  collection: string;
  continuation?: string | undefined;
  size?: number | undefined;
  searchEngine?: string | undefined;
};

/** @internal */
export const GetItemsByCollectionRequest$outboundSchema: z.ZodType<
  GetItemsByCollectionRequest$Outbound,
  z.ZodTypeDef,
  GetItemsByCollectionRequest
> = z.object({
  collection: z.string(),
  continuation: z.string().optional(),
  size: z.number().int().optional(),
  searchEngine: models.SearchEngine$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetItemsByCollectionRequest$ {
  /** @deprecated use `GetItemsByCollectionRequest$inboundSchema` instead. */
  export const inboundSchema = GetItemsByCollectionRequest$inboundSchema;
  /** @deprecated use `GetItemsByCollectionRequest$outboundSchema` instead. */
  export const outboundSchema = GetItemsByCollectionRequest$outboundSchema;
  /** @deprecated use `GetItemsByCollectionRequest$Outbound` instead. */
  export type Outbound = GetItemsByCollectionRequest$Outbound;
}

export function getItemsByCollectionRequestToJSON(
  getItemsByCollectionRequest: GetItemsByCollectionRequest,
): string {
  return JSON.stringify(
    GetItemsByCollectionRequest$outboundSchema.parse(
      getItemsByCollectionRequest,
    ),
  );
}

export function getItemsByCollectionRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetItemsByCollectionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetItemsByCollectionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetItemsByCollectionRequest' from JSON`,
  );
}
