/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetItemsByCreatorRequest = {
  /**
   * Since user's address can be present in several blockchains (for example, ETHEREUM and POLYGON),  you can use this filter to get Orders only for specific blockchains.  Or keep it empty to get Order from all blockchains
   */
  blockchains?: Array<models.Blockchain> | undefined;
  /**
   * Address of the item creator
   */
  creator: string;
  /**
   * Continuation token from the previous response
   */
  continuation?: string | undefined;
  /**
   * The number of items to return
   */
  size?: number | undefined;
  /**
   * Search engine to use for search
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  searchEngine?: models.SearchEngine | undefined;
};

/** @internal */
export const GetItemsByCreatorRequest$inboundSchema: z.ZodType<
  GetItemsByCreatorRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  blockchains: z.array(models.Blockchain$inboundSchema).optional(),
  creator: z.string(),
  continuation: z.string().optional(),
  size: z.number().int().optional(),
  searchEngine: models.SearchEngine$inboundSchema.optional(),
});

/** @internal */
export type GetItemsByCreatorRequest$Outbound = {
  blockchains?: Array<string> | undefined;
  creator: string;
  continuation?: string | undefined;
  size?: number | undefined;
  searchEngine?: string | undefined;
};

/** @internal */
export const GetItemsByCreatorRequest$outboundSchema: z.ZodType<
  GetItemsByCreatorRequest$Outbound,
  z.ZodTypeDef,
  GetItemsByCreatorRequest
> = z.object({
  blockchains: z.array(models.Blockchain$outboundSchema).optional(),
  creator: z.string(),
  continuation: z.string().optional(),
  size: z.number().int().optional(),
  searchEngine: models.SearchEngine$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetItemsByCreatorRequest$ {
  /** @deprecated use `GetItemsByCreatorRequest$inboundSchema` instead. */
  export const inboundSchema = GetItemsByCreatorRequest$inboundSchema;
  /** @deprecated use `GetItemsByCreatorRequest$outboundSchema` instead. */
  export const outboundSchema = GetItemsByCreatorRequest$outboundSchema;
  /** @deprecated use `GetItemsByCreatorRequest$Outbound` instead. */
  export type Outbound = GetItemsByCreatorRequest$Outbound;
}

export function getItemsByCreatorRequestToJSON(
  getItemsByCreatorRequest: GetItemsByCreatorRequest,
): string {
  return JSON.stringify(
    GetItemsByCreatorRequest$outboundSchema.parse(getItemsByCreatorRequest),
  );
}

export function getItemsByCreatorRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetItemsByCreatorRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetItemsByCreatorRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetItemsByCreatorRequest' from JSON`,
  );
}
