/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetItemByIdRequest = {
  /**
   * ItemId in format `ETHEREUM:${token}:${tokenId}`
   */
  itemId: string;
};

/** @internal */
export const GetItemByIdRequest$inboundSchema: z.ZodType<
  GetItemByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  itemId: z.string(),
});

/** @internal */
export type GetItemByIdRequest$Outbound = {
  itemId: string;
};

/** @internal */
export const GetItemByIdRequest$outboundSchema: z.ZodType<
  GetItemByIdRequest$Outbound,
  z.ZodTypeDef,
  GetItemByIdRequest
> = z.object({
  itemId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetItemByIdRequest$ {
  /** @deprecated use `GetItemByIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetItemByIdRequest$inboundSchema;
  /** @deprecated use `GetItemByIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetItemByIdRequest$outboundSchema;
  /** @deprecated use `GetItemByIdRequest$Outbound` instead. */
  export type Outbound = GetItemByIdRequest$Outbound;
}

export function getItemByIdRequestToJSON(
  getItemByIdRequest: GetItemByIdRequest,
): string {
  return JSON.stringify(
    GetItemByIdRequest$outboundSchema.parse(getItemByIdRequest),
  );
}

export function getItemByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetItemByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetItemByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetItemByIdRequest' from JSON`,
  );
}
