/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetItemsByOwnerWithOwnershipRequest = {
  /**
   * Address of the owner
   */
  owner: string;
  /**
   * Continuation token from the previous response
   */
  continuation?: string | undefined;
  /**
   * The number of items to return
   */
  size?: number | undefined;
  /**
   * Search engine to use for search
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  searchEngine?: models.SearchEngine | undefined;
};

/** @internal */
export const GetItemsByOwnerWithOwnershipRequest$inboundSchema: z.ZodType<
  GetItemsByOwnerWithOwnershipRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  owner: z.string(),
  continuation: z.string().optional(),
  size: z.number().int().optional(),
  searchEngine: models.SearchEngine$inboundSchema.optional(),
});

/** @internal */
export type GetItemsByOwnerWithOwnershipRequest$Outbound = {
  owner: string;
  continuation?: string | undefined;
  size?: number | undefined;
  searchEngine?: string | undefined;
};

/** @internal */
export const GetItemsByOwnerWithOwnershipRequest$outboundSchema: z.ZodType<
  GetItemsByOwnerWithOwnershipRequest$Outbound,
  z.ZodTypeDef,
  GetItemsByOwnerWithOwnershipRequest
> = z.object({
  owner: z.string(),
  continuation: z.string().optional(),
  size: z.number().int().optional(),
  searchEngine: models.SearchEngine$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetItemsByOwnerWithOwnershipRequest$ {
  /** @deprecated use `GetItemsByOwnerWithOwnershipRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetItemsByOwnerWithOwnershipRequest$inboundSchema;
  /** @deprecated use `GetItemsByOwnerWithOwnershipRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetItemsByOwnerWithOwnershipRequest$outboundSchema;
  /** @deprecated use `GetItemsByOwnerWithOwnershipRequest$Outbound` instead. */
  export type Outbound = GetItemsByOwnerWithOwnershipRequest$Outbound;
}

export function getItemsByOwnerWithOwnershipRequestToJSON(
  getItemsByOwnerWithOwnershipRequest: GetItemsByOwnerWithOwnershipRequest,
): string {
  return JSON.stringify(
    GetItemsByOwnerWithOwnershipRequest$outboundSchema.parse(
      getItemsByOwnerWithOwnershipRequest,
    ),
  );
}

export function getItemsByOwnerWithOwnershipRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetItemsByOwnerWithOwnershipRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetItemsByOwnerWithOwnershipRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetItemsByOwnerWithOwnershipRequest' from JSON`,
  );
}
