/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetListedRequest = {
  /**
   * Identifier of collection
   */
  collection: string;
};

/** @internal */
export const GetListedRequest$inboundSchema: z.ZodType<
  GetListedRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection: z.string(),
});

/** @internal */
export type GetListedRequest$Outbound = {
  collection: string;
};

/** @internal */
export const GetListedRequest$outboundSchema: z.ZodType<
  GetListedRequest$Outbound,
  z.ZodTypeDef,
  GetListedRequest
> = z.object({
  collection: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetListedRequest$ {
  /** @deprecated use `GetListedRequest$inboundSchema` instead. */
  export const inboundSchema = GetListedRequest$inboundSchema;
  /** @deprecated use `GetListedRequest$outboundSchema` instead. */
  export const outboundSchema = GetListedRequest$outboundSchema;
  /** @deprecated use `GetListedRequest$Outbound` instead. */
  export type Outbound = GetListedRequest$Outbound;
}

export function getListedRequestToJSON(
  getListedRequest: GetListedRequest,
): string {
  return JSON.stringify(
    GetListedRequest$outboundSchema.parse(getListedRequest),
  );
}

export function getListedRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetListedRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetListedRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetListedRequest' from JSON`,
  );
}
