/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetLazyItemByIdRequest = {
  /**
   * Item Id in format `ETHEREUM:${token}:${tokenId}`
   */
  itemId: string;
};

/** @internal */
export const GetLazyItemByIdRequest$inboundSchema: z.ZodType<
  GetLazyItemByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  itemId: z.string(),
});

/** @internal */
export type GetLazyItemByIdRequest$Outbound = {
  itemId: string;
};

/** @internal */
export const GetLazyItemByIdRequest$outboundSchema: z.ZodType<
  GetLazyItemByIdRequest$Outbound,
  z.ZodTypeDef,
  GetLazyItemByIdRequest
> = z.object({
  itemId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetLazyItemByIdRequest$ {
  /** @deprecated use `GetLazyItemByIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetLazyItemByIdRequest$inboundSchema;
  /** @deprecated use `GetLazyItemByIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetLazyItemByIdRequest$outboundSchema;
  /** @deprecated use `GetLazyItemByIdRequest$Outbound` instead. */
  export type Outbound = GetLazyItemByIdRequest$Outbound;
}

export function getLazyItemByIdRequestToJSON(
  getLazyItemByIdRequest: GetLazyItemByIdRequest,
): string {
  return JSON.stringify(
    GetLazyItemByIdRequest$outboundSchema.parse(getLazyItemByIdRequest),
  );
}

export function getLazyItemByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetLazyItemByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLazyItemByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLazyItemByIdRequest' from JSON`,
  );
}
