/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetOrderBidsByMakerRequest = {
  /**
   * Since user's address can be present in several blockchains (for example, ETHEREUM and POLYGON),  you can use this filter to get Orders only for specific blockchains.  Or keep it empty to get Order from all blockchains
   */
  maker: Array<string>;
  /**
   * Names of the blockchain networks. If no one specified, data from all blockchains will be returned
   */
  blockchains?: Array<models.Blockchain> | undefined;
  /**
   * The platform where the order was created
   */
  platform?: models.Platform | undefined;
  /**
   * The nft collection of order
   */
  collection?: Array<string> | undefined;
  /**
   * Address of the consumer to receive the commission for the order
   */
  origin?: string | undefined;
  /**
   * Order status
   */
  status?: Array<models.OrderStatus> | undefined;
  /**
   * Currencies for bids
   */
  currencies?: Array<string> | undefined;
  /**
   * Lower time border of data (timestamp)
   */
  start?: number | undefined;
  /**
   * Upper time border of data (timestamp)
   */
  end?: number | undefined;
  /**
   * Continuation token from the previous response
   */
  continuation?: string | undefined;
  /**
   * The number of items to return
   */
  size?: number | undefined;
  /**
   * Search engine to use for search
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  searchEngine?: models.SearchEngine | undefined;
};

/** @internal */
export const GetOrderBidsByMakerRequest$inboundSchema: z.ZodType<
  GetOrderBidsByMakerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  maker: z.array(z.string()),
  blockchains: z.array(models.Blockchain$inboundSchema).optional(),
  platform: models.Platform$inboundSchema.optional(),
  collection: z.array(z.string()).optional(),
  origin: z.string().optional(),
  status: z.array(models.OrderStatus$inboundSchema).optional(),
  currencies: z.array(z.string()).optional(),
  start: z.number().int().optional(),
  end: z.number().int().optional(),
  continuation: z.string().optional(),
  size: z.number().int().optional(),
  searchEngine: models.SearchEngine$inboundSchema.optional(),
});

/** @internal */
export type GetOrderBidsByMakerRequest$Outbound = {
  maker: Array<string>;
  blockchains?: Array<string> | undefined;
  platform?: string | undefined;
  collection?: Array<string> | undefined;
  origin?: string | undefined;
  status?: Array<string> | undefined;
  currencies?: Array<string> | undefined;
  start?: number | undefined;
  end?: number | undefined;
  continuation?: string | undefined;
  size?: number | undefined;
  searchEngine?: string | undefined;
};

/** @internal */
export const GetOrderBidsByMakerRequest$outboundSchema: z.ZodType<
  GetOrderBidsByMakerRequest$Outbound,
  z.ZodTypeDef,
  GetOrderBidsByMakerRequest
> = z.object({
  maker: z.array(z.string()),
  blockchains: z.array(models.Blockchain$outboundSchema).optional(),
  platform: models.Platform$outboundSchema.optional(),
  collection: z.array(z.string()).optional(),
  origin: z.string().optional(),
  status: z.array(models.OrderStatus$outboundSchema).optional(),
  currencies: z.array(z.string()).optional(),
  start: z.number().int().optional(),
  end: z.number().int().optional(),
  continuation: z.string().optional(),
  size: z.number().int().optional(),
  searchEngine: models.SearchEngine$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrderBidsByMakerRequest$ {
  /** @deprecated use `GetOrderBidsByMakerRequest$inboundSchema` instead. */
  export const inboundSchema = GetOrderBidsByMakerRequest$inboundSchema;
  /** @deprecated use `GetOrderBidsByMakerRequest$outboundSchema` instead. */
  export const outboundSchema = GetOrderBidsByMakerRequest$outboundSchema;
  /** @deprecated use `GetOrderBidsByMakerRequest$Outbound` instead. */
  export type Outbound = GetOrderBidsByMakerRequest$Outbound;
}

export function getOrderBidsByMakerRequestToJSON(
  getOrderBidsByMakerRequest: GetOrderBidsByMakerRequest,
): string {
  return JSON.stringify(
    GetOrderBidsByMakerRequest$outboundSchema.parse(getOrderBidsByMakerRequest),
  );
}

export function getOrderBidsByMakerRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetOrderBidsByMakerRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrderBidsByMakerRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrderBidsByMakerRequest' from JSON`,
  );
}
