/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetOrderBidsByItemRequest = {
  /**
   * The platform where the order was created
   */
  platform?: models.Platform | undefined;
  /**
   * Item Id, has format `ETHEREUM:${token}:${tokenId}`
   */
  itemId: string;
  /**
   * The maker of the bid
   */
  maker?: Array<string> | undefined;
  /**
   * Address of the consumer to receive the commission for the order
   */
  origin?: string | undefined;
  /**
   * Order status
   */
  status?: Array<models.OrderStatus> | undefined;
  /**
   * Currencies for bids
   */
  currencies?: Array<string> | undefined;
  /**
   * Lower time border of data (timestamp)
   */
  start?: number | undefined;
  /**
   * Upper time border of data (timestamp)
   */
  end?: number | undefined;
  /**
   * Continuation token from the previous response
   */
  continuation?: string | undefined;
  /**
   * The number of items to return
   */
  size?: number | undefined;
  /**
   * Search engine to use for search
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  searchEngine?: models.SearchEngine | undefined;
};

/** @internal */
export const GetOrderBidsByItemRequest$inboundSchema: z.ZodType<
  GetOrderBidsByItemRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  platform: models.Platform$inboundSchema.optional(),
  itemId: z.string(),
  maker: z.array(z.string()).optional(),
  origin: z.string().optional(),
  status: z.array(models.OrderStatus$inboundSchema).optional(),
  currencies: z.array(z.string()).optional(),
  start: z.number().int().optional(),
  end: z.number().int().optional(),
  continuation: z.string().optional(),
  size: z.number().int().optional(),
  searchEngine: models.SearchEngine$inboundSchema.optional(),
});

/** @internal */
export type GetOrderBidsByItemRequest$Outbound = {
  platform?: string | undefined;
  itemId: string;
  maker?: Array<string> | undefined;
  origin?: string | undefined;
  status?: Array<string> | undefined;
  currencies?: Array<string> | undefined;
  start?: number | undefined;
  end?: number | undefined;
  continuation?: string | undefined;
  size?: number | undefined;
  searchEngine?: string | undefined;
};

/** @internal */
export const GetOrderBidsByItemRequest$outboundSchema: z.ZodType<
  GetOrderBidsByItemRequest$Outbound,
  z.ZodTypeDef,
  GetOrderBidsByItemRequest
> = z.object({
  platform: models.Platform$outboundSchema.optional(),
  itemId: z.string(),
  maker: z.array(z.string()).optional(),
  origin: z.string().optional(),
  status: z.array(models.OrderStatus$outboundSchema).optional(),
  currencies: z.array(z.string()).optional(),
  start: z.number().int().optional(),
  end: z.number().int().optional(),
  continuation: z.string().optional(),
  size: z.number().int().optional(),
  searchEngine: models.SearchEngine$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrderBidsByItemRequest$ {
  /** @deprecated use `GetOrderBidsByItemRequest$inboundSchema` instead. */
  export const inboundSchema = GetOrderBidsByItemRequest$inboundSchema;
  /** @deprecated use `GetOrderBidsByItemRequest$outboundSchema` instead. */
  export const outboundSchema = GetOrderBidsByItemRequest$outboundSchema;
  /** @deprecated use `GetOrderBidsByItemRequest$Outbound` instead. */
  export type Outbound = GetOrderBidsByItemRequest$Outbound;
}

export function getOrderBidsByItemRequestToJSON(
  getOrderBidsByItemRequest: GetOrderBidsByItemRequest,
): string {
  return JSON.stringify(
    GetOrderBidsByItemRequest$outboundSchema.parse(getOrderBidsByItemRequest),
  );
}

export function getOrderBidsByItemRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetOrderBidsByItemRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrderBidsByItemRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrderBidsByItemRequest' from JSON`,
  );
}
