/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetOrderFloorBidsByCollectionRequest = {
  /**
   * The platform where the order was created
   */
  platform?: models.Platform | undefined;
  /**
   * Collection Id, has format `ETHEREUM:${token}`
   */
  collectionId: string;
  /**
   * Address of the consumer to receive the commission for the order
   */
  origin?: string | undefined;
  /**
   * Order status
   */
  status?: Array<models.OrderStatus> | undefined;
  /**
   * Currencies for bids
   */
  currencies?: Array<string> | undefined;
  /**
   * Lower time border of data (timestamp)
   */
  start?: number | undefined;
  /**
   * Upper time border of data (timestamp)
   */
  end?: number | undefined;
  /**
   * Continuation token from the previous response
   */
  continuation?: string | undefined;
  /**
   * The number of items to return
   */
  size?: number | undefined;
};

/** @internal */
export const GetOrderFloorBidsByCollectionRequest$inboundSchema: z.ZodType<
  GetOrderFloorBidsByCollectionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  platform: models.Platform$inboundSchema.optional(),
  collectionId: z.string(),
  origin: z.string().optional(),
  status: z.array(models.OrderStatus$inboundSchema).optional(),
  currencies: z.array(z.string()).optional(),
  start: z.number().int().optional(),
  end: z.number().int().optional(),
  continuation: z.string().optional(),
  size: z.number().int().optional(),
});

/** @internal */
export type GetOrderFloorBidsByCollectionRequest$Outbound = {
  platform?: string | undefined;
  collectionId: string;
  origin?: string | undefined;
  status?: Array<string> | undefined;
  currencies?: Array<string> | undefined;
  start?: number | undefined;
  end?: number | undefined;
  continuation?: string | undefined;
  size?: number | undefined;
};

/** @internal */
export const GetOrderFloorBidsByCollectionRequest$outboundSchema: z.ZodType<
  GetOrderFloorBidsByCollectionRequest$Outbound,
  z.ZodTypeDef,
  GetOrderFloorBidsByCollectionRequest
> = z.object({
  platform: models.Platform$outboundSchema.optional(),
  collectionId: z.string(),
  origin: z.string().optional(),
  status: z.array(models.OrderStatus$outboundSchema).optional(),
  currencies: z.array(z.string()).optional(),
  start: z.number().int().optional(),
  end: z.number().int().optional(),
  continuation: z.string().optional(),
  size: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrderFloorBidsByCollectionRequest$ {
  /** @deprecated use `GetOrderFloorBidsByCollectionRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetOrderFloorBidsByCollectionRequest$inboundSchema;
  /** @deprecated use `GetOrderFloorBidsByCollectionRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetOrderFloorBidsByCollectionRequest$outboundSchema;
  /** @deprecated use `GetOrderFloorBidsByCollectionRequest$Outbound` instead. */
  export type Outbound = GetOrderFloorBidsByCollectionRequest$Outbound;
}

export function getOrderFloorBidsByCollectionRequestToJSON(
  getOrderFloorBidsByCollectionRequest: GetOrderFloorBidsByCollectionRequest,
): string {
  return JSON.stringify(
    GetOrderFloorBidsByCollectionRequest$outboundSchema.parse(
      getOrderFloorBidsByCollectionRequest,
    ),
  );
}

export function getOrderFloorBidsByCollectionRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetOrderFloorBidsByCollectionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetOrderFloorBidsByCollectionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrderFloorBidsByCollectionRequest' from JSON`,
  );
}
