/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetOwnershipsByCollectionRequest = {
  /**
   * Address of the collection
   */
  collection: string;
  /**
   * Continuation token from the previous response
   */
  continuation?: string | undefined;
  /**
   * The number of items to return
   */
  size?: number | undefined;
};

/** @internal */
export const GetOwnershipsByCollectionRequest$inboundSchema: z.ZodType<
  GetOwnershipsByCollectionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection: z.string(),
  continuation: z.string().optional(),
  size: z.number().int().optional(),
});

/** @internal */
export type GetOwnershipsByCollectionRequest$Outbound = {
  collection: string;
  continuation?: string | undefined;
  size?: number | undefined;
};

/** @internal */
export const GetOwnershipsByCollectionRequest$outboundSchema: z.ZodType<
  GetOwnershipsByCollectionRequest$Outbound,
  z.ZodTypeDef,
  GetOwnershipsByCollectionRequest
> = z.object({
  collection: z.string(),
  continuation: z.string().optional(),
  size: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOwnershipsByCollectionRequest$ {
  /** @deprecated use `GetOwnershipsByCollectionRequest$inboundSchema` instead. */
  export const inboundSchema = GetOwnershipsByCollectionRequest$inboundSchema;
  /** @deprecated use `GetOwnershipsByCollectionRequest$outboundSchema` instead. */
  export const outboundSchema = GetOwnershipsByCollectionRequest$outboundSchema;
  /** @deprecated use `GetOwnershipsByCollectionRequest$Outbound` instead. */
  export type Outbound = GetOwnershipsByCollectionRequest$Outbound;
}

export function getOwnershipsByCollectionRequestToJSON(
  getOwnershipsByCollectionRequest: GetOwnershipsByCollectionRequest,
): string {
  return JSON.stringify(
    GetOwnershipsByCollectionRequest$outboundSchema.parse(
      getOwnershipsByCollectionRequest,
    ),
  );
}

export function getOwnershipsByCollectionRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetOwnershipsByCollectionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOwnershipsByCollectionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOwnershipsByCollectionRequest' from JSON`,
  );
}
