/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetSellersRequest = {
  /**
   * Identifier of collection
   */
  collection: string;
  /**
   * Filters of statistics
   */
  filters?: string | undefined;
};

/** @internal */
export const GetSellersRequest$inboundSchema: z.ZodType<
  GetSellersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection: z.string(),
  filters: z.string().optional(),
});

/** @internal */
export type GetSellersRequest$Outbound = {
  collection: string;
  filters?: string | undefined;
};

/** @internal */
export const GetSellersRequest$outboundSchema: z.ZodType<
  GetSellersRequest$Outbound,
  z.ZodTypeDef,
  GetSellersRequest
> = z.object({
  collection: z.string(),
  filters: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSellersRequest$ {
  /** @deprecated use `GetSellersRequest$inboundSchema` instead. */
  export const inboundSchema = GetSellersRequest$inboundSchema;
  /** @deprecated use `GetSellersRequest$outboundSchema` instead. */
  export const outboundSchema = GetSellersRequest$outboundSchema;
  /** @deprecated use `GetSellersRequest$Outbound` instead. */
  export type Outbound = GetSellersRequest$Outbound;
}

export function getSellersRequestToJSON(
  getSellersRequest: GetSellersRequest,
): string {
  return JSON.stringify(
    GetSellersRequest$outboundSchema.parse(getSellersRequest),
  );
}

export function getSellersRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetSellersRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSellersRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSellersRequest' from JSON`,
  );
}
