/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetSalesChartRequest = {
  /**
   * Collection ID
   */
  id: string;
  /**
   * Time period from
   */
  from?: Date | undefined;
  /**
   * Time period to
   */
  to?: Date | undefined;
  /**
   * Number of data points to return
   */
  size?: number | undefined;
  /**
   * Cursor from previous response
   */
  cursor?: string | undefined;
};

/** @internal */
export const GetSalesChartRequest$inboundSchema: z.ZodType<
  GetSalesChartRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  from: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  to: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  size: z.number().int().optional(),
  cursor: z.string().optional(),
});

/** @internal */
export type GetSalesChartRequest$Outbound = {
  id: string;
  from?: string | undefined;
  to?: string | undefined;
  size?: number | undefined;
  cursor?: string | undefined;
};

/** @internal */
export const GetSalesChartRequest$outboundSchema: z.ZodType<
  GetSalesChartRequest$Outbound,
  z.ZodTypeDef,
  GetSalesChartRequest
> = z.object({
  id: z.string(),
  from: z.date().transform(v => v.toISOString()).optional(),
  to: z.date().transform(v => v.toISOString()).optional(),
  size: z.number().int().optional(),
  cursor: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSalesChartRequest$ {
  /** @deprecated use `GetSalesChartRequest$inboundSchema` instead. */
  export const inboundSchema = GetSalesChartRequest$inboundSchema;
  /** @deprecated use `GetSalesChartRequest$outboundSchema` instead. */
  export const outboundSchema = GetSalesChartRequest$outboundSchema;
  /** @deprecated use `GetSalesChartRequest$Outbound` instead. */
  export type Outbound = GetSalesChartRequest$Outbound;
}

export function getSalesChartRequestToJSON(
  getSalesChartRequest: GetSalesChartRequest,
): string {
  return JSON.stringify(
    GetSalesChartRequest$outboundSchema.parse(getSalesChartRequest),
  );
}

export function getSalesChartRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetSalesChartRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSalesChartRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSalesChartRequest' from JSON`,
  );
}
