/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetTransactionsRequest = {
  /**
   * Identifier of collection
   */
  collection: string;
  /**
   * Filters of statistics
   */
  filters?: string | undefined;
};

/** @internal */
export const GetTransactionsRequest$inboundSchema: z.ZodType<
  GetTransactionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection: z.string(),
  filters: z.string().optional(),
});

/** @internal */
export type GetTransactionsRequest$Outbound = {
  collection: string;
  filters?: string | undefined;
};

/** @internal */
export const GetTransactionsRequest$outboundSchema: z.ZodType<
  GetTransactionsRequest$Outbound,
  z.ZodTypeDef,
  GetTransactionsRequest
> = z.object({
  collection: z.string(),
  filters: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsRequest$ {
  /** @deprecated use `GetTransactionsRequest$inboundSchema` instead. */
  export const inboundSchema = GetTransactionsRequest$inboundSchema;
  /** @deprecated use `GetTransactionsRequest$outboundSchema` instead. */
  export const outboundSchema = GetTransactionsRequest$outboundSchema;
  /** @deprecated use `GetTransactionsRequest$Outbound` instead. */
  export type Outbound = GetTransactionsRequest$Outbound;
}

export function getTransactionsRequestToJSON(
  getTransactionsRequest: GetTransactionsRequest,
): string {
  return JSON.stringify(
    GetTransactionsRequest$outboundSchema.parse(getTransactionsRequest),
  );
}

export function getTransactionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetTransactionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTransactionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTransactionsRequest' from JSON`,
  );
}
