/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetVolumeChartRequest = {
  /**
   * Collection ID
   */
  id: string;
  /**
   * Time period for aggregation
   */
  period: models.OlapPeriod;
  /**
   * Number of data points to return
   */
  size: number;
  /**
   * Optionally, the date-time of the last point of the graph. Defaults to current time.
   */
  endTime?: Date | undefined;
};

/** @internal */
export const GetVolumeChartRequest$inboundSchema: z.ZodType<
  GetVolumeChartRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  period: models.OlapPeriod$inboundSchema,
  size: z.number().int(),
  endTime: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
});

/** @internal */
export type GetVolumeChartRequest$Outbound = {
  id: string;
  period: string;
  size: number;
  endTime?: string | undefined;
};

/** @internal */
export const GetVolumeChartRequest$outboundSchema: z.ZodType<
  GetVolumeChartRequest$Outbound,
  z.ZodTypeDef,
  GetVolumeChartRequest
> = z.object({
  id: z.string(),
  period: models.OlapPeriod$outboundSchema,
  size: z.number().int(),
  endTime: z.date().transform(v => v.toISOString()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetVolumeChartRequest$ {
  /** @deprecated use `GetVolumeChartRequest$inboundSchema` instead. */
  export const inboundSchema = GetVolumeChartRequest$inboundSchema;
  /** @deprecated use `GetVolumeChartRequest$outboundSchema` instead. */
  export const outboundSchema = GetVolumeChartRequest$outboundSchema;
  /** @deprecated use `GetVolumeChartRequest$Outbound` instead. */
  export type Outbound = GetVolumeChartRequest$Outbound;
}

export function getVolumeChartRequestToJSON(
  getVolumeChartRequest: GetVolumeChartRequest,
): string {
  return JSON.stringify(
    GetVolumeChartRequest$outboundSchema.parse(getVolumeChartRequest),
  );
}

export function getVolumeChartRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetVolumeChartRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetVolumeChartRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetVolumeChartRequest' from JSON`,
  );
}
