/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetValidatedOrderByIdRequest = {
  /**
   * Order Id, has format 'ETHEREUM:${id}'
   */
  id: string;
};

/** @internal */
export const GetValidatedOrderByIdRequest$inboundSchema: z.ZodType<
  GetValidatedOrderByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetValidatedOrderByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetValidatedOrderByIdRequest$outboundSchema: z.ZodType<
  GetValidatedOrderByIdRequest$Outbound,
  z.ZodTypeDef,
  GetValidatedOrderByIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetValidatedOrderByIdRequest$ {
  /** @deprecated use `GetValidatedOrderByIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetValidatedOrderByIdRequest$inboundSchema;
  /** @deprecated use `GetValidatedOrderByIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetValidatedOrderByIdRequest$outboundSchema;
  /** @deprecated use `GetValidatedOrderByIdRequest$Outbound` instead. */
  export type Outbound = GetValidatedOrderByIdRequest$Outbound;
}

export function getValidatedOrderByIdRequestToJSON(
  getValidatedOrderByIdRequest: GetValidatedOrderByIdRequest,
): string {
  return JSON.stringify(
    GetValidatedOrderByIdRequest$outboundSchema.parse(
      getValidatedOrderByIdRequest,
    ),
  );
}

export function getValidatedOrderByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetValidatedOrderByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetValidatedOrderByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetValidatedOrderByIdRequest' from JSON`,
  );
}
