/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PrepareOrderCancelTransactionRequest = {
  /**
   * Order Id, has format 'ETHEREUM:${id}'
   */
  id: string;
};

/** @internal */
export const PrepareOrderCancelTransactionRequest$inboundSchema: z.ZodType<
  PrepareOrderCancelTransactionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type PrepareOrderCancelTransactionRequest$Outbound = {
  id: string;
};

/** @internal */
export const PrepareOrderCancelTransactionRequest$outboundSchema: z.ZodType<
  PrepareOrderCancelTransactionRequest$Outbound,
  z.ZodTypeDef,
  PrepareOrderCancelTransactionRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PrepareOrderCancelTransactionRequest$ {
  /** @deprecated use `PrepareOrderCancelTransactionRequest$inboundSchema` instead. */
  export const inboundSchema =
    PrepareOrderCancelTransactionRequest$inboundSchema;
  /** @deprecated use `PrepareOrderCancelTransactionRequest$outboundSchema` instead. */
  export const outboundSchema =
    PrepareOrderCancelTransactionRequest$outboundSchema;
  /** @deprecated use `PrepareOrderCancelTransactionRequest$Outbound` instead. */
  export type Outbound = PrepareOrderCancelTransactionRequest$Outbound;
}

export function prepareOrderCancelTransactionRequestToJSON(
  prepareOrderCancelTransactionRequest: PrepareOrderCancelTransactionRequest,
): string {
  return JSON.stringify(
    PrepareOrderCancelTransactionRequest$outboundSchema.parse(
      prepareOrderCancelTransactionRequest,
    ),
  );
}

export function prepareOrderCancelTransactionRequestFromJSON(
  jsonString: string,
): SafeParseResult<PrepareOrderCancelTransactionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PrepareOrderCancelTransactionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PrepareOrderCancelTransactionRequest' from JSON`,
  );
}
