/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type PrepareOrderTransactionRequest = {
  /**
   * Order Id, has format 'ETHEREUM:${id}'
   */
  id: string;
  prepareOrderTxForm: models.PrepareOrderTxForm;
};

/** @internal */
export const PrepareOrderTransactionRequest$inboundSchema: z.ZodType<
  PrepareOrderTransactionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  PrepareOrderTxForm: models.PrepareOrderTxForm$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "PrepareOrderTxForm": "prepareOrderTxForm",
  });
});

/** @internal */
export type PrepareOrderTransactionRequest$Outbound = {
  id: string;
  PrepareOrderTxForm: models.PrepareOrderTxForm$Outbound;
};

/** @internal */
export const PrepareOrderTransactionRequest$outboundSchema: z.ZodType<
  PrepareOrderTransactionRequest$Outbound,
  z.ZodTypeDef,
  PrepareOrderTransactionRequest
> = z.object({
  id: z.string(),
  prepareOrderTxForm: models.PrepareOrderTxForm$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    prepareOrderTxForm: "PrepareOrderTxForm",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PrepareOrderTransactionRequest$ {
  /** @deprecated use `PrepareOrderTransactionRequest$inboundSchema` instead. */
  export const inboundSchema = PrepareOrderTransactionRequest$inboundSchema;
  /** @deprecated use `PrepareOrderTransactionRequest$outboundSchema` instead. */
  export const outboundSchema = PrepareOrderTransactionRequest$outboundSchema;
  /** @deprecated use `PrepareOrderTransactionRequest$Outbound` instead. */
  export type Outbound = PrepareOrderTransactionRequest$Outbound;
}

export function prepareOrderTransactionRequestToJSON(
  prepareOrderTransactionRequest: PrepareOrderTransactionRequest,
): string {
  return JSON.stringify(
    PrepareOrderTransactionRequest$outboundSchema.parse(
      prepareOrderTransactionRequest,
    ),
  );
}

export function prepareOrderTransactionRequestFromJSON(
  jsonString: string,
): SafeParseResult<PrepareOrderTransactionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PrepareOrderTransactionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PrepareOrderTransactionRequest' from JSON`,
  );
}
