/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type QueryTraitsRequest = {
  /**
   * Trait keys for strict filtering (if not specified - all traits will be returned)
   */
  keys?: Array<string> | undefined;
  /**
   * Collections identifiers to which traits belong
   */
  collectionIds: Array<string>;
  /**
   * Return traits only for items owned by user
   */
  owners?: Array<string> | undefined;
};

/** @internal */
export const QueryTraitsRequest$inboundSchema: z.ZodType<
  QueryTraitsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  keys: z.array(z.string()).optional(),
  collectionIds: z.array(z.string()),
  owners: z.array(z.string()).optional(),
});

/** @internal */
export type QueryTraitsRequest$Outbound = {
  keys?: Array<string> | undefined;
  collectionIds: Array<string>;
  owners?: Array<string> | undefined;
};

/** @internal */
export const QueryTraitsRequest$outboundSchema: z.ZodType<
  QueryTraitsRequest$Outbound,
  z.ZodTypeDef,
  QueryTraitsRequest
> = z.object({
  keys: z.array(z.string()).optional(),
  collectionIds: z.array(z.string()),
  owners: z.array(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueryTraitsRequest$ {
  /** @deprecated use `QueryTraitsRequest$inboundSchema` instead. */
  export const inboundSchema = QueryTraitsRequest$inboundSchema;
  /** @deprecated use `QueryTraitsRequest$outboundSchema` instead. */
  export const outboundSchema = QueryTraitsRequest$outboundSchema;
  /** @deprecated use `QueryTraitsRequest$Outbound` instead. */
  export type Outbound = QueryTraitsRequest$Outbound;
}

export function queryTraitsRequestToJSON(
  queryTraitsRequest: QueryTraitsRequest,
): string {
  return JSON.stringify(
    QueryTraitsRequest$outboundSchema.parse(queryTraitsRequest),
  );
}

export function queryTraitsRequestFromJSON(
  jsonString: string,
): SafeParseResult<QueryTraitsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryTraitsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryTraitsRequest' from JSON`,
  );
}
