/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SearchTraitsRequest = {
  /**
   * filter
   */
  filter: string;
  /**
   * Collections identifiers to which traits belong
   */
  collectionIds: Array<string>;
  /**
   * Return traits only for items owned by user
   */
  owners?: Array<string> | undefined;
};

/** @internal */
export const SearchTraitsRequest$inboundSchema: z.ZodType<
  SearchTraitsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  filter: z.string(),
  collectionIds: z.array(z.string()),
  owners: z.array(z.string()).optional(),
});

/** @internal */
export type SearchTraitsRequest$Outbound = {
  filter: string;
  collectionIds: Array<string>;
  owners?: Array<string> | undefined;
};

/** @internal */
export const SearchTraitsRequest$outboundSchema: z.ZodType<
  SearchTraitsRequest$Outbound,
  z.ZodTypeDef,
  SearchTraitsRequest
> = z.object({
  filter: z.string(),
  collectionIds: z.array(z.string()),
  owners: z.array(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SearchTraitsRequest$ {
  /** @deprecated use `SearchTraitsRequest$inboundSchema` instead. */
  export const inboundSchema = SearchTraitsRequest$inboundSchema;
  /** @deprecated use `SearchTraitsRequest$outboundSchema` instead. */
  export const outboundSchema = SearchTraitsRequest$outboundSchema;
  /** @deprecated use `SearchTraitsRequest$Outbound` instead. */
  export type Outbound = SearchTraitsRequest$Outbound;
}

export function searchTraitsRequestToJSON(
  searchTraitsRequest: SearchTraitsRequest,
): string {
  return JSON.stringify(
    SearchTraitsRequest$outboundSchema.parse(searchTraitsRequest),
  );
}

export function searchTraitsRequestFromJSON(
  jsonString: string,
): SafeParseResult<SearchTraitsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchTraitsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchTraitsRequest' from JSON`,
  );
}
