/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ActivityUserFilter = {
  any?: Array<string> | undefined;
  from?: Array<string> | undefined;
  to?: Array<string> | undefined;
};

/** @internal */
export const ActivityUserFilter$inboundSchema: z.ZodType<
  ActivityUserFilter,
  z.ZodTypeDef,
  unknown
> = z.object({
  any: z.array(z.string()).optional(),
  from: z.array(z.string()).optional(),
  to: z.array(z.string()).optional(),
});

/** @internal */
export type ActivityUserFilter$Outbound = {
  any?: Array<string> | undefined;
  from?: Array<string> | undefined;
  to?: Array<string> | undefined;
};

/** @internal */
export const ActivityUserFilter$outboundSchema: z.ZodType<
  ActivityUserFilter$Outbound,
  z.ZodTypeDef,
  ActivityUserFilter
> = z.object({
  any: z.array(z.string()).optional(),
  from: z.array(z.string()).optional(),
  to: z.array(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ActivityUserFilter$ {
  /** @deprecated use `ActivityUserFilter$inboundSchema` instead. */
  export const inboundSchema = ActivityUserFilter$inboundSchema;
  /** @deprecated use `ActivityUserFilter$outboundSchema` instead. */
  export const outboundSchema = ActivityUserFilter$outboundSchema;
  /** @deprecated use `ActivityUserFilter$Outbound` instead. */
  export type Outbound = ActivityUserFilter$Outbound;
}

export function activityUserFilterToJSON(
  activityUserFilter: ActivityUserFilter,
): string {
  return JSON.stringify(
    ActivityUserFilter$outboundSchema.parse(activityUserFilter),
  );
}

export function activityUserFilterFromJSON(
  jsonString: string,
): SafeParseResult<ActivityUserFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivityUserFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivityUserFilter' from JSON`,
  );
}
