/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ActivitySearchSort = {
  Latest: "LATEST",
  Earliest: "EARLIEST",
} as const;
export type ActivitySearchSort = ClosedEnum<typeof ActivitySearchSort>;

/** @internal */
export const ActivitySearchSort$inboundSchema: z.ZodNativeEnum<
  typeof ActivitySearchSort
> = z.nativeEnum(ActivitySearchSort);

/** @internal */
export const ActivitySearchSort$outboundSchema: z.ZodNativeEnum<
  typeof ActivitySearchSort
> = ActivitySearchSort$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ActivitySearchSort$ {
  /** @deprecated use `ActivitySearchSort$inboundSchema` instead. */
  export const inboundSchema = ActivitySearchSort$inboundSchema;
  /** @deprecated use `ActivitySearchSort$outboundSchema` instead. */
  export const outboundSchema = ActivitySearchSort$outboundSchema;
}
