/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ActivitySearchFilter,
  ActivitySearchFilter$inboundSchema,
  ActivitySearchFilter$Outbound,
  ActivitySearchFilter$outboundSchema,
} from "./activitysearchfilter.js";
import {
  ActivitySearchSort,
  ActivitySearchSort$inboundSchema,
  ActivitySearchSort$outboundSchema,
} from "./activitysearchsort.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Complex search request for Activities
 */
export type ActivitySearchRequest = {
  /**
   * Number of entities returned
   */
  size?: number | undefined;
  /**
   * Cursor token to paginate Activity search result
   */
  cursor?: string | undefined;
  filter: ActivitySearchFilter;
  sort?: ActivitySearchSort | undefined;
};

/** @internal */
export const ActivitySearchRequest$inboundSchema: z.ZodType<
  ActivitySearchRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  size: z.number().int().default(50),
  cursor: z.string().optional(),
  filter: ActivitySearchFilter$inboundSchema,
  sort: ActivitySearchSort$inboundSchema.optional(),
});

/** @internal */
export type ActivitySearchRequest$Outbound = {
  size: number;
  cursor?: string | undefined;
  filter: ActivitySearchFilter$Outbound;
  sort?: string | undefined;
};

/** @internal */
export const ActivitySearchRequest$outboundSchema: z.ZodType<
  ActivitySearchRequest$Outbound,
  z.ZodTypeDef,
  ActivitySearchRequest
> = z.object({
  size: z.number().int().default(50),
  cursor: z.string().optional(),
  filter: ActivitySearchFilter$outboundSchema,
  sort: ActivitySearchSort$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ActivitySearchRequest$ {
  /** @deprecated use `ActivitySearchRequest$inboundSchema` instead. */
  export const inboundSchema = ActivitySearchRequest$inboundSchema;
  /** @deprecated use `ActivitySearchRequest$outboundSchema` instead. */
  export const outboundSchema = ActivitySearchRequest$outboundSchema;
  /** @deprecated use `ActivitySearchRequest$Outbound` instead. */
  export type Outbound = ActivitySearchRequest$Outbound;
}

export function activitySearchRequestToJSON(
  activitySearchRequest: ActivitySearchRequest,
): string {
  return JSON.stringify(
    ActivitySearchRequest$outboundSchema.parse(activitySearchRequest),
  );
}

export function activitySearchRequestFromJSON(
  jsonString: string,
): SafeParseResult<ActivitySearchRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivitySearchRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivitySearchRequest' from JSON`,
  );
}
