/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ActivityType = {
  Transfer: "TRANSFER",
  Mint: "MINT",
  Burn: "BURN",
  Bid: "BID",
  List: "LIST",
  Sell: "SELL",
  CancelList: "CANCEL_LIST",
  CancelBid: "CANCEL_BID",
  BridgeTo: "BRIDGE_TO",
  BridgeFrom: "BRIDGE_FROM",
} as const;
export type ActivityType = ClosedEnum<typeof ActivityType>;

/** @internal */
export const ActivityType$inboundSchema: z.ZodNativeEnum<typeof ActivityType> =
  z.nativeEnum(ActivityType);

/** @internal */
export const ActivityType$outboundSchema: z.ZodNativeEnum<typeof ActivityType> =
  ActivityType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ActivityType$ {
  /** @deprecated use `ActivityType$inboundSchema` instead. */
  export const inboundSchema = ActivityType$inboundSchema;
  /** @deprecated use `ActivityType$outboundSchema` instead. */
  export const outboundSchema = ActivityType$outboundSchema;
}
