/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ActivityBlockchainInfo,
  ActivityBlockchainInfo$inboundSchema,
  ActivityBlockchainInfo$Outbound,
  ActivityBlockchainInfo$outboundSchema,
} from "./activityblockchaininfo.js";
import {
  Asset,
  Asset$inboundSchema,
  Asset$Outbound,
  Asset$outboundSchema,
} from "./asset.js";
import {
  AssetType,
  AssetType$inboundSchema,
  AssetType$Outbound,
  AssetType$outboundSchema,
} from "./assettype.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OrderActivityMatchSide,
  OrderActivityMatchSide$inboundSchema,
  OrderActivityMatchSide$Outbound,
  OrderActivityMatchSide$outboundSchema,
} from "./orderactivitymatchside.js";
import {
  OrderActivitySource,
  OrderActivitySource$inboundSchema,
  OrderActivitySource$outboundSchema,
} from "./orderactivitysource.js";

export const AtTypeL2Withdrawal = {
  L2Withdrawal: "L2_WITHDRAWAL",
} as const;
export type AtTypeL2Withdrawal = ClosedEnum<typeof AtTypeL2Withdrawal>;


export type L2WithdrawalActivity = {
  atType: AtTypeL2Withdrawal;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  user: string;
  status: string;
  /**
   * Item Id, has format `ETHEREUM:${token}:${tokenId}`
   */
  itemId: string;
  /**
   * Collection id
   */
  collection?: string | undefined;
  value?: string | undefined;
  id: string;
  date: Date;
  lastUpdatedAt?: Date | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

export const AtTypeL2Deposit = {
  L2Deposit: "L2_DEPOSIT",
} as const;
export type AtTypeL2Deposit = ClosedEnum<typeof AtTypeL2Deposit>;

export type L2DepositActivity = {
  atType: AtTypeL2Deposit;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  user: string;
  status: string;
  /**
   * Item Id, has format `ETHEREUM:${token}:${tokenId}`
   */
  itemId: string;
  /**
   * Collection id
   */
  collection?: string | undefined;
  value?: string | undefined;
  id: string;
  date: Date;
  lastUpdatedAt?: Date | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

export const AtTypeCancelList = {
  CancelList: "CANCEL_LIST",
} as const;
export type AtTypeCancelList = ClosedEnum<typeof AtTypeCancelList>;

export type OrderCancelListActivity = {
  atType: AtTypeCancelList;
  orderId?: string | undefined;
  hash: string;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  maker: string;
  make: AssetType;
  take: AssetType;
  source?: OrderActivitySource | undefined;
  transactionHash: string;
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  blockchainInfo?: ActivityBlockchainInfo | undefined;
  id: string;
  date: Date;
  lastUpdatedAt?: Date | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

export const AtTypeCancelBid = {
  CancelBid: "CANCEL_BID",
} as const;
export type AtTypeCancelBid = ClosedEnum<typeof AtTypeCancelBid>;

export type OrderCancelBidActivity = {
  atType: AtTypeCancelBid;
  orderId?: string | undefined;
  hash: string;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  maker: string;
  make: AssetType;
  take: AssetType;
  source?: OrderActivitySource | undefined;
  transactionHash: string;
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  blockchainInfo?: ActivityBlockchainInfo | undefined;
  id: string;
  date: Date;
  lastUpdatedAt?: Date | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

export const AtTypeList = {
  List: "LIST",
} as const;
export type AtTypeList = ClosedEnum<typeof AtTypeList>;

export type OrderListActivity = {
  atType: AtTypeList;
  orderId?: string | undefined;
  hash: string;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  maker: string;
  make: Asset;
  take: Asset;
  price: string;
  priceUsd?: string | undefined;
  source?: OrderActivitySource | undefined;
  id: string;
  date: Date;
  lastUpdatedAt?: Date | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

export const AtTypeBid = {
  Bid: "BID",
} as const;
export type AtTypeBid = ClosedEnum<typeof AtTypeBid>;

export type OrderBidActivity = {
  atType: AtTypeBid;
  orderId?: string | undefined;
  hash: string;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  maker: string;
  make: Asset;
  take: Asset;
  price: string;
  priceUsd?: string | undefined;
  source?: OrderActivitySource | undefined;
  marketplaceMarker?: string | undefined;
  id: string;
  date: Date;
  lastUpdatedAt?: Date | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

export const ActivityOrderMatchActivityType = {
  Sell: "SELL",
  AcceptBid: "ACCEPT_BID",
} as const;
export type ActivityOrderMatchActivityType = ClosedEnum<
  typeof ActivityOrderMatchActivityType
>;

export type OrderMatchSell = {
  atType?: OrderMatchActivityAtType | undefined;
  nft: Asset;
  payment: Asset;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  buyer: string;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  seller: string;
  buyerOrderHash?: string | undefined;
  sellerOrderHash?: string | undefined;
  price: string;
  priceUsd?: string | undefined;
  amountUsd?: string | undefined;
  type: ActivityOrderMatchActivityType;
  sellMarketplaceMarker?: string | undefined;
  buyMarketplaceMarker?: string | undefined;
  orderId?: string | undefined;
  source: OrderActivitySource;
  transactionHash: string;
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  blockchainInfo?: ActivityBlockchainInfo | undefined;
  id: string;
  date: Date;
  lastUpdatedAt?: Date | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

export const OrderMatchActivityAtType = {
  Match: "MATCH",
} as const;
export type OrderMatchActivityAtType = ClosedEnum<
  typeof OrderMatchActivityAtType
>;

export type OrderMatchSwap = {
  atType?: OrderMatchActivityAtType | undefined;
  left: OrderActivityMatchSide;
  right: OrderActivityMatchSide;
  orderId?: string | undefined;
  source: OrderActivitySource;
  transactionHash: string;
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  blockchainInfo?: ActivityBlockchainInfo | undefined;
  id: string;
  date: Date;
  lastUpdatedAt?: Date | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

export type OrderMatchActivity = OrderMatchSwap | OrderMatchSell;

export const AtTypeReceiveFromChain = {
  ReceiveFromChain: "RECEIVE_FROM_CHAIN",
} as const;
export type AtTypeReceiveFromChain = ClosedEnum<typeof AtTypeReceiveFromChain>;

export type ReceiveFromChainActivity = {
  atType: AtTypeReceiveFromChain;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  owner: string;
  from: string;
  chainId: string;
  /**
   * Blockchain contract address in Union format `ETHEREUM:${token}`
   */
  contract?: string | undefined;
  /**
   * Collection id
   */
  collection?: string | undefined;
  /**
   * Item Id, has format `ETHEREUM:${token}:${tokenId}`
   */
  itemId: string;
  value: string;
  transactionHash: string;
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  blockchainInfo?: ActivityBlockchainInfo | undefined;
  id: string;
  date: Date;
  lastUpdatedAt?: Date | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

export const AtTypeSendToChain = {
  SendToChain: "SEND_TO_CHAIN",
} as const;
export type AtTypeSendToChain = ClosedEnum<typeof AtTypeSendToChain>;

export type SendToChainActivity = {
  atType: AtTypeSendToChain;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  owner: string;
  to: string;
  chainId: string;
  /**
   * Blockchain contract address in Union format `ETHEREUM:${token}`
   */
  contract?: string | undefined;
  /**
   * Collection id
   */
  collection?: string | undefined;
  /**
   * Item Id, has format `ETHEREUM:${token}:${tokenId}`
   */
  itemId: string;
  value: string;
  transactionHash: string;
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  blockchainInfo?: ActivityBlockchainInfo | undefined;
  id: string;
  date: Date;
  lastUpdatedAt?: Date | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

export const ActivityAtTypeTransfer = {
  Transfer: "TRANSFER",
} as const;
export type ActivityAtTypeTransfer = ClosedEnum<typeof ActivityAtTypeTransfer>;

export type TransferActivity = {
  atType: ActivityAtTypeTransfer;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  from: string;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  owner: string;
  /**
   * Blockchain contract address in Union format `ETHEREUM:${token}`
   */
  contract?: string | undefined;
  /**
   * Collection id
   */
  collection?: string | undefined;
  tokenId?: string | undefined;
  /**
   * Item Id, has format `ETHEREUM:${token}:${tokenId}`
   */
  itemId?: string | undefined;
  value: string;
  purchase?: boolean | undefined;
  transactionHash: string;
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  blockchainInfo?: ActivityBlockchainInfo | undefined;
  id: string;
  date: Date;
  lastUpdatedAt?: Date | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

export const AtTypeBurn = {
  Burn: "BURN",
} as const;
export type AtTypeBurn = ClosedEnum<typeof AtTypeBurn>;

export type BurnActivity = {
  atType: AtTypeBurn;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  owner: string;
  /**
   * Blockchain contract address in Union format `ETHEREUM:${token}`
   */
  contract?: string | undefined;
  /**
   * Collection id
   */
  collection?: string | undefined;
  tokenId?: string | undefined;
  /**
   * Item Id, has format `ETHEREUM:${token}:${tokenId}`
   */
  itemId?: string | undefined;
  value: string;
  transactionHash: string;
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  blockchainInfo?: ActivityBlockchainInfo | undefined;
  id: string;
  date: Date;
  lastUpdatedAt?: Date | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

export const AtTypeMint = {
  Mint: "MINT",
} as const;
export type AtTypeMint = ClosedEnum<typeof AtTypeMint>;

export type MintActivity = {
  atType: AtTypeMint;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  owner: string;
  /**
   * Blockchain contract address in Union format `ETHEREUM:${token}`
   */
  contract?: string | undefined;
  /**
   * Collection id
   */
  collection?: string | undefined;
  tokenId?: string | undefined;
  /**
   * Item Id, has format `ETHEREUM:${token}:${tokenId}`
   */
  itemId?: string | undefined;
  value: string;
  mintPrice?: string | undefined;
  mintPayment?: Asset | undefined;
  mintPriceUsd?: string | undefined;
  transactionHash: string;
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  blockchainInfo?: ActivityBlockchainInfo | undefined;
  id: string;
  date: Date;
  lastUpdatedAt?: Date | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

export type Activity =
  | L2DepositActivity
  | L2WithdrawalActivity
  | BurnActivity
  | OrderListActivity
  | OrderCancelBidActivity
  | OrderCancelListActivity
  | SendToChainActivity
  | ReceiveFromChainActivity
  | OrderBidActivity
  | TransferActivity
  | MintActivity
  | OrderMatchSwap
  | OrderMatchSell;

/** @internal */
export const AtTypeL2Withdrawal$inboundSchema: z.ZodNativeEnum<
  typeof AtTypeL2Withdrawal
> = z.nativeEnum(AtTypeL2Withdrawal);

/** @internal */
export const AtTypeL2Withdrawal$outboundSchema: z.ZodNativeEnum<
  typeof AtTypeL2Withdrawal
> = AtTypeL2Withdrawal$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AtTypeL2Withdrawal$ {
  /** @deprecated use `AtTypeL2Withdrawal$inboundSchema` instead. */
  export const inboundSchema = AtTypeL2Withdrawal$inboundSchema;
  /** @deprecated use `AtTypeL2Withdrawal$outboundSchema` instead. */
  export const outboundSchema = AtTypeL2Withdrawal$outboundSchema;
}

/** @internal */
export const L2WithdrawalActivity$inboundSchema: z.ZodType<
  L2WithdrawalActivity,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": AtTypeL2Withdrawal$inboundSchema,
  user: z.string(),
  status: z.string(),
  itemId: z.string(),
  collection: z.string().optional(),
  value: z.string().optional(),
  id: z.string(),
  date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  lastUpdatedAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type L2WithdrawalActivity$Outbound = {
  "@type": string;
  user: string;
  status: string;
  itemId: string;
  collection?: string | undefined;
  value?: string | undefined;
  id: string;
  date: string;
  lastUpdatedAt?: string | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

/** @internal */
export const L2WithdrawalActivity$outboundSchema: z.ZodType<
  L2WithdrawalActivity$Outbound,
  z.ZodTypeDef,
  L2WithdrawalActivity
> = z.object({
  atType: AtTypeL2Withdrawal$outboundSchema,
  user: z.string(),
  status: z.string(),
  itemId: z.string(),
  collection: z.string().optional(),
  value: z.string().optional(),
  id: z.string(),
  date: z.date().transform(v => v.toISOString()),
  lastUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace L2WithdrawalActivity$ {
  /** @deprecated use `L2WithdrawalActivity$inboundSchema` instead. */
  export const inboundSchema = L2WithdrawalActivity$inboundSchema;
  /** @deprecated use `L2WithdrawalActivity$outboundSchema` instead. */
  export const outboundSchema = L2WithdrawalActivity$outboundSchema;
  /** @deprecated use `L2WithdrawalActivity$Outbound` instead. */
  export type Outbound = L2WithdrawalActivity$Outbound;
}

export function l2WithdrawalActivityToJSON(
  l2WithdrawalActivity: L2WithdrawalActivity,
): string {
  return JSON.stringify(
    L2WithdrawalActivity$outboundSchema.parse(l2WithdrawalActivity),
  );
}

export function l2WithdrawalActivityFromJSON(
  jsonString: string,
): SafeParseResult<L2WithdrawalActivity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => L2WithdrawalActivity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'L2WithdrawalActivity' from JSON`,
  );
}

/** @internal */
export const AtTypeL2Deposit$inboundSchema: z.ZodNativeEnum<
  typeof AtTypeL2Deposit
> = z.nativeEnum(AtTypeL2Deposit);

/** @internal */
export const AtTypeL2Deposit$outboundSchema: z.ZodNativeEnum<
  typeof AtTypeL2Deposit
> = AtTypeL2Deposit$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AtTypeL2Deposit$ {
  /** @deprecated use `AtTypeL2Deposit$inboundSchema` instead. */
  export const inboundSchema = AtTypeL2Deposit$inboundSchema;
  /** @deprecated use `AtTypeL2Deposit$outboundSchema` instead. */
  export const outboundSchema = AtTypeL2Deposit$outboundSchema;
}

/** @internal */
export const L2DepositActivity$inboundSchema: z.ZodType<
  L2DepositActivity,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": AtTypeL2Deposit$inboundSchema,
  user: z.string(),
  status: z.string(),
  itemId: z.string(),
  collection: z.string().optional(),
  value: z.string().optional(),
  id: z.string(),
  date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  lastUpdatedAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type L2DepositActivity$Outbound = {
  "@type": string;
  user: string;
  status: string;
  itemId: string;
  collection?: string | undefined;
  value?: string | undefined;
  id: string;
  date: string;
  lastUpdatedAt?: string | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

/** @internal */
export const L2DepositActivity$outboundSchema: z.ZodType<
  L2DepositActivity$Outbound,
  z.ZodTypeDef,
  L2DepositActivity
> = z.object({
  atType: AtTypeL2Deposit$outboundSchema,
  user: z.string(),
  status: z.string(),
  itemId: z.string(),
  collection: z.string().optional(),
  value: z.string().optional(),
  id: z.string(),
  date: z.date().transform(v => v.toISOString()),
  lastUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace L2DepositActivity$ {
  /** @deprecated use `L2DepositActivity$inboundSchema` instead. */
  export const inboundSchema = L2DepositActivity$inboundSchema;
  /** @deprecated use `L2DepositActivity$outboundSchema` instead. */
  export const outboundSchema = L2DepositActivity$outboundSchema;
  /** @deprecated use `L2DepositActivity$Outbound` instead. */
  export type Outbound = L2DepositActivity$Outbound;
}

export function l2DepositActivityToJSON(
  l2DepositActivity: L2DepositActivity,
): string {
  return JSON.stringify(
    L2DepositActivity$outboundSchema.parse(l2DepositActivity),
  );
}

export function l2DepositActivityFromJSON(
  jsonString: string,
): SafeParseResult<L2DepositActivity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => L2DepositActivity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'L2DepositActivity' from JSON`,
  );
}

/** @internal */
export const AtTypeCancelList$inboundSchema: z.ZodNativeEnum<
  typeof AtTypeCancelList
> = z.nativeEnum(AtTypeCancelList);

/** @internal */
export const AtTypeCancelList$outboundSchema: z.ZodNativeEnum<
  typeof AtTypeCancelList
> = AtTypeCancelList$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AtTypeCancelList$ {
  /** @deprecated use `AtTypeCancelList$inboundSchema` instead. */
  export const inboundSchema = AtTypeCancelList$inboundSchema;
  /** @deprecated use `AtTypeCancelList$outboundSchema` instead. */
  export const outboundSchema = AtTypeCancelList$outboundSchema;
}

/** @internal */
export const OrderCancelListActivity$inboundSchema: z.ZodType<
  OrderCancelListActivity,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": AtTypeCancelList$inboundSchema,
  orderId: z.string().optional(),
  hash: z.string(),
  maker: z.string(),
  make: AssetType$inboundSchema,
  take: AssetType$inboundSchema,
  source: OrderActivitySource$inboundSchema.optional(),
  transactionHash: z.string(),
  blockchainInfo: ActivityBlockchainInfo$inboundSchema.optional(),
  id: z.string(),
  date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  lastUpdatedAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type OrderCancelListActivity$Outbound = {
  "@type": string;
  orderId?: string | undefined;
  hash: string;
  maker: string;
  make: AssetType$Outbound;
  take: AssetType$Outbound;
  source?: string | undefined;
  transactionHash: string;
  blockchainInfo?: ActivityBlockchainInfo$Outbound | undefined;
  id: string;
  date: string;
  lastUpdatedAt?: string | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

/** @internal */
export const OrderCancelListActivity$outboundSchema: z.ZodType<
  OrderCancelListActivity$Outbound,
  z.ZodTypeDef,
  OrderCancelListActivity
> = z.object({
  atType: AtTypeCancelList$outboundSchema,
  orderId: z.string().optional(),
  hash: z.string(),
  maker: z.string(),
  make: AssetType$outboundSchema,
  take: AssetType$outboundSchema,
  source: OrderActivitySource$outboundSchema.optional(),
  transactionHash: z.string(),
  blockchainInfo: ActivityBlockchainInfo$outboundSchema.optional(),
  id: z.string(),
  date: z.date().transform(v => v.toISOString()),
  lastUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrderCancelListActivity$ {
  /** @deprecated use `OrderCancelListActivity$inboundSchema` instead. */
  export const inboundSchema = OrderCancelListActivity$inboundSchema;
  /** @deprecated use `OrderCancelListActivity$outboundSchema` instead. */
  export const outboundSchema = OrderCancelListActivity$outboundSchema;
  /** @deprecated use `OrderCancelListActivity$Outbound` instead. */
  export type Outbound = OrderCancelListActivity$Outbound;
}

export function orderCancelListActivityToJSON(
  orderCancelListActivity: OrderCancelListActivity,
): string {
  return JSON.stringify(
    OrderCancelListActivity$outboundSchema.parse(orderCancelListActivity),
  );
}

export function orderCancelListActivityFromJSON(
  jsonString: string,
): SafeParseResult<OrderCancelListActivity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrderCancelListActivity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrderCancelListActivity' from JSON`,
  );
}

/** @internal */
export const AtTypeCancelBid$inboundSchema: z.ZodNativeEnum<
  typeof AtTypeCancelBid
> = z.nativeEnum(AtTypeCancelBid);

/** @internal */
export const AtTypeCancelBid$outboundSchema: z.ZodNativeEnum<
  typeof AtTypeCancelBid
> = AtTypeCancelBid$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AtTypeCancelBid$ {
  /** @deprecated use `AtTypeCancelBid$inboundSchema` instead. */
  export const inboundSchema = AtTypeCancelBid$inboundSchema;
  /** @deprecated use `AtTypeCancelBid$outboundSchema` instead. */
  export const outboundSchema = AtTypeCancelBid$outboundSchema;
}

/** @internal */
export const OrderCancelBidActivity$inboundSchema: z.ZodType<
  OrderCancelBidActivity,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": AtTypeCancelBid$inboundSchema,
  orderId: z.string().optional(),
  hash: z.string(),
  maker: z.string(),
  make: AssetType$inboundSchema,
  take: AssetType$inboundSchema,
  source: OrderActivitySource$inboundSchema.optional(),
  transactionHash: z.string(),
  blockchainInfo: ActivityBlockchainInfo$inboundSchema.optional(),
  id: z.string(),
  date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  lastUpdatedAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type OrderCancelBidActivity$Outbound = {
  "@type": string;
  orderId?: string | undefined;
  hash: string;
  maker: string;
  make: AssetType$Outbound;
  take: AssetType$Outbound;
  source?: string | undefined;
  transactionHash: string;
  blockchainInfo?: ActivityBlockchainInfo$Outbound | undefined;
  id: string;
  date: string;
  lastUpdatedAt?: string | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

/** @internal */
export const OrderCancelBidActivity$outboundSchema: z.ZodType<
  OrderCancelBidActivity$Outbound,
  z.ZodTypeDef,
  OrderCancelBidActivity
> = z.object({
  atType: AtTypeCancelBid$outboundSchema,
  orderId: z.string().optional(),
  hash: z.string(),
  maker: z.string(),
  make: AssetType$outboundSchema,
  take: AssetType$outboundSchema,
  source: OrderActivitySource$outboundSchema.optional(),
  transactionHash: z.string(),
  blockchainInfo: ActivityBlockchainInfo$outboundSchema.optional(),
  id: z.string(),
  date: z.date().transform(v => v.toISOString()),
  lastUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrderCancelBidActivity$ {
  /** @deprecated use `OrderCancelBidActivity$inboundSchema` instead. */
  export const inboundSchema = OrderCancelBidActivity$inboundSchema;
  /** @deprecated use `OrderCancelBidActivity$outboundSchema` instead. */
  export const outboundSchema = OrderCancelBidActivity$outboundSchema;
  /** @deprecated use `OrderCancelBidActivity$Outbound` instead. */
  export type Outbound = OrderCancelBidActivity$Outbound;
}

export function orderCancelBidActivityToJSON(
  orderCancelBidActivity: OrderCancelBidActivity,
): string {
  return JSON.stringify(
    OrderCancelBidActivity$outboundSchema.parse(orderCancelBidActivity),
  );
}

export function orderCancelBidActivityFromJSON(
  jsonString: string,
): SafeParseResult<OrderCancelBidActivity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrderCancelBidActivity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrderCancelBidActivity' from JSON`,
  );
}

/** @internal */
export const AtTypeList$inboundSchema: z.ZodNativeEnum<typeof AtTypeList> = z
  .nativeEnum(AtTypeList);

/** @internal */
export const AtTypeList$outboundSchema: z.ZodNativeEnum<typeof AtTypeList> =
  AtTypeList$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AtTypeList$ {
  /** @deprecated use `AtTypeList$inboundSchema` instead. */
  export const inboundSchema = AtTypeList$inboundSchema;
  /** @deprecated use `AtTypeList$outboundSchema` instead. */
  export const outboundSchema = AtTypeList$outboundSchema;
}

/** @internal */
export const OrderListActivity$inboundSchema: z.ZodType<
  OrderListActivity,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": AtTypeList$inboundSchema,
  orderId: z.string().optional(),
  hash: z.string(),
  maker: z.string(),
  make: Asset$inboundSchema,
  take: Asset$inboundSchema,
  price: z.string(),
  priceUsd: z.string().optional(),
  source: OrderActivitySource$inboundSchema.optional(),
  id: z.string(),
  date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  lastUpdatedAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type OrderListActivity$Outbound = {
  "@type": string;
  orderId?: string | undefined;
  hash: string;
  maker: string;
  make: Asset$Outbound;
  take: Asset$Outbound;
  price: string;
  priceUsd?: string | undefined;
  source?: string | undefined;
  id: string;
  date: string;
  lastUpdatedAt?: string | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

/** @internal */
export const OrderListActivity$outboundSchema: z.ZodType<
  OrderListActivity$Outbound,
  z.ZodTypeDef,
  OrderListActivity
> = z.object({
  atType: AtTypeList$outboundSchema,
  orderId: z.string().optional(),
  hash: z.string(),
  maker: z.string(),
  make: Asset$outboundSchema,
  take: Asset$outboundSchema,
  price: z.string(),
  priceUsd: z.string().optional(),
  source: OrderActivitySource$outboundSchema.optional(),
  id: z.string(),
  date: z.date().transform(v => v.toISOString()),
  lastUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrderListActivity$ {
  /** @deprecated use `OrderListActivity$inboundSchema` instead. */
  export const inboundSchema = OrderListActivity$inboundSchema;
  /** @deprecated use `OrderListActivity$outboundSchema` instead. */
  export const outboundSchema = OrderListActivity$outboundSchema;
  /** @deprecated use `OrderListActivity$Outbound` instead. */
  export type Outbound = OrderListActivity$Outbound;
}

export function orderListActivityToJSON(
  orderListActivity: OrderListActivity,
): string {
  return JSON.stringify(
    OrderListActivity$outboundSchema.parse(orderListActivity),
  );
}

export function orderListActivityFromJSON(
  jsonString: string,
): SafeParseResult<OrderListActivity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrderListActivity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrderListActivity' from JSON`,
  );
}

/** @internal */
export const AtTypeBid$inboundSchema: z.ZodNativeEnum<typeof AtTypeBid> = z
  .nativeEnum(AtTypeBid);

/** @internal */
export const AtTypeBid$outboundSchema: z.ZodNativeEnum<typeof AtTypeBid> =
  AtTypeBid$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AtTypeBid$ {
  /** @deprecated use `AtTypeBid$inboundSchema` instead. */
  export const inboundSchema = AtTypeBid$inboundSchema;
  /** @deprecated use `AtTypeBid$outboundSchema` instead. */
  export const outboundSchema = AtTypeBid$outboundSchema;
}

/** @internal */
export const OrderBidActivity$inboundSchema: z.ZodType<
  OrderBidActivity,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": AtTypeBid$inboundSchema,
  orderId: z.string().optional(),
  hash: z.string(),
  maker: z.string(),
  make: Asset$inboundSchema,
  take: Asset$inboundSchema,
  price: z.string(),
  priceUsd: z.string().optional(),
  source: OrderActivitySource$inboundSchema.optional(),
  marketplaceMarker: z.string().optional(),
  id: z.string(),
  date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  lastUpdatedAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type OrderBidActivity$Outbound = {
  "@type": string;
  orderId?: string | undefined;
  hash: string;
  maker: string;
  make: Asset$Outbound;
  take: Asset$Outbound;
  price: string;
  priceUsd?: string | undefined;
  source?: string | undefined;
  marketplaceMarker?: string | undefined;
  id: string;
  date: string;
  lastUpdatedAt?: string | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

/** @internal */
export const OrderBidActivity$outboundSchema: z.ZodType<
  OrderBidActivity$Outbound,
  z.ZodTypeDef,
  OrderBidActivity
> = z.object({
  atType: AtTypeBid$outboundSchema,
  orderId: z.string().optional(),
  hash: z.string(),
  maker: z.string(),
  make: Asset$outboundSchema,
  take: Asset$outboundSchema,
  price: z.string(),
  priceUsd: z.string().optional(),
  source: OrderActivitySource$outboundSchema.optional(),
  marketplaceMarker: z.string().optional(),
  id: z.string(),
  date: z.date().transform(v => v.toISOString()),
  lastUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrderBidActivity$ {
  /** @deprecated use `OrderBidActivity$inboundSchema` instead. */
  export const inboundSchema = OrderBidActivity$inboundSchema;
  /** @deprecated use `OrderBidActivity$outboundSchema` instead. */
  export const outboundSchema = OrderBidActivity$outboundSchema;
  /** @deprecated use `OrderBidActivity$Outbound` instead. */
  export type Outbound = OrderBidActivity$Outbound;
}

export function orderBidActivityToJSON(
  orderBidActivity: OrderBidActivity,
): string {
  return JSON.stringify(
    OrderBidActivity$outboundSchema.parse(orderBidActivity),
  );
}

export function orderBidActivityFromJSON(
  jsonString: string,
): SafeParseResult<OrderBidActivity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrderBidActivity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrderBidActivity' from JSON`,
  );
}

/** @internal */
export const ActivityOrderMatchActivityType$inboundSchema: z.ZodNativeEnum<
  typeof ActivityOrderMatchActivityType
> = z.nativeEnum(ActivityOrderMatchActivityType);

/** @internal */
export const ActivityOrderMatchActivityType$outboundSchema: z.ZodNativeEnum<
  typeof ActivityOrderMatchActivityType
> = ActivityOrderMatchActivityType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ActivityOrderMatchActivityType$ {
  /** @deprecated use `ActivityOrderMatchActivityType$inboundSchema` instead. */
  export const inboundSchema = ActivityOrderMatchActivityType$inboundSchema;
  /** @deprecated use `ActivityOrderMatchActivityType$outboundSchema` instead. */
  export const outboundSchema = ActivityOrderMatchActivityType$outboundSchema;
}


/** @internal */
export const OrderMatchActivityAtType$inboundSchema: z.ZodNativeEnum<
  typeof OrderMatchActivityAtType
> = z.nativeEnum(OrderMatchActivityAtType);

/** @internal */
export const OrderMatchActivityAtType$outboundSchema: z.ZodNativeEnum<
  typeof OrderMatchActivityAtType
> = OrderMatchActivityAtType$inboundSchema;

/** @internal */
export const OrderMatchSell$inboundSchema: z.ZodType<
  OrderMatchSell,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": OrderMatchActivityAtType$inboundSchema.optional(),
  nft: Asset$inboundSchema,
  payment: Asset$inboundSchema,
  buyer: z.string(),
  seller: z.string(),
  buyerOrderHash: z.string().optional(),
  sellerOrderHash: z.string().optional(),
  price: z.string(),
  priceUsd: z.string().optional(),
  amountUsd: z.string().optional(),
  type: ActivityOrderMatchActivityType$inboundSchema,
  sellMarketplaceMarker: z.string().optional(),
  buyMarketplaceMarker: z.string().optional(),
  orderId: z.string().optional(),
  source: OrderActivitySource$inboundSchema,
  transactionHash: z.string(),
  blockchainInfo: ActivityBlockchainInfo$inboundSchema.optional(),
  id: z.string(),
  date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  lastUpdatedAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type OrderMatchSell$Outbound = {
  "@type"?: string | undefined;
  nft: Asset$Outbound;
  payment: Asset$Outbound;
  buyer: string;
  seller: string;
  buyerOrderHash?: string | undefined;
  sellerOrderHash?: string | undefined;
  price: string;
  priceUsd?: string | undefined;
  amountUsd?: string | undefined;
  type: string;
  sellMarketplaceMarker?: string | undefined;
  buyMarketplaceMarker?: string | undefined;
  orderId?: string | undefined;
  source: string;
  transactionHash: string;
  blockchainInfo?: ActivityBlockchainInfo$Outbound | undefined;
  id: string;
  date: string;
  lastUpdatedAt?: string | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

/** @internal */
export const OrderMatchSell$outboundSchema: z.ZodType<
  OrderMatchSell$Outbound,
  z.ZodTypeDef,
  OrderMatchSell
> = z.object({
  atType: OrderMatchActivityAtType$outboundSchema.optional(),
  nft: Asset$outboundSchema,
  payment: Asset$outboundSchema,
  buyer: z.string(),
  seller: z.string(),
  buyerOrderHash: z.string().optional(),
  sellerOrderHash: z.string().optional(),
  price: z.string(),
  priceUsd: z.string().optional(),
  amountUsd: z.string().optional(),
  type: ActivityOrderMatchActivityType$outboundSchema,
  sellMarketplaceMarker: z.string().optional(),
  buyMarketplaceMarker: z.string().optional(),
  orderId: z.string().optional(),
  source: OrderActivitySource$outboundSchema,
  transactionHash: z.string(),
  blockchainInfo: ActivityBlockchainInfo$outboundSchema.optional(),
  id: z.string(),
  date: z.date().transform(v => v.toISOString()),
  lastUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrderMatchSell$ {
  /** @deprecated use `OrderMatchSell$inboundSchema` instead. */
  export const inboundSchema = OrderMatchSell$inboundSchema;
  /** @deprecated use `OrderMatchSell$outboundSchema` instead. */
  export const outboundSchema = OrderMatchSell$outboundSchema;
  /** @deprecated use `OrderMatchSell$Outbound` instead. */
  export type Outbound = OrderMatchSell$Outbound;
}

export function orderMatchSellToJSON(orderMatchSell: OrderMatchSell): string {
  return JSON.stringify(OrderMatchSell$outboundSchema.parse(orderMatchSell));
}

export function orderMatchSellFromJSON(
  jsonString: string,
): SafeParseResult<OrderMatchSell, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrderMatchSell$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrderMatchSell' from JSON`,
  );
}


/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrderMatchActivityAtType$ {
  /** @deprecated use `OrderMatchActivityAtType$inboundSchema` instead. */
  export const inboundSchema = OrderMatchActivityAtType$inboundSchema;
  /** @deprecated use `OrderMatchActivityAtType$outboundSchema` instead. */
  export const outboundSchema = OrderMatchActivityAtType$outboundSchema;
}

/** @internal */
export const OrderMatchSwap$inboundSchema: z.ZodType<
  OrderMatchSwap,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": OrderMatchActivityAtType$inboundSchema.optional(),
  left: OrderActivityMatchSide$inboundSchema,
  right: OrderActivityMatchSide$inboundSchema,
  orderId: z.string().optional(),
  source: OrderActivitySource$inboundSchema,
  transactionHash: z.string(),
  blockchainInfo: ActivityBlockchainInfo$inboundSchema.optional(),
  id: z.string(),
  date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  lastUpdatedAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type OrderMatchSwap$Outbound = {
  "@type"?: string | undefined;
  left: OrderActivityMatchSide$Outbound;
  right: OrderActivityMatchSide$Outbound;
  orderId?: string | undefined;
  source: string;
  transactionHash: string;
  blockchainInfo?: ActivityBlockchainInfo$Outbound | undefined;
  id: string;
  date: string;
  lastUpdatedAt?: string | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

/** @internal */
export const OrderMatchSwap$outboundSchema: z.ZodType<
  OrderMatchSwap$Outbound,
  z.ZodTypeDef,
  OrderMatchSwap
> = z.object({
  atType: OrderMatchActivityAtType$outboundSchema.optional(),
  left: OrderActivityMatchSide$outboundSchema,
  right: OrderActivityMatchSide$outboundSchema,
  orderId: z.string().optional(),
  source: OrderActivitySource$outboundSchema,
  transactionHash: z.string(),
  blockchainInfo: ActivityBlockchainInfo$outboundSchema.optional(),
  id: z.string(),
  date: z.date().transform(v => v.toISOString()),
  lastUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrderMatchSwap$ {
  /** @deprecated use `OrderMatchSwap$inboundSchema` instead. */
  export const inboundSchema = OrderMatchSwap$inboundSchema;
  /** @deprecated use `OrderMatchSwap$outboundSchema` instead. */
  export const outboundSchema = OrderMatchSwap$outboundSchema;
  /** @deprecated use `OrderMatchSwap$Outbound` instead. */
  export type Outbound = OrderMatchSwap$Outbound;
}

export function orderMatchSwapToJSON(orderMatchSwap: OrderMatchSwap): string {
  return JSON.stringify(OrderMatchSwap$outboundSchema.parse(orderMatchSwap));
}

export function orderMatchSwapFromJSON(
  jsonString: string,
): SafeParseResult<OrderMatchSwap, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrderMatchSwap$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrderMatchSwap' from JSON`,
  );
}

/** @internal */
export const OrderMatchActivity$inboundSchema: z.ZodType<
  OrderMatchActivity,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => OrderMatchSwap$inboundSchema),
  z.lazy(() => OrderMatchSell$inboundSchema),
]);

/** @internal */
export type OrderMatchActivity$Outbound =
  | OrderMatchSwap$Outbound
  | OrderMatchSell$Outbound;

/** @internal */
export const OrderMatchActivity$outboundSchema: z.ZodType<
  OrderMatchActivity$Outbound,
  z.ZodTypeDef,
  OrderMatchActivity
> = z.union([
  z.lazy(() => OrderMatchSwap$outboundSchema),
  z.lazy(() => OrderMatchSell$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrderMatchActivity$ {
  /** @deprecated use `OrderMatchActivity$inboundSchema` instead. */
  export const inboundSchema = OrderMatchActivity$inboundSchema;
  /** @deprecated use `OrderMatchActivity$outboundSchema` instead. */
  export const outboundSchema = OrderMatchActivity$outboundSchema;
  /** @deprecated use `OrderMatchActivity$Outbound` instead. */
  export type Outbound = OrderMatchActivity$Outbound;
}

export function orderMatchActivityToJSON(
  orderMatchActivity: OrderMatchActivity,
): string {
  return JSON.stringify(
    OrderMatchActivity$outboundSchema.parse(orderMatchActivity),
  );
}

export function orderMatchActivityFromJSON(
  jsonString: string,
): SafeParseResult<OrderMatchActivity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrderMatchActivity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrderMatchActivity' from JSON`,
  );
}

/** @internal */
export const AtTypeReceiveFromChain$inboundSchema: z.ZodNativeEnum<
  typeof AtTypeReceiveFromChain
> = z.nativeEnum(AtTypeReceiveFromChain);

/** @internal */
export const AtTypeReceiveFromChain$outboundSchema: z.ZodNativeEnum<
  typeof AtTypeReceiveFromChain
> = AtTypeReceiveFromChain$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AtTypeReceiveFromChain$ {
  /** @deprecated use `AtTypeReceiveFromChain$inboundSchema` instead. */
  export const inboundSchema = AtTypeReceiveFromChain$inboundSchema;
  /** @deprecated use `AtTypeReceiveFromChain$outboundSchema` instead. */
  export const outboundSchema = AtTypeReceiveFromChain$outboundSchema;
}

/** @internal */
export const ReceiveFromChainActivity$inboundSchema: z.ZodType<
  ReceiveFromChainActivity,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": AtTypeReceiveFromChain$inboundSchema,
  owner: z.string(),
  from: z.string(),
  chainId: z.string(),
  contract: z.string().optional(),
  collection: z.string().optional(),
  itemId: z.string(),
  value: z.string(),
  transactionHash: z.string(),
  blockchainInfo: ActivityBlockchainInfo$inboundSchema.optional(),
  id: z.string(),
  date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  lastUpdatedAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type ReceiveFromChainActivity$Outbound = {
  "@type": string;
  owner: string;
  from: string;
  chainId: string;
  contract?: string | undefined;
  collection?: string | undefined;
  itemId: string;
  value: string;
  transactionHash: string;
  blockchainInfo?: ActivityBlockchainInfo$Outbound | undefined;
  id: string;
  date: string;
  lastUpdatedAt?: string | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

/** @internal */
export const ReceiveFromChainActivity$outboundSchema: z.ZodType<
  ReceiveFromChainActivity$Outbound,
  z.ZodTypeDef,
  ReceiveFromChainActivity
> = z.object({
  atType: AtTypeReceiveFromChain$outboundSchema,
  owner: z.string(),
  from: z.string(),
  chainId: z.string(),
  contract: z.string().optional(),
  collection: z.string().optional(),
  itemId: z.string(),
  value: z.string(),
  transactionHash: z.string(),
  blockchainInfo: ActivityBlockchainInfo$outboundSchema.optional(),
  id: z.string(),
  date: z.date().transform(v => v.toISOString()),
  lastUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReceiveFromChainActivity$ {
  /** @deprecated use `ReceiveFromChainActivity$inboundSchema` instead. */
  export const inboundSchema = ReceiveFromChainActivity$inboundSchema;
  /** @deprecated use `ReceiveFromChainActivity$outboundSchema` instead. */
  export const outboundSchema = ReceiveFromChainActivity$outboundSchema;
  /** @deprecated use `ReceiveFromChainActivity$Outbound` instead. */
  export type Outbound = ReceiveFromChainActivity$Outbound;
}

export function receiveFromChainActivityToJSON(
  receiveFromChainActivity: ReceiveFromChainActivity,
): string {
  return JSON.stringify(
    ReceiveFromChainActivity$outboundSchema.parse(receiveFromChainActivity),
  );
}

export function receiveFromChainActivityFromJSON(
  jsonString: string,
): SafeParseResult<ReceiveFromChainActivity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReceiveFromChainActivity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReceiveFromChainActivity' from JSON`,
  );
}

/** @internal */
export const AtTypeSendToChain$inboundSchema: z.ZodNativeEnum<
  typeof AtTypeSendToChain
> = z.nativeEnum(AtTypeSendToChain);

/** @internal */
export const AtTypeSendToChain$outboundSchema: z.ZodNativeEnum<
  typeof AtTypeSendToChain
> = AtTypeSendToChain$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AtTypeSendToChain$ {
  /** @deprecated use `AtTypeSendToChain$inboundSchema` instead. */
  export const inboundSchema = AtTypeSendToChain$inboundSchema;
  /** @deprecated use `AtTypeSendToChain$outboundSchema` instead. */
  export const outboundSchema = AtTypeSendToChain$outboundSchema;
}

/** @internal */
export const SendToChainActivity$inboundSchema: z.ZodType<
  SendToChainActivity,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": AtTypeSendToChain$inboundSchema,
  owner: z.string(),
  to: z.string(),
  chainId: z.string(),
  contract: z.string().optional(),
  collection: z.string().optional(),
  itemId: z.string(),
  value: z.string(),
  transactionHash: z.string(),
  blockchainInfo: ActivityBlockchainInfo$inboundSchema.optional(),
  id: z.string(),
  date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  lastUpdatedAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type SendToChainActivity$Outbound = {
  "@type": string;
  owner: string;
  to: string;
  chainId: string;
  contract?: string | undefined;
  collection?: string | undefined;
  itemId: string;
  value: string;
  transactionHash: string;
  blockchainInfo?: ActivityBlockchainInfo$Outbound | undefined;
  id: string;
  date: string;
  lastUpdatedAt?: string | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

/** @internal */
export const SendToChainActivity$outboundSchema: z.ZodType<
  SendToChainActivity$Outbound,
  z.ZodTypeDef,
  SendToChainActivity
> = z.object({
  atType: AtTypeSendToChain$outboundSchema,
  owner: z.string(),
  to: z.string(),
  chainId: z.string(),
  contract: z.string().optional(),
  collection: z.string().optional(),
  itemId: z.string(),
  value: z.string(),
  transactionHash: z.string(),
  blockchainInfo: ActivityBlockchainInfo$outboundSchema.optional(),
  id: z.string(),
  date: z.date().transform(v => v.toISOString()),
  lastUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SendToChainActivity$ {
  /** @deprecated use `SendToChainActivity$inboundSchema` instead. */
  export const inboundSchema = SendToChainActivity$inboundSchema;
  /** @deprecated use `SendToChainActivity$outboundSchema` instead. */
  export const outboundSchema = SendToChainActivity$outboundSchema;
  /** @deprecated use `SendToChainActivity$Outbound` instead. */
  export type Outbound = SendToChainActivity$Outbound;
}

export function sendToChainActivityToJSON(
  sendToChainActivity: SendToChainActivity,
): string {
  return JSON.stringify(
    SendToChainActivity$outboundSchema.parse(sendToChainActivity),
  );
}

export function sendToChainActivityFromJSON(
  jsonString: string,
): SafeParseResult<SendToChainActivity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendToChainActivity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendToChainActivity' from JSON`,
  );
}

/** @internal */
export const ActivityAtTypeTransfer$inboundSchema: z.ZodNativeEnum<
  typeof ActivityAtTypeTransfer
> = z.nativeEnum(ActivityAtTypeTransfer);

/** @internal */
export const ActivityAtTypeTransfer$outboundSchema: z.ZodNativeEnum<
  typeof ActivityAtTypeTransfer
> = ActivityAtTypeTransfer$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ActivityAtTypeTransfer$ {
  /** @deprecated use `ActivityAtTypeTransfer$inboundSchema` instead. */
  export const inboundSchema = ActivityAtTypeTransfer$inboundSchema;
  /** @deprecated use `ActivityAtTypeTransfer$outboundSchema` instead. */
  export const outboundSchema = ActivityAtTypeTransfer$outboundSchema;
}

/** @internal */
export const TransferActivity$inboundSchema: z.ZodType<
  TransferActivity,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": ActivityAtTypeTransfer$inboundSchema,
  from: z.string(),
  owner: z.string(),
  contract: z.string().optional(),
  collection: z.string().optional(),
  tokenId: z.string().optional(),
  itemId: z.string().optional(),
  value: z.string(),
  purchase: z.boolean().optional(),
  transactionHash: z.string(),
  blockchainInfo: ActivityBlockchainInfo$inboundSchema.optional(),
  id: z.string(),
  date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  lastUpdatedAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type TransferActivity$Outbound = {
  "@type": string;
  from: string;
  owner: string;
  contract?: string | undefined;
  collection?: string | undefined;
  tokenId?: string | undefined;
  itemId?: string | undefined;
  value: string;
  purchase?: boolean | undefined;
  transactionHash: string;
  blockchainInfo?: ActivityBlockchainInfo$Outbound | undefined;
  id: string;
  date: string;
  lastUpdatedAt?: string | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

/** @internal */
export const TransferActivity$outboundSchema: z.ZodType<
  TransferActivity$Outbound,
  z.ZodTypeDef,
  TransferActivity
> = z.object({
  atType: ActivityAtTypeTransfer$outboundSchema,
  from: z.string(),
  owner: z.string(),
  contract: z.string().optional(),
  collection: z.string().optional(),
  tokenId: z.string().optional(),
  itemId: z.string().optional(),
  value: z.string(),
  purchase: z.boolean().optional(),
  transactionHash: z.string(),
  blockchainInfo: ActivityBlockchainInfo$outboundSchema.optional(),
  id: z.string(),
  date: z.date().transform(v => v.toISOString()),
  lastUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransferActivity$ {
  /** @deprecated use `TransferActivity$inboundSchema` instead. */
  export const inboundSchema = TransferActivity$inboundSchema;
  /** @deprecated use `TransferActivity$outboundSchema` instead. */
  export const outboundSchema = TransferActivity$outboundSchema;
  /** @deprecated use `TransferActivity$Outbound` instead. */
  export type Outbound = TransferActivity$Outbound;
}

export function transferActivityToJSON(
  transferActivity: TransferActivity,
): string {
  return JSON.stringify(
    TransferActivity$outboundSchema.parse(transferActivity),
  );
}

export function transferActivityFromJSON(
  jsonString: string,
): SafeParseResult<TransferActivity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransferActivity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransferActivity' from JSON`,
  );
}

/** @internal */
export const AtTypeBurn$inboundSchema: z.ZodNativeEnum<typeof AtTypeBurn> = z
  .nativeEnum(AtTypeBurn);

/** @internal */
export const AtTypeBurn$outboundSchema: z.ZodNativeEnum<typeof AtTypeBurn> =
  AtTypeBurn$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AtTypeBurn$ {
  /** @deprecated use `AtTypeBurn$inboundSchema` instead. */
  export const inboundSchema = AtTypeBurn$inboundSchema;
  /** @deprecated use `AtTypeBurn$outboundSchema` instead. */
  export const outboundSchema = AtTypeBurn$outboundSchema;
}

/** @internal */
export const BurnActivity$inboundSchema: z.ZodType<
  BurnActivity,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": AtTypeBurn$inboundSchema,
  owner: z.string(),
  contract: z.string().optional(),
  collection: z.string().optional(),
  tokenId: z.string().optional(),
  itemId: z.string().optional(),
  value: z.string(),
  transactionHash: z.string(),
  blockchainInfo: ActivityBlockchainInfo$inboundSchema.optional(),
  id: z.string(),
  date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  lastUpdatedAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type BurnActivity$Outbound = {
  "@type": string;
  owner: string;
  contract?: string | undefined;
  collection?: string | undefined;
  tokenId?: string | undefined;
  itemId?: string | undefined;
  value: string;
  transactionHash: string;
  blockchainInfo?: ActivityBlockchainInfo$Outbound | undefined;
  id: string;
  date: string;
  lastUpdatedAt?: string | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

/** @internal */
export const BurnActivity$outboundSchema: z.ZodType<
  BurnActivity$Outbound,
  z.ZodTypeDef,
  BurnActivity
> = z.object({
  atType: AtTypeBurn$outboundSchema,
  owner: z.string(),
  contract: z.string().optional(),
  collection: z.string().optional(),
  tokenId: z.string().optional(),
  itemId: z.string().optional(),
  value: z.string(),
  transactionHash: z.string(),
  blockchainInfo: ActivityBlockchainInfo$outboundSchema.optional(),
  id: z.string(),
  date: z.date().transform(v => v.toISOString()),
  lastUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BurnActivity$ {
  /** @deprecated use `BurnActivity$inboundSchema` instead. */
  export const inboundSchema = BurnActivity$inboundSchema;
  /** @deprecated use `BurnActivity$outboundSchema` instead. */
  export const outboundSchema = BurnActivity$outboundSchema;
  /** @deprecated use `BurnActivity$Outbound` instead. */
  export type Outbound = BurnActivity$Outbound;
}

export function burnActivityToJSON(burnActivity: BurnActivity): string {
  return JSON.stringify(BurnActivity$outboundSchema.parse(burnActivity));
}

export function burnActivityFromJSON(
  jsonString: string,
): SafeParseResult<BurnActivity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BurnActivity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BurnActivity' from JSON`,
  );
}

/** @internal */
export const AtTypeMint$inboundSchema: z.ZodNativeEnum<typeof AtTypeMint> = z
  .nativeEnum(AtTypeMint);

/** @internal */
export const AtTypeMint$outboundSchema: z.ZodNativeEnum<typeof AtTypeMint> =
  AtTypeMint$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AtTypeMint$ {
  /** @deprecated use `AtTypeMint$inboundSchema` instead. */
  export const inboundSchema = AtTypeMint$inboundSchema;
  /** @deprecated use `AtTypeMint$outboundSchema` instead. */
  export const outboundSchema = AtTypeMint$outboundSchema;
}

/** @internal */
export const MintActivity$inboundSchema: z.ZodType<
  MintActivity,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": AtTypeMint$inboundSchema,
  owner: z.string(),
  contract: z.string().optional(),
  collection: z.string().optional(),
  tokenId: z.string().optional(),
  itemId: z.string().optional(),
  value: z.string(),
  mintPrice: z.string().optional(),
  mintPayment: Asset$inboundSchema.optional(),
  mintPriceUsd: z.string().optional(),
  transactionHash: z.string(),
  blockchainInfo: ActivityBlockchainInfo$inboundSchema.optional(),
  id: z.string(),
  date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  lastUpdatedAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type MintActivity$Outbound = {
  "@type": string;
  owner: string;
  contract?: string | undefined;
  collection?: string | undefined;
  tokenId?: string | undefined;
  itemId?: string | undefined;
  value: string;
  mintPrice?: string | undefined;
  mintPayment?: Asset$Outbound | undefined;
  mintPriceUsd?: string | undefined;
  transactionHash: string;
  blockchainInfo?: ActivityBlockchainInfo$Outbound | undefined;
  id: string;
  date: string;
  lastUpdatedAt?: string | undefined;
  cursor?: string | undefined;
  reverted?: boolean | undefined;
  version?: number | undefined;
};

/** @internal */
export const MintActivity$outboundSchema: z.ZodType<
  MintActivity$Outbound,
  z.ZodTypeDef,
  MintActivity
> = z.object({
  atType: AtTypeMint$outboundSchema,
  owner: z.string(),
  contract: z.string().optional(),
  collection: z.string().optional(),
  tokenId: z.string().optional(),
  itemId: z.string().optional(),
  value: z.string(),
  mintPrice: z.string().optional(),
  mintPayment: Asset$outboundSchema.optional(),
  mintPriceUsd: z.string().optional(),
  transactionHash: z.string(),
  blockchainInfo: ActivityBlockchainInfo$outboundSchema.optional(),
  id: z.string(),
  date: z.date().transform(v => v.toISOString()),
  lastUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  cursor: z.string().optional(),
  reverted: z.boolean().optional(),
  version: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MintActivity$ {
  /** @deprecated use `MintActivity$inboundSchema` instead. */
  export const inboundSchema = MintActivity$inboundSchema;
  /** @deprecated use `MintActivity$outboundSchema` instead. */
  export const outboundSchema = MintActivity$outboundSchema;
  /** @deprecated use `MintActivity$Outbound` instead. */
  export type Outbound = MintActivity$Outbound;
}

export function mintActivityToJSON(mintActivity: MintActivity): string {
  return JSON.stringify(MintActivity$outboundSchema.parse(mintActivity));
}

export function mintActivityFromJSON(
  jsonString: string,
): SafeParseResult<MintActivity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MintActivity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MintActivity' from JSON`,
  );
}

/** @internal */
export const Activity$inboundSchema: z.ZodType<
  Activity,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => L2DepositActivity$inboundSchema),
  z.lazy(() => L2WithdrawalActivity$inboundSchema),
  z.lazy(() => BurnActivity$inboundSchema),
  z.lazy(() => OrderListActivity$inboundSchema),
  z.lazy(() => OrderCancelBidActivity$inboundSchema),
  z.lazy(() => OrderCancelListActivity$inboundSchema),
  z.lazy(() => SendToChainActivity$inboundSchema),
  z.lazy(() => ReceiveFromChainActivity$inboundSchema),
  z.lazy(() => OrderBidActivity$inboundSchema),
  z.lazy(() => TransferActivity$inboundSchema),
  z.lazy(() => MintActivity$inboundSchema),
  z.union([
    z.lazy(() => OrderMatchSwap$inboundSchema),
    z.lazy(() => OrderMatchSell$inboundSchema),
  ]),
]);

/** @internal */
export type Activity$Outbound =
  | L2DepositActivity$Outbound
  | L2WithdrawalActivity$Outbound
  | BurnActivity$Outbound
  | OrderListActivity$Outbound
  | OrderCancelBidActivity$Outbound
  | OrderCancelListActivity$Outbound
  | SendToChainActivity$Outbound
  | ReceiveFromChainActivity$Outbound
  | OrderBidActivity$Outbound
  | TransferActivity$Outbound
  | MintActivity$Outbound
  | OrderMatchSwap$Outbound
  | OrderMatchSell$Outbound;

/** @internal */
export const Activity$outboundSchema: z.ZodType<
  Activity$Outbound,
  z.ZodTypeDef,
  Activity
> = z.union([
  z.lazy(() => L2DepositActivity$outboundSchema),
  z.lazy(() => L2WithdrawalActivity$outboundSchema),
  z.lazy(() => BurnActivity$outboundSchema),
  z.lazy(() => OrderListActivity$outboundSchema),
  z.lazy(() => OrderCancelBidActivity$outboundSchema),
  z.lazy(() => OrderCancelListActivity$outboundSchema),
  z.lazy(() => SendToChainActivity$outboundSchema),
  z.lazy(() => ReceiveFromChainActivity$outboundSchema),
  z.lazy(() => OrderBidActivity$outboundSchema),
  z.lazy(() => TransferActivity$outboundSchema),
  z.lazy(() => MintActivity$outboundSchema),
  z.union([
    z.lazy(() => OrderMatchSwap$outboundSchema),
    z.lazy(() => OrderMatchSell$outboundSchema),
  ]),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Activity$ {
  /** @deprecated use `Activity$inboundSchema` instead. */
  export const inboundSchema = Activity$inboundSchema;
  /** @deprecated use `Activity$outboundSchema` instead. */
  export const outboundSchema = Activity$outboundSchema;
  /** @deprecated use `Activity$Outbound` instead. */
  export type Outbound = Activity$Outbound;
}

export function activityToJSON(activity: Activity): string {
  return JSON.stringify(Activity$outboundSchema.parse(activity));
}

export function activityFromJSON(
  jsonString: string,
): SafeParseResult<Activity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Activity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Activity' from JSON`,
  );
}
