/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ActivityCurrencyFilter = {
  bid?: Array<string> | undefined;
};

/** @internal */
export const ActivityCurrencyFilter$inboundSchema: z.ZodType<
  ActivityCurrencyFilter,
  z.ZodTypeDef,
  unknown
> = z.object({
  bid: z.array(z.string()).optional(),
});

/** @internal */
export type ActivityCurrencyFilter$Outbound = {
  bid?: Array<string> | undefined;
};

/** @internal */
export const ActivityCurrencyFilter$outboundSchema: z.ZodType<
  ActivityCurrencyFilter$Outbound,
  z.ZodTypeDef,
  ActivityCurrencyFilter
> = z.object({
  bid: z.array(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ActivityCurrencyFilter$ {
  /** @deprecated use `ActivityCurrencyFilter$inboundSchema` instead. */
  export const inboundSchema = ActivityCurrencyFilter$inboundSchema;
  /** @deprecated use `ActivityCurrencyFilter$outboundSchema` instead. */
  export const outboundSchema = ActivityCurrencyFilter$outboundSchema;
  /** @deprecated use `ActivityCurrencyFilter$Outbound` instead. */
  export type Outbound = ActivityCurrencyFilter$Outbound;
}

export function activityCurrencyFilterToJSON(
  activityCurrencyFilter: ActivityCurrencyFilter,
): string {
  return JSON.stringify(
    ActivityCurrencyFilter$outboundSchema.parse(activityCurrencyFilter),
  );
}

export function activityCurrencyFilterFromJSON(
  jsonString: string,
): SafeParseResult<ActivityCurrencyFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivityCurrencyFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivityCurrencyFilter' from JSON`,
  );
}
