/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ActivityCurrencyFilter,
  ActivityCurrencyFilter$inboundSchema,
  ActivityCurrencyFilter$Outbound,
  ActivityCurrencyFilter$outboundSchema,
} from "./activitycurrencyfilter.js";
import {
  ActivityType,
  ActivityType$inboundSchema,
  ActivityType$outboundSchema,
} from "./activitytype.js";
import {
  ActivityUserFilter,
  ActivityUserFilter$inboundSchema,
  ActivityUserFilter$Outbound,
  ActivityUserFilter$outboundSchema,
} from "./activityuserfilter.js";
import {
  Blockchain,
  Blockchain$inboundSchema,
  Blockchain$outboundSchema,
} from "./blockchain.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ActivitySearchFilter = {
  blockchains?: Array<Blockchain> | undefined;
  types?: Array<ActivityType> | undefined;
  collections?: Array<string> | undefined;
  items?: Array<string> | undefined;
  users?: ActivityUserFilter | undefined;
  currencies?: ActivityCurrencyFilter | undefined;
  from?: Date | undefined;
  to?: Date | undefined;
  fromBlockInclusive?: number | undefined;
  toBlockExclusive?: number | undefined;
};

/** @internal */
export const ActivitySearchFilter$inboundSchema: z.ZodType<
  ActivitySearchFilter,
  z.ZodTypeDef,
  unknown
> = z.object({
  blockchains: z.array(Blockchain$inboundSchema).optional(),
  types: z.array(ActivityType$inboundSchema).optional(),
  collections: z.array(z.string()).optional(),
  items: z.array(z.string()).optional(),
  users: ActivityUserFilter$inboundSchema.optional(),
  currencies: ActivityCurrencyFilter$inboundSchema.optional(),
  from: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  to: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  fromBlockInclusive: z.number().int().optional(),
  toBlockExclusive: z.number().int().optional(),
});

/** @internal */
export type ActivitySearchFilter$Outbound = {
  blockchains?: Array<string> | undefined;
  types?: Array<string> | undefined;
  collections?: Array<string> | undefined;
  items?: Array<string> | undefined;
  users?: ActivityUserFilter$Outbound | undefined;
  currencies?: ActivityCurrencyFilter$Outbound | undefined;
  from?: string | undefined;
  to?: string | undefined;
  fromBlockInclusive?: number | undefined;
  toBlockExclusive?: number | undefined;
};

/** @internal */
export const ActivitySearchFilter$outboundSchema: z.ZodType<
  ActivitySearchFilter$Outbound,
  z.ZodTypeDef,
  ActivitySearchFilter
> = z.object({
  blockchains: z.array(Blockchain$outboundSchema).optional(),
  types: z.array(ActivityType$outboundSchema).optional(),
  collections: z.array(z.string()).optional(),
  items: z.array(z.string()).optional(),
  users: ActivityUserFilter$outboundSchema.optional(),
  currencies: ActivityCurrencyFilter$outboundSchema.optional(),
  from: z.date().transform(v => v.toISOString()).optional(),
  to: z.date().transform(v => v.toISOString()).optional(),
  fromBlockInclusive: z.number().int().optional(),
  toBlockExclusive: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ActivitySearchFilter$ {
  /** @deprecated use `ActivitySearchFilter$inboundSchema` instead. */
  export const inboundSchema = ActivitySearchFilter$inboundSchema;
  /** @deprecated use `ActivitySearchFilter$outboundSchema` instead. */
  export const outboundSchema = ActivitySearchFilter$outboundSchema;
  /** @deprecated use `ActivitySearchFilter$Outbound` instead. */
  export type Outbound = ActivitySearchFilter$Outbound;
}

export function activitySearchFilterToJSON(
  activitySearchFilter: ActivitySearchFilter,
): string {
  return JSON.stringify(
    ActivitySearchFilter$outboundSchema.parse(activitySearchFilter),
  );
}

export function activitySearchFilterFromJSON(
  jsonString: string,
): SafeParseResult<ActivitySearchFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivitySearchFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivitySearchFilter' from JSON`,
  );
}
