/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Blockchain,
  Blockchain$inboundSchema,
  Blockchain$outboundSchema,
} from "./blockchain.js";
import {
  CollectionMeta,
  CollectionMeta$inboundSchema,
  CollectionMeta$Outbound,
  CollectionMeta$outboundSchema,
} from "./collectionmeta.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Order,
  Order$inboundSchema,
  Order$Outbound,
  Order$outboundSchema,
} from "./order.js";
import {
  OriginOrders,
  OriginOrders$inboundSchema,
  OriginOrders$Outbound,
  OriginOrders$outboundSchema,
} from "./originorders.js";

/**
 * Collection structure can be described as:
 *
 * @remarks
 * - REGULAR: a standalone collection that has a corresponding contract address on the blockchain.
 * - COMPOSITE: an artificial collection that is composed of one or more regular collections or items.
 * - PART: an artificial collection that is a part of a larger regular collection, thus has a parent collection.
 */
export const Structure = {
  Regular: "REGULAR",
  Composite: "COMPOSITE",
  Part: "PART",
} as const;
/**
 * Collection structure can be described as:
 *
 * @remarks
 * - REGULAR: a standalone collection that has a corresponding contract address on the blockchain.
 * - COMPOSITE: an artificial collection that is composed of one or more regular collections or items.
 * - PART: an artificial collection that is a part of a larger regular collection, thus has a parent collection.
 */
export type Structure = ClosedEnum<typeof Structure>;

export const CollectionType = {
  CryptoPunks: "CRYPTO_PUNKS",
  Erc721: "ERC721",
  Erc1155: "ERC1155",
  Flow: "FLOW",
  Solana: "SOLANA",
  TokenGroup2022: "TOKEN_GROUP_2022",
  Immutablex: "IMMUTABLEX",
  Aptos: "APTOS",
} as const;
export type CollectionType = ClosedEnum<typeof CollectionType>;

export const Status = {
  Pending: "PENDING",
  Error: "ERROR",
  Confirmed: "CONFIRMED",
} as const;
export type Status = ClosedEnum<typeof Status>;

export const CollectionFeature = {
  ApproveForAll: "APPROVE_FOR_ALL",
  SetUriPrefix: "SET_URI_PREFIX",
  Burn: "BURN",
  MintWithAddress: "MINT_WITH_ADDRESS",
  SecondarySaleFees: "SECONDARY_SALE_FEES",
  MintAndTransfer: "MINT_AND_TRANSFER",
  Pausable: "PAUSABLE",
  NotForSale: "NOT_FOR_SALE",
} as const;
export type CollectionFeature = ClosedEnum<typeof CollectionFeature>;

export type Collection = {
  /**
   * Collection id
   */
  id: string;
  /**
   * Collection id
   */
  parent?: string | undefined;
  blockchain: Blockchain;
  /**
   * Collection structure can be described as:
   *
   * @remarks
   * - REGULAR: a standalone collection that has a corresponding contract address on the blockchain.
   * - COMPOSITE: an artificial collection that is composed of one or more regular collections or items.
   * - PART: an artificial collection that is a part of a larger regular collection, thus has a parent collection.
   */
  structure?: Structure | undefined;
  type: CollectionType;
  status?: Status | undefined;
  name: string;
  symbol?: string | undefined;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  owner?: string | undefined;
  features: Array<CollectionFeature>;
  /**
   * List of addresses that can mint items in this collection
   */
  minters?: Array<string> | undefined;
  meta?: CollectionMeta | undefined;
  bestBidOrder?: Order | undefined;
  bestSellOrder?: Order | undefined;
  /**
   * Contains best bid order for each currency if exists
   */
  bestBidOrdersByCurrency?: Array<Order> | undefined;
  originOrders?: Array<OriginOrders> | undefined;
  self?: boolean | undefined;
  /**
   * Deprecated, use spamScore instead
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  scam?: boolean | undefined;
  /**
   * Spam score of the collection, 0 - not spam, 100 - spam
   */
  spamScore?: number | undefined;
  hasTraits?: boolean | undefined;
  shared?: boolean | undefined;
  /**
   * Blockchain-specific information about this NFT collection particular to that blockchain's data model
   */
  extra?: { [k: string]: string } | undefined;
  version?: number | undefined;
};

/** @internal */
export const Structure$inboundSchema: z.ZodNativeEnum<typeof Structure> = z
  .nativeEnum(Structure);

/** @internal */
export const Structure$outboundSchema: z.ZodNativeEnum<typeof Structure> =
  Structure$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Structure$ {
  /** @deprecated use `Structure$inboundSchema` instead. */
  export const inboundSchema = Structure$inboundSchema;
  /** @deprecated use `Structure$outboundSchema` instead. */
  export const outboundSchema = Structure$outboundSchema;
}

/** @internal */
export const CollectionType$inboundSchema: z.ZodNativeEnum<
  typeof CollectionType
> = z.nativeEnum(CollectionType);

/** @internal */
export const CollectionType$outboundSchema: z.ZodNativeEnum<
  typeof CollectionType
> = CollectionType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CollectionType$ {
  /** @deprecated use `CollectionType$inboundSchema` instead. */
  export const inboundSchema = CollectionType$inboundSchema;
  /** @deprecated use `CollectionType$outboundSchema` instead. */
  export const outboundSchema = CollectionType$outboundSchema;
}

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z
  .nativeEnum(Status);

/** @internal */
export const Status$outboundSchema: z.ZodNativeEnum<typeof Status> =
  Status$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Status$ {
  /** @deprecated use `Status$inboundSchema` instead. */
  export const inboundSchema = Status$inboundSchema;
  /** @deprecated use `Status$outboundSchema` instead. */
  export const outboundSchema = Status$outboundSchema;
}

/** @internal */
export const CollectionFeature$inboundSchema: z.ZodNativeEnum<
  typeof CollectionFeature
> = z.nativeEnum(CollectionFeature);

/** @internal */
export const CollectionFeature$outboundSchema: z.ZodNativeEnum<
  typeof CollectionFeature
> = CollectionFeature$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CollectionFeature$ {
  /** @deprecated use `CollectionFeature$inboundSchema` instead. */
  export const inboundSchema = CollectionFeature$inboundSchema;
  /** @deprecated use `CollectionFeature$outboundSchema` instead. */
  export const outboundSchema = CollectionFeature$outboundSchema;
}

/** @internal */
export const Collection$inboundSchema: z.ZodType<
  Collection,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  parent: z.string().optional(),
  blockchain: Blockchain$inboundSchema,
  structure: Structure$inboundSchema.optional(),
  type: CollectionType$inboundSchema,
  status: Status$inboundSchema.optional(),
  name: z.string(),
  symbol: z.string().optional(),
  owner: z.string().optional(),
  features: z.array(CollectionFeature$inboundSchema),
  minters: z.array(z.string()).optional(),
  meta: CollectionMeta$inboundSchema.optional(),
  bestBidOrder: Order$inboundSchema.optional(),
  bestSellOrder: Order$inboundSchema.optional(),
  bestBidOrdersByCurrency: z.array(Order$inboundSchema).optional(),
  originOrders: z.array(OriginOrders$inboundSchema).optional(),
  self: z.boolean().optional(),
  scam: z.boolean().default(false),
  spamScore: z.number().int().optional(),
  hasTraits: z.boolean().default(true),
  shared: z.boolean().default(false),
  extra: z.record(z.string()).optional(),
  version: z.number().int().optional(),
});

/** @internal */
export type Collection$Outbound = {
  id: string;
  parent?: string | undefined;
  blockchain: string;
  structure?: string | undefined;
  type: string;
  status?: string | undefined;
  name: string;
  symbol?: string | undefined;
  owner?: string | undefined;
  features: Array<string>;
  minters?: Array<string> | undefined;
  meta?: CollectionMeta$Outbound | undefined;
  bestBidOrder?: Order$Outbound | undefined;
  bestSellOrder?: Order$Outbound | undefined;
  bestBidOrdersByCurrency?: Array<Order$Outbound> | undefined;
  originOrders?: Array<OriginOrders$Outbound> | undefined;
  self?: boolean | undefined;
  scam: boolean;
  spamScore?: number | undefined;
  hasTraits: boolean;
  shared: boolean;
  extra?: { [k: string]: string } | undefined;
  version?: number | undefined;
};

/** @internal */
export const Collection$outboundSchema: z.ZodType<
  Collection$Outbound,
  z.ZodTypeDef,
  Collection
> = z.object({
  id: z.string(),
  parent: z.string().optional(),
  blockchain: Blockchain$outboundSchema,
  structure: Structure$outboundSchema.optional(),
  type: CollectionType$outboundSchema,
  status: Status$outboundSchema.optional(),
  name: z.string(),
  symbol: z.string().optional(),
  owner: z.string().optional(),
  features: z.array(CollectionFeature$outboundSchema),
  minters: z.array(z.string()).optional(),
  meta: CollectionMeta$outboundSchema.optional(),
  bestBidOrder: Order$outboundSchema.optional(),
  bestSellOrder: Order$outboundSchema.optional(),
  bestBidOrdersByCurrency: z.array(Order$outboundSchema).optional(),
  originOrders: z.array(OriginOrders$outboundSchema).optional(),
  self: z.boolean().optional(),
  scam: z.boolean().default(false),
  spamScore: z.number().int().optional(),
  hasTraits: z.boolean().default(true),
  shared: z.boolean().default(false),
  extra: z.record(z.string()).optional(),
  version: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Collection$ {
  /** @deprecated use `Collection$inboundSchema` instead. */
  export const inboundSchema = Collection$inboundSchema;
  /** @deprecated use `Collection$outboundSchema` instead. */
  export const outboundSchema = Collection$outboundSchema;
  /** @deprecated use `Collection$Outbound` instead. */
  export type Outbound = Collection$Outbound;
}

export function collectionToJSON(collection: Collection): string {
  return JSON.stringify(Collection$outboundSchema.parse(collection));
}

export function collectionFromJSON(
  jsonString: string,
): SafeParseResult<Collection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Collection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Collection' from JSON`,
  );
}
