/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Collection,
  Collection$inboundSchema,
  Collection$Outbound,
  Collection$outboundSchema,
} from "./collection.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CollectionWithOwnedItems = {
  collection: Collection;
  ownedItems: number;
};

/** @internal */
export const CollectionWithOwnedItems$inboundSchema: z.ZodType<
  CollectionWithOwnedItems,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection: Collection$inboundSchema,
  ownedItems: z.number().int(),
});

/** @internal */
export type CollectionWithOwnedItems$Outbound = {
  collection: Collection$Outbound;
  ownedItems: number;
};

/** @internal */
export const CollectionWithOwnedItems$outboundSchema: z.ZodType<
  CollectionWithOwnedItems$Outbound,
  z.ZodTypeDef,
  CollectionWithOwnedItems
> = z.object({
  collection: Collection$outboundSchema,
  ownedItems: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CollectionWithOwnedItems$ {
  /** @deprecated use `CollectionWithOwnedItems$inboundSchema` instead. */
  export const inboundSchema = CollectionWithOwnedItems$inboundSchema;
  /** @deprecated use `CollectionWithOwnedItems$outboundSchema` instead. */
  export const outboundSchema = CollectionWithOwnedItems$outboundSchema;
  /** @deprecated use `CollectionWithOwnedItems$Outbound` instead. */
  export type Outbound = CollectionWithOwnedItems$Outbound;
}

export function collectionWithOwnedItemsToJSON(
  collectionWithOwnedItems: CollectionWithOwnedItems,
): string {
  return JSON.stringify(
    CollectionWithOwnedItems$outboundSchema.parse(collectionWithOwnedItems),
  );
}

export function collectionWithOwnedItemsFromJSON(
  jsonString: string,
): SafeParseResult<CollectionWithOwnedItems, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CollectionWithOwnedItems$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CollectionWithOwnedItems' from JSON`,
  );
}
