/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  MetaContent,
  MetaContent$inboundSchema,
  MetaContent$Outbound,
  MetaContent$outboundSchema,
} from "./metacontent.js";

export type CollectionMeta = {
  /**
   * Name of the collection
   */
  name: string;
  /**
   * Description of the collection
   */
  description?: string | undefined;
  createdAt?: Date | undefined;
  tags?: Array<string> | undefined;
  genres?: Array<string> | undefined;
  /**
   * Language in RFC 1176 format
   */
  language?: string | undefined;
  rights?: string | undefined;
  rightsUri?: string | undefined;
  /**
   * URI to external page related to the collection
   */
  externalUri?: string | undefined;
  /**
   * URI to the original meta JSON
   */
  originalMetaUri?: string | undefined;
  content: Array<MetaContent>;
  /**
   * External link to the original website for the collection
   */
  externalLink?: string | undefined;
  /**
   * Indicates a 1% seller fee
   */
  sellerFeeBasisPoints?: number | undefined;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  feeRecipient?: string | undefined;
};

/** @internal */
export const CollectionMeta$inboundSchema: z.ZodType<
  CollectionMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  tags: z.array(z.string()).optional(),
  genres: z.array(z.string()).optional(),
  language: z.string().optional(),
  rights: z.string().optional(),
  rightsUri: z.string().optional(),
  externalUri: z.string().optional(),
  originalMetaUri: z.string().optional(),
  content: z.array(MetaContent$inboundSchema),
  externalLink: z.string().optional(),
  sellerFeeBasisPoints: z.number().int().optional(),
  feeRecipient: z.string().optional(),
});

/** @internal */
export type CollectionMeta$Outbound = {
  name: string;
  description?: string | undefined;
  createdAt?: string | undefined;
  tags?: Array<string> | undefined;
  genres?: Array<string> | undefined;
  language?: string | undefined;
  rights?: string | undefined;
  rightsUri?: string | undefined;
  externalUri?: string | undefined;
  originalMetaUri?: string | undefined;
  content: Array<MetaContent$Outbound>;
  externalLink?: string | undefined;
  sellerFeeBasisPoints?: number | undefined;
  feeRecipient?: string | undefined;
};

/** @internal */
export const CollectionMeta$outboundSchema: z.ZodType<
  CollectionMeta$Outbound,
  z.ZodTypeDef,
  CollectionMeta
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  createdAt: z.date().transform(v => v.toISOString()).optional(),
  tags: z.array(z.string()).optional(),
  genres: z.array(z.string()).optional(),
  language: z.string().optional(),
  rights: z.string().optional(),
  rightsUri: z.string().optional(),
  externalUri: z.string().optional(),
  originalMetaUri: z.string().optional(),
  content: z.array(MetaContent$outboundSchema),
  externalLink: z.string().optional(),
  sellerFeeBasisPoints: z.number().int().optional(),
  feeRecipient: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CollectionMeta$ {
  /** @deprecated use `CollectionMeta$inboundSchema` instead. */
  export const inboundSchema = CollectionMeta$inboundSchema;
  /** @deprecated use `CollectionMeta$outboundSchema` instead. */
  export const outboundSchema = CollectionMeta$outboundSchema;
  /** @deprecated use `CollectionMeta$Outbound` instead. */
  export type Outbound = CollectionMeta$Outbound;
}

export function collectionMetaToJSON(collectionMeta: CollectionMeta): string {
  return JSON.stringify(CollectionMeta$outboundSchema.parse(collectionMeta));
}

export function collectionMetaFromJSON(
  jsonString: string,
): SafeParseResult<CollectionMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CollectionMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CollectionMeta' from JSON`,
  );
}
