/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Blockchain,
  Blockchain$inboundSchema,
  Blockchain$outboundSchema,
} from "./blockchain.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Filter for collections search query
 */
export type CollectionsSearchFilter = {
  blockchains?: Array<Blockchain> | undefined;
  text: string;
};

/** @internal */
export const CollectionsSearchFilter$inboundSchema: z.ZodType<
  CollectionsSearchFilter,
  z.ZodTypeDef,
  unknown
> = z.object({
  blockchains: z.array(Blockchain$inboundSchema).optional(),
  text: z.string(),
});

/** @internal */
export type CollectionsSearchFilter$Outbound = {
  blockchains?: Array<string> | undefined;
  text: string;
};

/** @internal */
export const CollectionsSearchFilter$outboundSchema: z.ZodType<
  CollectionsSearchFilter$Outbound,
  z.ZodTypeDef,
  CollectionsSearchFilter
> = z.object({
  blockchains: z.array(Blockchain$outboundSchema).optional(),
  text: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CollectionsSearchFilter$ {
  /** @deprecated use `CollectionsSearchFilter$inboundSchema` instead. */
  export const inboundSchema = CollectionsSearchFilter$inboundSchema;
  /** @deprecated use `CollectionsSearchFilter$outboundSchema` instead. */
  export const outboundSchema = CollectionsSearchFilter$outboundSchema;
  /** @deprecated use `CollectionsSearchFilter$Outbound` instead. */
  export type Outbound = CollectionsSearchFilter$Outbound;
}

export function collectionsSearchFilterToJSON(
  collectionsSearchFilter: CollectionsSearchFilter,
): string {
  return JSON.stringify(
    CollectionsSearchFilter$outboundSchema.parse(collectionsSearchFilter),
  );
}

export function collectionsSearchFilterFromJSON(
  jsonString: string,
): SafeParseResult<CollectionsSearchFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CollectionsSearchFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CollectionsSearchFilter' from JSON`,
  );
}
