/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CollectionsSearchFilter,
  CollectionsSearchFilter$inboundSchema,
  CollectionsSearchFilter$Outbound,
  CollectionsSearchFilter$outboundSchema,
} from "./collectionssearchfilter.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Complex search request for collections
 */
export type CollectionsSearchRequest = {
  /**
   * Number of entities returned
   */
  size?: number | undefined;
  /**
   * Continuation token to paginate collections search result
   */
  continuation?: string | undefined;
  /**
   * Filter for collections search query
   */
  filter: CollectionsSearchFilter;
};

/** @internal */
export const CollectionsSearchRequest$inboundSchema: z.ZodType<
  CollectionsSearchRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  size: z.number().int().default(50),
  continuation: z.string().optional(),
  filter: CollectionsSearchFilter$inboundSchema,
});

/** @internal */
export type CollectionsSearchRequest$Outbound = {
  size: number;
  continuation?: string | undefined;
  filter: CollectionsSearchFilter$Outbound;
};

/** @internal */
export const CollectionsSearchRequest$outboundSchema: z.ZodType<
  CollectionsSearchRequest$Outbound,
  z.ZodTypeDef,
  CollectionsSearchRequest
> = z.object({
  size: z.number().int().default(50),
  continuation: z.string().optional(),
  filter: CollectionsSearchFilter$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CollectionsSearchRequest$ {
  /** @deprecated use `CollectionsSearchRequest$inboundSchema` instead. */
  export const inboundSchema = CollectionsSearchRequest$inboundSchema;
  /** @deprecated use `CollectionsSearchRequest$outboundSchema` instead. */
  export const outboundSchema = CollectionsSearchRequest$outboundSchema;
  /** @deprecated use `CollectionsSearchRequest$Outbound` instead. */
  export type Outbound = CollectionsSearchRequest$Outbound;
}

export function collectionsSearchRequestToJSON(
  collectionsSearchRequest: CollectionsSearchRequest,
): string {
  return JSON.stringify(
    CollectionsSearchRequest$outboundSchema.parse(collectionsSearchRequest),
  );
}

export function collectionsSearchRequestFromJSON(
  jsonString: string,
): SafeParseResult<CollectionsSearchRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CollectionsSearchRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CollectionsSearchRequest' from JSON`,
  );
}
