/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CurrencyUsdRate = {
  /**
   * Currency Id
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  currencyId?: string | undefined;
  /**
   * Currency Symbol
   */
  symbol: string;
  abbreviation?: string | undefined;
  rate: string;
  /**
   * Date and time of currency USD rate
   */
  date: Date;
};

/** @internal */
export const CurrencyUsdRate$inboundSchema: z.ZodType<
  CurrencyUsdRate,
  z.ZodTypeDef,
  unknown
> = z.object({
  currencyId: z.string().optional(),
  symbol: z.string(),
  abbreviation: z.string().optional(),
  rate: z.string(),
  date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
});

/** @internal */
export type CurrencyUsdRate$Outbound = {
  currencyId?: string | undefined;
  symbol: string;
  abbreviation?: string | undefined;
  rate: string;
  date: string;
};

/** @internal */
export const CurrencyUsdRate$outboundSchema: z.ZodType<
  CurrencyUsdRate$Outbound,
  z.ZodTypeDef,
  CurrencyUsdRate
> = z.object({
  currencyId: z.string().optional(),
  symbol: z.string(),
  abbreviation: z.string().optional(),
  rate: z.string(),
  date: z.date().transform(v => v.toISOString()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CurrencyUsdRate$ {
  /** @deprecated use `CurrencyUsdRate$inboundSchema` instead. */
  export const inboundSchema = CurrencyUsdRate$inboundSchema;
  /** @deprecated use `CurrencyUsdRate$outboundSchema` instead. */
  export const outboundSchema = CurrencyUsdRate$outboundSchema;
  /** @deprecated use `CurrencyUsdRate$Outbound` instead. */
  export type Outbound = CurrencyUsdRate$Outbound;
}

export function currencyUsdRateToJSON(
  currencyUsdRate: CurrencyUsdRate,
): string {
  return JSON.stringify(CurrencyUsdRate$outboundSchema.parse(currencyUsdRate));
}

export function currencyUsdRateFromJSON(
  jsonString: string,
): SafeParseResult<CurrencyUsdRate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CurrencyUsdRate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CurrencyUsdRate' from JSON`,
  );
}
