/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Item,
  Item$inboundSchema,
  Item$Outbound,
  Item$outboundSchema,
} from "./item.js";
import {
  ItemTraitProperty,
  ItemTraitProperty$inboundSchema,
  ItemTraitProperty$Outbound,
  ItemTraitProperty$outboundSchema,
} from "./itemtraitproperty.js";

export type DuplicatedItem = {
  traitGroups: Array<ItemTraitProperty>;
  /**
   * Number of duplicated items in the group
   */
  count: number;
  item: Item;
};

/** @internal */
export const DuplicatedItem$inboundSchema: z.ZodType<
  DuplicatedItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  traitGroups: z.array(ItemTraitProperty$inboundSchema),
  count: z.number().int(),
  item: Item$inboundSchema,
});

/** @internal */
export type DuplicatedItem$Outbound = {
  traitGroups: Array<ItemTraitProperty$Outbound>;
  count: number;
  item: Item$Outbound;
};

/** @internal */
export const DuplicatedItem$outboundSchema: z.ZodType<
  DuplicatedItem$Outbound,
  z.ZodTypeDef,
  DuplicatedItem
> = z.object({
  traitGroups: z.array(ItemTraitProperty$outboundSchema),
  count: z.number().int(),
  item: Item$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DuplicatedItem$ {
  /** @deprecated use `DuplicatedItem$inboundSchema` instead. */
  export const inboundSchema = DuplicatedItem$inboundSchema;
  /** @deprecated use `DuplicatedItem$outboundSchema` instead. */
  export const outboundSchema = DuplicatedItem$outboundSchema;
  /** @deprecated use `DuplicatedItem$Outbound` instead. */
  export type Outbound = DuplicatedItem$Outbound;
}

export function duplicatedItemToJSON(duplicatedItem: DuplicatedItem): string {
  return JSON.stringify(DuplicatedItem$outboundSchema.parse(duplicatedItem));
}

export function duplicatedItemFromJSON(
  jsonString: string,
): SafeParseResult<DuplicatedItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DuplicatedItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DuplicatedItem' from JSON`,
  );
}
