/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const EthCryptoPunksAssetTypeAtType = {
  CryptoPunks: "CRYPTO_PUNKS",
} as const;
export type EthCryptoPunksAssetTypeAtType = ClosedEnum<
  typeof EthCryptoPunksAssetTypeAtType
>;

export type EthCryptoPunksAssetType = {
  atType: EthCryptoPunksAssetTypeAtType;
  /**
   * Blockchain contract address in Union format `ETHEREUM:${token}`
   */
  contract: string;
  /**
   * Collection id
   */
  collection?: string | undefined;
  tokenId: number;
};

/** @internal */
export const EthCryptoPunksAssetTypeAtType$inboundSchema: z.ZodNativeEnum<
  typeof EthCryptoPunksAssetTypeAtType
> = z.nativeEnum(EthCryptoPunksAssetTypeAtType);

/** @internal */
export const EthCryptoPunksAssetTypeAtType$outboundSchema: z.ZodNativeEnum<
  typeof EthCryptoPunksAssetTypeAtType
> = EthCryptoPunksAssetTypeAtType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthCryptoPunksAssetTypeAtType$ {
  /** @deprecated use `EthCryptoPunksAssetTypeAtType$inboundSchema` instead. */
  export const inboundSchema = EthCryptoPunksAssetTypeAtType$inboundSchema;
  /** @deprecated use `EthCryptoPunksAssetTypeAtType$outboundSchema` instead. */
  export const outboundSchema = EthCryptoPunksAssetTypeAtType$outboundSchema;
}

/** @internal */
export const EthCryptoPunksAssetType$inboundSchema: z.ZodType<
  EthCryptoPunksAssetType,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": EthCryptoPunksAssetTypeAtType$inboundSchema,
  contract: z.string(),
  collection: z.string().optional(),
  tokenId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type EthCryptoPunksAssetType$Outbound = {
  "@type": string;
  contract: string;
  collection?: string | undefined;
  tokenId: number;
};

/** @internal */
export const EthCryptoPunksAssetType$outboundSchema: z.ZodType<
  EthCryptoPunksAssetType$Outbound,
  z.ZodTypeDef,
  EthCryptoPunksAssetType
> = z.object({
  atType: EthCryptoPunksAssetTypeAtType$outboundSchema,
  contract: z.string(),
  collection: z.string().optional(),
  tokenId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthCryptoPunksAssetType$ {
  /** @deprecated use `EthCryptoPunksAssetType$inboundSchema` instead. */
  export const inboundSchema = EthCryptoPunksAssetType$inboundSchema;
  /** @deprecated use `EthCryptoPunksAssetType$outboundSchema` instead. */
  export const outboundSchema = EthCryptoPunksAssetType$outboundSchema;
  /** @deprecated use `EthCryptoPunksAssetType$Outbound` instead. */
  export type Outbound = EthCryptoPunksAssetType$Outbound;
}

export function ethCryptoPunksAssetTypeToJSON(
  ethCryptoPunksAssetType: EthCryptoPunksAssetType,
): string {
  return JSON.stringify(
    EthCryptoPunksAssetType$outboundSchema.parse(ethCryptoPunksAssetType),
  );
}

export function ethCryptoPunksAssetTypeFromJSON(
  jsonString: string,
): SafeParseResult<EthCryptoPunksAssetType, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EthCryptoPunksAssetType$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EthCryptoPunksAssetType' from JSON`,
  );
}
