/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const EthCollectionAssetTypeAtType = {
  Collection: "COLLECTION",
} as const;
export type EthCollectionAssetTypeAtType = ClosedEnum<
  typeof EthCollectionAssetTypeAtType
>;

export type EthCollectionAssetType = {
  atType: EthCollectionAssetTypeAtType;
  /**
   * Blockchain contract address in Union format `ETHEREUM:${token}`
   */
  contract: string;
  /**
   * Collection id
   */
  collection?: string | undefined;
};

/** @internal */
export const EthCollectionAssetTypeAtType$inboundSchema: z.ZodNativeEnum<
  typeof EthCollectionAssetTypeAtType
> = z.nativeEnum(EthCollectionAssetTypeAtType);

/** @internal */
export const EthCollectionAssetTypeAtType$outboundSchema: z.ZodNativeEnum<
  typeof EthCollectionAssetTypeAtType
> = EthCollectionAssetTypeAtType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthCollectionAssetTypeAtType$ {
  /** @deprecated use `EthCollectionAssetTypeAtType$inboundSchema` instead. */
  export const inboundSchema = EthCollectionAssetTypeAtType$inboundSchema;
  /** @deprecated use `EthCollectionAssetTypeAtType$outboundSchema` instead. */
  export const outboundSchema = EthCollectionAssetTypeAtType$outboundSchema;
}

/** @internal */
export const EthCollectionAssetType$inboundSchema: z.ZodType<
  EthCollectionAssetType,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": EthCollectionAssetTypeAtType$inboundSchema,
  contract: z.string(),
  collection: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type EthCollectionAssetType$Outbound = {
  "@type": string;
  contract: string;
  collection?: string | undefined;
};

/** @internal */
export const EthCollectionAssetType$outboundSchema: z.ZodType<
  EthCollectionAssetType$Outbound,
  z.ZodTypeDef,
  EthCollectionAssetType
> = z.object({
  atType: EthCollectionAssetTypeAtType$outboundSchema,
  contract: z.string(),
  collection: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthCollectionAssetType$ {
  /** @deprecated use `EthCollectionAssetType$inboundSchema` instead. */
  export const inboundSchema = EthCollectionAssetType$inboundSchema;
  /** @deprecated use `EthCollectionAssetType$outboundSchema` instead. */
  export const outboundSchema = EthCollectionAssetType$outboundSchema;
  /** @deprecated use `EthCollectionAssetType$Outbound` instead. */
  export type Outbound = EthCollectionAssetType$Outbound;
}

export function ethCollectionAssetTypeToJSON(
  ethCollectionAssetType: EthCollectionAssetType,
): string {
  return JSON.stringify(
    EthCollectionAssetType$outboundSchema.parse(ethCollectionAssetType),
  );
}

export function ethCollectionAssetTypeFromJSON(
  jsonString: string,
): SafeParseResult<EthCollectionAssetType, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EthCollectionAssetType$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EthCollectionAssetType' from JSON`,
  );
}
