/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const EthErc721AssetTypeAtType = {
  Erc721: "ERC721",
} as const;
export type EthErc721AssetTypeAtType = ClosedEnum<
  typeof EthErc721AssetTypeAtType
>;

export type EthErc721AssetType = {
  atType: EthErc721AssetTypeAtType;
  /**
   * Blockchain contract address in Union format `ETHEREUM:${token}`
   */
  contract: string;
  /**
   * Collection id
   */
  collection?: string | undefined;
  tokenId: string;
};

/** @internal */
export const EthErc721AssetTypeAtType$inboundSchema: z.ZodNativeEnum<
  typeof EthErc721AssetTypeAtType
> = z.nativeEnum(EthErc721AssetTypeAtType);

/** @internal */
export const EthErc721AssetTypeAtType$outboundSchema: z.ZodNativeEnum<
  typeof EthErc721AssetTypeAtType
> = EthErc721AssetTypeAtType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthErc721AssetTypeAtType$ {
  /** @deprecated use `EthErc721AssetTypeAtType$inboundSchema` instead. */
  export const inboundSchema = EthErc721AssetTypeAtType$inboundSchema;
  /** @deprecated use `EthErc721AssetTypeAtType$outboundSchema` instead. */
  export const outboundSchema = EthErc721AssetTypeAtType$outboundSchema;
}

/** @internal */
export const EthErc721AssetType$inboundSchema: z.ZodType<
  EthErc721AssetType,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": EthErc721AssetTypeAtType$inboundSchema,
  contract: z.string(),
  collection: z.string().optional(),
  tokenId: z.string(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type EthErc721AssetType$Outbound = {
  "@type": string;
  contract: string;
  collection?: string | undefined;
  tokenId: string;
};

/** @internal */
export const EthErc721AssetType$outboundSchema: z.ZodType<
  EthErc721AssetType$Outbound,
  z.ZodTypeDef,
  EthErc721AssetType
> = z.object({
  atType: EthErc721AssetTypeAtType$outboundSchema,
  contract: z.string(),
  collection: z.string().optional(),
  tokenId: z.string(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthErc721AssetType$ {
  /** @deprecated use `EthErc721AssetType$inboundSchema` instead. */
  export const inboundSchema = EthErc721AssetType$inboundSchema;
  /** @deprecated use `EthErc721AssetType$outboundSchema` instead. */
  export const outboundSchema = EthErc721AssetType$outboundSchema;
  /** @deprecated use `EthErc721AssetType$Outbound` instead. */
  export type Outbound = EthErc721AssetType$Outbound;
}

export function ethErc721AssetTypeToJSON(
  ethErc721AssetType: EthErc721AssetType,
): string {
  return JSON.stringify(
    EthErc721AssetType$outboundSchema.parse(ethErc721AssetType),
  );
}

export function ethErc721AssetTypeFromJSON(
  jsonString: string,
): SafeParseResult<EthErc721AssetType, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EthErc721AssetType$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EthErc721AssetType' from JSON`,
  );
}
