/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Payout,
  Payout$inboundSchema,
  Payout$Outbound,
  Payout$outboundSchema,
} from "./payout.js";

export const EthOrderDataRaribleV2DataV3BuyAtType = {
  EthRaribleV2DataV3Buy: "ETH_RARIBLE_V2_DATA_V3_BUY",
} as const;
export type EthOrderDataRaribleV2DataV3BuyAtType = ClosedEnum<
  typeof EthOrderDataRaribleV2DataV3BuyAtType
>;

export type EthOrderDataRaribleV2DataV3Buy = {
  atType: EthOrderDataRaribleV2DataV3BuyAtType;
  payout?: Payout | undefined;
  originFeeFirst?: Payout | undefined;
  originFeeSecond?: Payout | undefined;
  marketplaceMarker?: string | undefined;
};

/** @internal */
export const EthOrderDataRaribleV2DataV3BuyAtType$inboundSchema:
  z.ZodNativeEnum<typeof EthOrderDataRaribleV2DataV3BuyAtType> = z.nativeEnum(
    EthOrderDataRaribleV2DataV3BuyAtType,
  );

/** @internal */
export const EthOrderDataRaribleV2DataV3BuyAtType$outboundSchema:
  z.ZodNativeEnum<typeof EthOrderDataRaribleV2DataV3BuyAtType> =
    EthOrderDataRaribleV2DataV3BuyAtType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthOrderDataRaribleV2DataV3BuyAtType$ {
  /** @deprecated use `EthOrderDataRaribleV2DataV3BuyAtType$inboundSchema` instead. */
  export const inboundSchema =
    EthOrderDataRaribleV2DataV3BuyAtType$inboundSchema;
  /** @deprecated use `EthOrderDataRaribleV2DataV3BuyAtType$outboundSchema` instead. */
  export const outboundSchema =
    EthOrderDataRaribleV2DataV3BuyAtType$outboundSchema;
}

/** @internal */
export const EthOrderDataRaribleV2DataV3Buy$inboundSchema: z.ZodType<
  EthOrderDataRaribleV2DataV3Buy,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": EthOrderDataRaribleV2DataV3BuyAtType$inboundSchema,
  payout: Payout$inboundSchema.optional(),
  originFeeFirst: Payout$inboundSchema.optional(),
  originFeeSecond: Payout$inboundSchema.optional(),
  marketplaceMarker: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type EthOrderDataRaribleV2DataV3Buy$Outbound = {
  "@type": string;
  payout?: Payout$Outbound | undefined;
  originFeeFirst?: Payout$Outbound | undefined;
  originFeeSecond?: Payout$Outbound | undefined;
  marketplaceMarker?: string | undefined;
};

/** @internal */
export const EthOrderDataRaribleV2DataV3Buy$outboundSchema: z.ZodType<
  EthOrderDataRaribleV2DataV3Buy$Outbound,
  z.ZodTypeDef,
  EthOrderDataRaribleV2DataV3Buy
> = z.object({
  atType: EthOrderDataRaribleV2DataV3BuyAtType$outboundSchema,
  payout: Payout$outboundSchema.optional(),
  originFeeFirst: Payout$outboundSchema.optional(),
  originFeeSecond: Payout$outboundSchema.optional(),
  marketplaceMarker: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthOrderDataRaribleV2DataV3Buy$ {
  /** @deprecated use `EthOrderDataRaribleV2DataV3Buy$inboundSchema` instead. */
  export const inboundSchema = EthOrderDataRaribleV2DataV3Buy$inboundSchema;
  /** @deprecated use `EthOrderDataRaribleV2DataV3Buy$outboundSchema` instead. */
  export const outboundSchema = EthOrderDataRaribleV2DataV3Buy$outboundSchema;
  /** @deprecated use `EthOrderDataRaribleV2DataV3Buy$Outbound` instead. */
  export type Outbound = EthOrderDataRaribleV2DataV3Buy$Outbound;
}

export function ethOrderDataRaribleV2DataV3BuyToJSON(
  ethOrderDataRaribleV2DataV3Buy: EthOrderDataRaribleV2DataV3Buy,
): string {
  return JSON.stringify(
    EthOrderDataRaribleV2DataV3Buy$outboundSchema.parse(
      ethOrderDataRaribleV2DataV3Buy,
    ),
  );
}

export function ethOrderDataRaribleV2DataV3BuyFromJSON(
  jsonString: string,
): SafeParseResult<EthOrderDataRaribleV2DataV3Buy, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EthOrderDataRaribleV2DataV3Buy$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EthOrderDataRaribleV2DataV3Buy' from JSON`,
  );
}
