/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const EthOrderDataLegacyAtType = {
  EthRaribleV1: "ETH_RARIBLE_V1",
} as const;
export type EthOrderDataLegacyAtType = ClosedEnum<
  typeof EthOrderDataLegacyAtType
>;

export type EthOrderDataLegacy = {
  atType: EthOrderDataLegacyAtType;
  fee: string;
};

/** @internal */
export const EthOrderDataLegacyAtType$inboundSchema: z.ZodNativeEnum<
  typeof EthOrderDataLegacyAtType
> = z.nativeEnum(EthOrderDataLegacyAtType);

/** @internal */
export const EthOrderDataLegacyAtType$outboundSchema: z.ZodNativeEnum<
  typeof EthOrderDataLegacyAtType
> = EthOrderDataLegacyAtType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthOrderDataLegacyAtType$ {
  /** @deprecated use `EthOrderDataLegacyAtType$inboundSchema` instead. */
  export const inboundSchema = EthOrderDataLegacyAtType$inboundSchema;
  /** @deprecated use `EthOrderDataLegacyAtType$outboundSchema` instead. */
  export const outboundSchema = EthOrderDataLegacyAtType$outboundSchema;
}

/** @internal */
export const EthOrderDataLegacy$inboundSchema: z.ZodType<
  EthOrderDataLegacy,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": EthOrderDataLegacyAtType$inboundSchema,
  fee: z.string(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type EthOrderDataLegacy$Outbound = {
  "@type": string;
  fee: string;
};

/** @internal */
export const EthOrderDataLegacy$outboundSchema: z.ZodType<
  EthOrderDataLegacy$Outbound,
  z.ZodTypeDef,
  EthOrderDataLegacy
> = z.object({
  atType: EthOrderDataLegacyAtType$outboundSchema,
  fee: z.string(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthOrderDataLegacy$ {
  /** @deprecated use `EthOrderDataLegacy$inboundSchema` instead. */
  export const inboundSchema = EthOrderDataLegacy$inboundSchema;
  /** @deprecated use `EthOrderDataLegacy$outboundSchema` instead. */
  export const outboundSchema = EthOrderDataLegacy$outboundSchema;
  /** @deprecated use `EthOrderDataLegacy$Outbound` instead. */
  export type Outbound = EthOrderDataLegacy$Outbound;
}

export function ethOrderDataLegacyToJSON(
  ethOrderDataLegacy: EthOrderDataLegacy,
): string {
  return JSON.stringify(
    EthOrderDataLegacy$outboundSchema.parse(ethOrderDataLegacy),
  );
}

export function ethOrderDataLegacyFromJSON(
  jsonString: string,
): SafeParseResult<EthOrderDataLegacy, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EthOrderDataLegacy$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EthOrderDataLegacy' from JSON`,
  );
}
