/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AssetType,
  AssetType$inboundSchema,
  AssetType$Outbound,
  AssetType$outboundSchema,
} from "./assettype.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type EthOrderFormAsset = {
  assetType: AssetType;
  value: string;
};

/** @internal */
export const EthOrderFormAsset$inboundSchema: z.ZodType<
  EthOrderFormAsset,
  z.ZodTypeDef,
  unknown
> = z.object({
  assetType: AssetType$inboundSchema,
  value: z.string(),
});

/** @internal */
export type EthOrderFormAsset$Outbound = {
  assetType: AssetType$Outbound;
  value: string;
};

/** @internal */
export const EthOrderFormAsset$outboundSchema: z.ZodType<
  EthOrderFormAsset$Outbound,
  z.ZodTypeDef,
  EthOrderFormAsset
> = z.object({
  assetType: AssetType$outboundSchema,
  value: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthOrderFormAsset$ {
  /** @deprecated use `EthOrderFormAsset$inboundSchema` instead. */
  export const inboundSchema = EthOrderFormAsset$inboundSchema;
  /** @deprecated use `EthOrderFormAsset$outboundSchema` instead. */
  export const outboundSchema = EthOrderFormAsset$outboundSchema;
  /** @deprecated use `EthOrderFormAsset$Outbound` instead. */
  export type Outbound = EthOrderFormAsset$Outbound;
}

export function ethOrderFormAssetToJSON(
  ethOrderFormAsset: EthOrderFormAsset,
): string {
  return JSON.stringify(
    EthOrderFormAsset$outboundSchema.parse(ethOrderFormAsset),
  );
}

export function ethOrderFormAssetFromJSON(
  jsonString: string,
): SafeParseResult<EthOrderFormAsset, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EthOrderFormAsset$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EthOrderFormAsset' from JSON`,
  );
}
