/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Payout,
  Payout$inboundSchema,
  Payout$Outbound,
  Payout$outboundSchema,
} from "./payout.js";

export const EthOrderDataRaribleV2DataV3AtType = {
  EthRaribleV23: "ETH_RARIBLE_V2_3",
} as const;
export type EthOrderDataRaribleV2DataV3AtType = ClosedEnum<
  typeof EthOrderDataRaribleV2DataV3AtType
>;

export type EthOrderDataRaribleV2DataV3 = {
  atType: EthOrderDataRaribleV2DataV3AtType;
  payouts: Array<Payout>;
  originFees: Array<Payout>;
  /**
   * If true, the 'fill' part of the order applies to the 'make' side, otherwise to the 'take' side
   */
  isMakeFill: boolean;
};

/** @internal */
export const EthOrderDataRaribleV2DataV3AtType$inboundSchema: z.ZodNativeEnum<
  typeof EthOrderDataRaribleV2DataV3AtType
> = z.nativeEnum(EthOrderDataRaribleV2DataV3AtType);

/** @internal */
export const EthOrderDataRaribleV2DataV3AtType$outboundSchema: z.ZodNativeEnum<
  typeof EthOrderDataRaribleV2DataV3AtType
> = EthOrderDataRaribleV2DataV3AtType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthOrderDataRaribleV2DataV3AtType$ {
  /** @deprecated use `EthOrderDataRaribleV2DataV3AtType$inboundSchema` instead. */
  export const inboundSchema = EthOrderDataRaribleV2DataV3AtType$inboundSchema;
  /** @deprecated use `EthOrderDataRaribleV2DataV3AtType$outboundSchema` instead. */
  export const outboundSchema =
    EthOrderDataRaribleV2DataV3AtType$outboundSchema;
}

/** @internal */
export const EthOrderDataRaribleV2DataV3$inboundSchema: z.ZodType<
  EthOrderDataRaribleV2DataV3,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": EthOrderDataRaribleV2DataV3AtType$inboundSchema,
  payouts: z.array(Payout$inboundSchema),
  originFees: z.array(Payout$inboundSchema),
  isMakeFill: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type EthOrderDataRaribleV2DataV3$Outbound = {
  "@type": string;
  payouts: Array<Payout$Outbound>;
  originFees: Array<Payout$Outbound>;
  isMakeFill: boolean;
};

/** @internal */
export const EthOrderDataRaribleV2DataV3$outboundSchema: z.ZodType<
  EthOrderDataRaribleV2DataV3$Outbound,
  z.ZodTypeDef,
  EthOrderDataRaribleV2DataV3
> = z.object({
  atType: EthOrderDataRaribleV2DataV3AtType$outboundSchema,
  payouts: z.array(Payout$outboundSchema),
  originFees: z.array(Payout$outboundSchema),
  isMakeFill: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthOrderDataRaribleV2DataV3$ {
  /** @deprecated use `EthOrderDataRaribleV2DataV3$inboundSchema` instead. */
  export const inboundSchema = EthOrderDataRaribleV2DataV3$inboundSchema;
  /** @deprecated use `EthOrderDataRaribleV2DataV3$outboundSchema` instead. */
  export const outboundSchema = EthOrderDataRaribleV2DataV3$outboundSchema;
  /** @deprecated use `EthOrderDataRaribleV2DataV3$Outbound` instead. */
  export type Outbound = EthOrderDataRaribleV2DataV3$Outbound;
}

export function ethOrderDataRaribleV2DataV3ToJSON(
  ethOrderDataRaribleV2DataV3: EthOrderDataRaribleV2DataV3,
): string {
  return JSON.stringify(
    EthOrderDataRaribleV2DataV3$outboundSchema.parse(
      ethOrderDataRaribleV2DataV3,
    ),
  );
}

export function ethOrderDataRaribleV2DataV3FromJSON(
  jsonString: string,
): SafeParseResult<EthOrderDataRaribleV2DataV3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EthOrderDataRaribleV2DataV3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EthOrderDataRaribleV2DataV3' from JSON`,
  );
}
