/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  EthSeaportConsideration,
  EthSeaportConsideration$inboundSchema,
  EthSeaportConsideration$Outbound,
  EthSeaportConsideration$outboundSchema,
} from "./ethseaportconsideration.js";
import {
  EthSeaportOffer,
  EthSeaportOffer$inboundSchema,
  EthSeaportOffer$Outbound,
  EthSeaportOffer$outboundSchema,
} from "./ethseaportoffer.js";
import {
  EthSeaportOrderType,
  EthSeaportOrderType$inboundSchema,
  EthSeaportOrderType$outboundSchema,
} from "./ethseaportordertype.js";

export const EthOrderSeaportDataV1AtType = {
  EthBasicSeaportDataV1: "ETH_BASIC_SEAPORT_DATA_V1",
} as const;
export type EthOrderSeaportDataV1AtType = ClosedEnum<
  typeof EthOrderSeaportDataV1AtType
>;

export type EthOrderBasicSeaportDataV1 = {
  atType: EthOrderSeaportDataV1AtType;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  protocol: string;
  orderType: EthSeaportOrderType;
  offer: Array<EthSeaportOffer>;
  consideration: Array<EthSeaportConsideration>;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  zone: string;
  zoneHash: string;
  conduitKey: string;
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  counter?: number | undefined;
  nonce?: string | undefined;
};

export type EthOrderSeaportDataV1 = EthOrderBasicSeaportDataV1;

/** @internal */
export const EthOrderSeaportDataV1AtType$inboundSchema: z.ZodNativeEnum<
  typeof EthOrderSeaportDataV1AtType
> = z.nativeEnum(EthOrderSeaportDataV1AtType);

/** @internal */
export const EthOrderSeaportDataV1AtType$outboundSchema: z.ZodNativeEnum<
  typeof EthOrderSeaportDataV1AtType
> = EthOrderSeaportDataV1AtType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthOrderSeaportDataV1AtType$ {
  /** @deprecated use `EthOrderSeaportDataV1AtType$inboundSchema` instead. */
  export const inboundSchema = EthOrderSeaportDataV1AtType$inboundSchema;
  /** @deprecated use `EthOrderSeaportDataV1AtType$outboundSchema` instead. */
  export const outboundSchema = EthOrderSeaportDataV1AtType$outboundSchema;
}

/** @internal */
export const EthOrderBasicSeaportDataV1$inboundSchema: z.ZodType<
  EthOrderBasicSeaportDataV1,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": EthOrderSeaportDataV1AtType$inboundSchema,
  protocol: z.string(),
  orderType: EthSeaportOrderType$inboundSchema,
  offer: z.array(EthSeaportOffer$inboundSchema),
  consideration: z.array(EthSeaportConsideration$inboundSchema),
  zone: z.string(),
  zoneHash: z.string(),
  conduitKey: z.string(),
  counter: z.number().int().optional(),
  nonce: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type EthOrderBasicSeaportDataV1$Outbound = {
  "@type": string;
  protocol: string;
  orderType: string;
  offer: Array<EthSeaportOffer$Outbound>;
  consideration: Array<EthSeaportConsideration$Outbound>;
  zone: string;
  zoneHash: string;
  conduitKey: string;
  counter?: number | undefined;
  nonce?: string | undefined;
};

/** @internal */
export const EthOrderBasicSeaportDataV1$outboundSchema: z.ZodType<
  EthOrderBasicSeaportDataV1$Outbound,
  z.ZodTypeDef,
  EthOrderBasicSeaportDataV1
> = z.object({
  atType: EthOrderSeaportDataV1AtType$outboundSchema,
  protocol: z.string(),
  orderType: EthSeaportOrderType$outboundSchema,
  offer: z.array(EthSeaportOffer$outboundSchema),
  consideration: z.array(EthSeaportConsideration$outboundSchema),
  zone: z.string(),
  zoneHash: z.string(),
  conduitKey: z.string(),
  counter: z.number().int().optional(),
  nonce: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthOrderBasicSeaportDataV1$ {
  /** @deprecated use `EthOrderBasicSeaportDataV1$inboundSchema` instead. */
  export const inboundSchema = EthOrderBasicSeaportDataV1$inboundSchema;
  /** @deprecated use `EthOrderBasicSeaportDataV1$outboundSchema` instead. */
  export const outboundSchema = EthOrderBasicSeaportDataV1$outboundSchema;
  /** @deprecated use `EthOrderBasicSeaportDataV1$Outbound` instead. */
  export type Outbound = EthOrderBasicSeaportDataV1$Outbound;
}

export function ethOrderBasicSeaportDataV1ToJSON(
  ethOrderBasicSeaportDataV1: EthOrderBasicSeaportDataV1,
): string {
  return JSON.stringify(
    EthOrderBasicSeaportDataV1$outboundSchema.parse(ethOrderBasicSeaportDataV1),
  );
}

export function ethOrderBasicSeaportDataV1FromJSON(
  jsonString: string,
): SafeParseResult<EthOrderBasicSeaportDataV1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EthOrderBasicSeaportDataV1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EthOrderBasicSeaportDataV1' from JSON`,
  );
}

/** @internal */
export const EthOrderSeaportDataV1$inboundSchema: z.ZodType<
  EthOrderSeaportDataV1,
  z.ZodTypeDef,
  unknown
> = z.lazy(() => EthOrderBasicSeaportDataV1$inboundSchema);

/** @internal */
export type EthOrderSeaportDataV1$Outbound =
  EthOrderBasicSeaportDataV1$Outbound;

/** @internal */
export const EthOrderSeaportDataV1$outboundSchema: z.ZodType<
  EthOrderSeaportDataV1$Outbound,
  z.ZodTypeDef,
  EthOrderSeaportDataV1
> = z.lazy(() => EthOrderBasicSeaportDataV1$outboundSchema);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthOrderSeaportDataV1$ {
  /** @deprecated use `EthOrderSeaportDataV1$inboundSchema` instead. */
  export const inboundSchema = EthOrderSeaportDataV1$inboundSchema;
  /** @deprecated use `EthOrderSeaportDataV1$outboundSchema` instead. */
  export const outboundSchema = EthOrderSeaportDataV1$outboundSchema;
  /** @deprecated use `EthOrderSeaportDataV1$Outbound` instead. */
  export type Outbound = EthOrderSeaportDataV1$Outbound;
}

export function ethOrderSeaportDataV1ToJSON(
  ethOrderSeaportDataV1: EthOrderSeaportDataV1,
): string {
  return JSON.stringify(
    EthOrderSeaportDataV1$outboundSchema.parse(ethOrderSeaportDataV1),
  );
}

export function ethOrderSeaportDataV1FromJSON(
  jsonString: string,
): SafeParseResult<EthOrderSeaportDataV1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EthOrderSeaportDataV1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EthOrderSeaportDataV1' from JSON`,
  );
}
