/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Payout,
  Payout$inboundSchema,
  Payout$Outbound,
  Payout$outboundSchema,
} from "./payout.js";

export const EthOrderDataRaribleV2DataV2AtType = {
  EthRaribleV22: "ETH_RARIBLE_V2_2",
} as const;
export type EthOrderDataRaribleV2DataV2AtType = ClosedEnum<
  typeof EthOrderDataRaribleV2DataV2AtType
>;

export type EthOrderDataRaribleV2DataV2 = {
  atType: EthOrderDataRaribleV2DataV2AtType;
  payouts: Array<Payout>;
  originFees: Array<Payout>;
  /**
   * If true, the 'fill' part of the order applies to the 'make' side, otherwise to the 'take' side
   */
  isMakeFill: boolean;
};

/** @internal */
export const EthOrderDataRaribleV2DataV2AtType$inboundSchema: z.ZodNativeEnum<
  typeof EthOrderDataRaribleV2DataV2AtType
> = z.nativeEnum(EthOrderDataRaribleV2DataV2AtType);

/** @internal */
export const EthOrderDataRaribleV2DataV2AtType$outboundSchema: z.ZodNativeEnum<
  typeof EthOrderDataRaribleV2DataV2AtType
> = EthOrderDataRaribleV2DataV2AtType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthOrderDataRaribleV2DataV2AtType$ {
  /** @deprecated use `EthOrderDataRaribleV2DataV2AtType$inboundSchema` instead. */
  export const inboundSchema = EthOrderDataRaribleV2DataV2AtType$inboundSchema;
  /** @deprecated use `EthOrderDataRaribleV2DataV2AtType$outboundSchema` instead. */
  export const outboundSchema =
    EthOrderDataRaribleV2DataV2AtType$outboundSchema;
}

/** @internal */
export const EthOrderDataRaribleV2DataV2$inboundSchema: z.ZodType<
  EthOrderDataRaribleV2DataV2,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": EthOrderDataRaribleV2DataV2AtType$inboundSchema,
  payouts: z.array(Payout$inboundSchema),
  originFees: z.array(Payout$inboundSchema),
  isMakeFill: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type EthOrderDataRaribleV2DataV2$Outbound = {
  "@type": string;
  payouts: Array<Payout$Outbound>;
  originFees: Array<Payout$Outbound>;
  isMakeFill: boolean;
};

/** @internal */
export const EthOrderDataRaribleV2DataV2$outboundSchema: z.ZodType<
  EthOrderDataRaribleV2DataV2$Outbound,
  z.ZodTypeDef,
  EthOrderDataRaribleV2DataV2
> = z.object({
  atType: EthOrderDataRaribleV2DataV2AtType$outboundSchema,
  payouts: z.array(Payout$outboundSchema),
  originFees: z.array(Payout$outboundSchema),
  isMakeFill: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthOrderDataRaribleV2DataV2$ {
  /** @deprecated use `EthOrderDataRaribleV2DataV2$inboundSchema` instead. */
  export const inboundSchema = EthOrderDataRaribleV2DataV2$inboundSchema;
  /** @deprecated use `EthOrderDataRaribleV2DataV2$outboundSchema` instead. */
  export const outboundSchema = EthOrderDataRaribleV2DataV2$outboundSchema;
  /** @deprecated use `EthOrderDataRaribleV2DataV2$Outbound` instead. */
  export type Outbound = EthOrderDataRaribleV2DataV2$Outbound;
}

export function ethOrderDataRaribleV2DataV2ToJSON(
  ethOrderDataRaribleV2DataV2: EthOrderDataRaribleV2DataV2,
): string {
  return JSON.stringify(
    EthOrderDataRaribleV2DataV2$outboundSchema.parse(
      ethOrderDataRaribleV2DataV2,
    ),
  );
}

export function ethOrderDataRaribleV2DataV2FromJSON(
  jsonString: string,
): SafeParseResult<EthOrderDataRaribleV2DataV2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EthOrderDataRaribleV2DataV2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EthOrderDataRaribleV2DataV2' from JSON`,
  );
}
