/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const EthOrderCryptoPunksDataAtType = {
  EthCryptoPunks: "ETH_CRYPTO_PUNKS",
} as const;
export type EthOrderCryptoPunksDataAtType = ClosedEnum<
  typeof EthOrderCryptoPunksDataAtType
>;

export type EthOrderCryptoPunksData = {
  atType: EthOrderCryptoPunksDataAtType;
  stub?: string | undefined;
};

/** @internal */
export const EthOrderCryptoPunksDataAtType$inboundSchema: z.ZodNativeEnum<
  typeof EthOrderCryptoPunksDataAtType
> = z.nativeEnum(EthOrderCryptoPunksDataAtType);

/** @internal */
export const EthOrderCryptoPunksDataAtType$outboundSchema: z.ZodNativeEnum<
  typeof EthOrderCryptoPunksDataAtType
> = EthOrderCryptoPunksDataAtType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthOrderCryptoPunksDataAtType$ {
  /** @deprecated use `EthOrderCryptoPunksDataAtType$inboundSchema` instead. */
  export const inboundSchema = EthOrderCryptoPunksDataAtType$inboundSchema;
  /** @deprecated use `EthOrderCryptoPunksDataAtType$outboundSchema` instead. */
  export const outboundSchema = EthOrderCryptoPunksDataAtType$outboundSchema;
}

/** @internal */
export const EthOrderCryptoPunksData$inboundSchema: z.ZodType<
  EthOrderCryptoPunksData,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": EthOrderCryptoPunksDataAtType$inboundSchema,
  stub: z.string().default("STUB"),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type EthOrderCryptoPunksData$Outbound = {
  "@type": string;
  stub: string;
};

/** @internal */
export const EthOrderCryptoPunksData$outboundSchema: z.ZodType<
  EthOrderCryptoPunksData$Outbound,
  z.ZodTypeDef,
  EthOrderCryptoPunksData
> = z.object({
  atType: EthOrderCryptoPunksDataAtType$outboundSchema,
  stub: z.string().default("STUB"),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthOrderCryptoPunksData$ {
  /** @deprecated use `EthOrderCryptoPunksData$inboundSchema` instead. */
  export const inboundSchema = EthOrderCryptoPunksData$inboundSchema;
  /** @deprecated use `EthOrderCryptoPunksData$outboundSchema` instead. */
  export const outboundSchema = EthOrderCryptoPunksData$outboundSchema;
  /** @deprecated use `EthOrderCryptoPunksData$Outbound` instead. */
  export type Outbound = EthOrderCryptoPunksData$Outbound;
}

export function ethOrderCryptoPunksDataToJSON(
  ethOrderCryptoPunksData: EthOrderCryptoPunksData,
): string {
  return JSON.stringify(
    EthOrderCryptoPunksData$outboundSchema.parse(ethOrderCryptoPunksData),
  );
}

export function ethOrderCryptoPunksDataFromJSON(
  jsonString: string,
): SafeParseResult<EthOrderCryptoPunksData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EthOrderCryptoPunksData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EthOrderCryptoPunksData' from JSON`,
  );
}
