/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  EthSeaportItemType,
  EthSeaportItemType$inboundSchema,
  EthSeaportItemType$outboundSchema,
} from "./ethseaportitemtype.js";

export type EthSeaportConsideration = {
  itemType: EthSeaportItemType;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  token: string;
  identifierOrCriteria: string;
  startAmount: string;
  endAmount: string;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  recipient: string;
};

/** @internal */
export const EthSeaportConsideration$inboundSchema: z.ZodType<
  EthSeaportConsideration,
  z.ZodTypeDef,
  unknown
> = z.object({
  itemType: EthSeaportItemType$inboundSchema,
  token: z.string(),
  identifierOrCriteria: z.string(),
  startAmount: z.string(),
  endAmount: z.string(),
  recipient: z.string(),
});

/** @internal */
export type EthSeaportConsideration$Outbound = {
  itemType: string;
  token: string;
  identifierOrCriteria: string;
  startAmount: string;
  endAmount: string;
  recipient: string;
};

/** @internal */
export const EthSeaportConsideration$outboundSchema: z.ZodType<
  EthSeaportConsideration$Outbound,
  z.ZodTypeDef,
  EthSeaportConsideration
> = z.object({
  itemType: EthSeaportItemType$outboundSchema,
  token: z.string(),
  identifierOrCriteria: z.string(),
  startAmount: z.string(),
  endAmount: z.string(),
  recipient: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthSeaportConsideration$ {
  /** @deprecated use `EthSeaportConsideration$inboundSchema` instead. */
  export const inboundSchema = EthSeaportConsideration$inboundSchema;
  /** @deprecated use `EthSeaportConsideration$outboundSchema` instead. */
  export const outboundSchema = EthSeaportConsideration$outboundSchema;
  /** @deprecated use `EthSeaportConsideration$Outbound` instead. */
  export type Outbound = EthSeaportConsideration$Outbound;
}

export function ethSeaportConsiderationToJSON(
  ethSeaportConsideration: EthSeaportConsideration,
): string {
  return JSON.stringify(
    EthSeaportConsideration$outboundSchema.parse(ethSeaportConsideration),
  );
}

export function ethSeaportConsiderationFromJSON(
  jsonString: string,
): SafeParseResult<EthSeaportConsideration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EthSeaportConsideration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EthSeaportConsideration' from JSON`,
  );
}
