/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const EthSeaportItemType = {
  Native: "NATIVE",
  Erc20: "ERC20",
  Erc721: "ERC721",
  Erc1155: "ERC1155",
  Erc721WithCriteria: "ERC721_WITH_CRITERIA",
  Erc1155WithCriteria: "ERC1155_WITH_CRITERIA",
} as const;
export type EthSeaportItemType = ClosedEnum<typeof EthSeaportItemType>;

/** @internal */
export const EthSeaportItemType$inboundSchema: z.ZodNativeEnum<
  typeof EthSeaportItemType
> = z.nativeEnum(EthSeaportItemType);

/** @internal */
export const EthSeaportItemType$outboundSchema: z.ZodNativeEnum<
  typeof EthSeaportItemType
> = EthSeaportItemType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthSeaportItemType$ {
  /** @deprecated use `EthSeaportItemType$inboundSchema` instead. */
  export const inboundSchema = EthSeaportItemType$inboundSchema;
  /** @deprecated use `EthSeaportItemType$outboundSchema` instead. */
  export const outboundSchema = EthSeaportItemType$outboundSchema;
}
