/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  EthSeaportItemType,
  EthSeaportItemType$inboundSchema,
  EthSeaportItemType$outboundSchema,
} from "./ethseaportitemtype.js";

export type EthSeaportOffer = {
  itemType: EthSeaportItemType;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  token: string;
  identifierOrCriteria: string;
  startAmount: string;
  endAmount: string;
};

/** @internal */
export const EthSeaportOffer$inboundSchema: z.ZodType<
  EthSeaportOffer,
  z.ZodTypeDef,
  unknown
> = z.object({
  itemType: EthSeaportItemType$inboundSchema,
  token: z.string(),
  identifierOrCriteria: z.string(),
  startAmount: z.string(),
  endAmount: z.string(),
});

/** @internal */
export type EthSeaportOffer$Outbound = {
  itemType: string;
  token: string;
  identifierOrCriteria: string;
  startAmount: string;
  endAmount: string;
};

/** @internal */
export const EthSeaportOffer$outboundSchema: z.ZodType<
  EthSeaportOffer$Outbound,
  z.ZodTypeDef,
  EthSeaportOffer
> = z.object({
  itemType: EthSeaportItemType$outboundSchema,
  token: z.string(),
  identifierOrCriteria: z.string(),
  startAmount: z.string(),
  endAmount: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthSeaportOffer$ {
  /** @deprecated use `EthSeaportOffer$inboundSchema` instead. */
  export const inboundSchema = EthSeaportOffer$inboundSchema;
  /** @deprecated use `EthSeaportOffer$outboundSchema` instead. */
  export const outboundSchema = EthSeaportOffer$outboundSchema;
  /** @deprecated use `EthSeaportOffer$Outbound` instead. */
  export type Outbound = EthSeaportOffer$Outbound;
}

export function ethSeaportOfferToJSON(
  ethSeaportOffer: EthSeaportOffer,
): string {
  return JSON.stringify(EthSeaportOffer$outboundSchema.parse(ethSeaportOffer));
}

export function ethSeaportOfferFromJSON(
  jsonString: string,
): SafeParseResult<EthSeaportOffer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EthSeaportOffer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EthSeaportOffer' from JSON`,
  );
}
