/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Trait property parameters with additional features
 */
export type ExtendedTraitProperty = {
  key: string;
  value: string;
  /**
   * Rarity percent
   */
  rarity: number;
};

/** @internal */
export const ExtendedTraitProperty$inboundSchema: z.ZodType<
  ExtendedTraitProperty,
  z.ZodTypeDef,
  unknown
> = z.object({
  key: z.string(),
  value: z.string(),
  rarity: z.number(),
});

/** @internal */
export type ExtendedTraitProperty$Outbound = {
  key: string;
  value: string;
  rarity: number;
};

/** @internal */
export const ExtendedTraitProperty$outboundSchema: z.ZodType<
  ExtendedTraitProperty$Outbound,
  z.ZodTypeDef,
  ExtendedTraitProperty
> = z.object({
  key: z.string(),
  value: z.string(),
  rarity: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExtendedTraitProperty$ {
  /** @deprecated use `ExtendedTraitProperty$inboundSchema` instead. */
  export const inboundSchema = ExtendedTraitProperty$inboundSchema;
  /** @deprecated use `ExtendedTraitProperty$outboundSchema` instead. */
  export const outboundSchema = ExtendedTraitProperty$outboundSchema;
  /** @deprecated use `ExtendedTraitProperty$Outbound` instead. */
  export type Outbound = ExtendedTraitProperty$Outbound;
}

export function extendedTraitPropertyToJSON(
  extendedTraitProperty: ExtendedTraitProperty,
): string {
  return JSON.stringify(
    ExtendedTraitProperty$outboundSchema.parse(extendedTraitProperty),
  );
}

export function extendedTraitPropertyFromJSON(
  jsonString: string,
): SafeParseResult<ExtendedTraitProperty, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExtendedTraitProperty$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExtendedTraitProperty' from JSON`,
  );
}
