/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Payout,
  Payout$inboundSchema,
  Payout$Outbound,
  Payout$outboundSchema,
} from "./payout.js";

export const FlowOrderDataV1AtType = {
  FlowRaribleV1: "FLOW_RARIBLE_V1",
} as const;
export type FlowOrderDataV1AtType = ClosedEnum<typeof FlowOrderDataV1AtType>;

export type FlowOrderDataV1 = {
  atType: FlowOrderDataV1AtType;
  payouts: Array<Payout>;
  originFees: Array<Payout>;
};

/** @internal */
export const FlowOrderDataV1AtType$inboundSchema: z.ZodNativeEnum<
  typeof FlowOrderDataV1AtType
> = z.nativeEnum(FlowOrderDataV1AtType);

/** @internal */
export const FlowOrderDataV1AtType$outboundSchema: z.ZodNativeEnum<
  typeof FlowOrderDataV1AtType
> = FlowOrderDataV1AtType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FlowOrderDataV1AtType$ {
  /** @deprecated use `FlowOrderDataV1AtType$inboundSchema` instead. */
  export const inboundSchema = FlowOrderDataV1AtType$inboundSchema;
  /** @deprecated use `FlowOrderDataV1AtType$outboundSchema` instead. */
  export const outboundSchema = FlowOrderDataV1AtType$outboundSchema;
}

/** @internal */
export const FlowOrderDataV1$inboundSchema: z.ZodType<
  FlowOrderDataV1,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": FlowOrderDataV1AtType$inboundSchema,
  payouts: z.array(Payout$inboundSchema),
  originFees: z.array(Payout$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type FlowOrderDataV1$Outbound = {
  "@type": string;
  payouts: Array<Payout$Outbound>;
  originFees: Array<Payout$Outbound>;
};

/** @internal */
export const FlowOrderDataV1$outboundSchema: z.ZodType<
  FlowOrderDataV1$Outbound,
  z.ZodTypeDef,
  FlowOrderDataV1
> = z.object({
  atType: FlowOrderDataV1AtType$outboundSchema,
  payouts: z.array(Payout$outboundSchema),
  originFees: z.array(Payout$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FlowOrderDataV1$ {
  /** @deprecated use `FlowOrderDataV1$inboundSchema` instead. */
  export const inboundSchema = FlowOrderDataV1$inboundSchema;
  /** @deprecated use `FlowOrderDataV1$outboundSchema` instead. */
  export const outboundSchema = FlowOrderDataV1$outboundSchema;
  /** @deprecated use `FlowOrderDataV1$Outbound` instead. */
  export type Outbound = FlowOrderDataV1$Outbound;
}

export function flowOrderDataV1ToJSON(
  flowOrderDataV1: FlowOrderDataV1,
): string {
  return JSON.stringify(FlowOrderDataV1$outboundSchema.parse(flowOrderDataV1));
}

export function flowOrderDataV1FromJSON(
  jsonString: string,
): SafeParseResult<FlowOrderDataV1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FlowOrderDataV1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FlowOrderDataV1' from JSON`,
  );
}
