/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const FlowAssetTypeNftAtType = {
  FlowNft: "FLOW_NFT",
} as const;
export type FlowAssetTypeNftAtType = ClosedEnum<typeof FlowAssetTypeNftAtType>;

export type FlowAssetTypeNft = {
  atType: FlowAssetTypeNftAtType;
  /**
   * Blockchain contract address in Union format `ETHEREUM:${token}`
   */
  contract: string;
  /**
   * Collection id
   */
  collection?: string | undefined;
  tokenId: string;
};

/** @internal */
export const FlowAssetTypeNftAtType$inboundSchema: z.ZodNativeEnum<
  typeof FlowAssetTypeNftAtType
> = z.nativeEnum(FlowAssetTypeNftAtType);

/** @internal */
export const FlowAssetTypeNftAtType$outboundSchema: z.ZodNativeEnum<
  typeof FlowAssetTypeNftAtType
> = FlowAssetTypeNftAtType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FlowAssetTypeNftAtType$ {
  /** @deprecated use `FlowAssetTypeNftAtType$inboundSchema` instead. */
  export const inboundSchema = FlowAssetTypeNftAtType$inboundSchema;
  /** @deprecated use `FlowAssetTypeNftAtType$outboundSchema` instead. */
  export const outboundSchema = FlowAssetTypeNftAtType$outboundSchema;
}

/** @internal */
export const FlowAssetTypeNft$inboundSchema: z.ZodType<
  FlowAssetTypeNft,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": FlowAssetTypeNftAtType$inboundSchema,
  contract: z.string(),
  collection: z.string().optional(),
  tokenId: z.string(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type FlowAssetTypeNft$Outbound = {
  "@type": string;
  contract: string;
  collection?: string | undefined;
  tokenId: string;
};

/** @internal */
export const FlowAssetTypeNft$outboundSchema: z.ZodType<
  FlowAssetTypeNft$Outbound,
  z.ZodTypeDef,
  FlowAssetTypeNft
> = z.object({
  atType: FlowAssetTypeNftAtType$outboundSchema,
  contract: z.string(),
  collection: z.string().optional(),
  tokenId: z.string(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FlowAssetTypeNft$ {
  /** @deprecated use `FlowAssetTypeNft$inboundSchema` instead. */
  export const inboundSchema = FlowAssetTypeNft$inboundSchema;
  /** @deprecated use `FlowAssetTypeNft$outboundSchema` instead. */
  export const outboundSchema = FlowAssetTypeNft$outboundSchema;
  /** @deprecated use `FlowAssetTypeNft$Outbound` instead. */
  export type Outbound = FlowAssetTypeNft$Outbound;
}

export function flowAssetTypeNftToJSON(
  flowAssetTypeNft: FlowAssetTypeNft,
): string {
  return JSON.stringify(
    FlowAssetTypeNft$outboundSchema.parse(flowAssetTypeNft),
  );
}

export function flowAssetTypeNftFromJSON(
  jsonString: string,
): SafeParseResult<FlowAssetTypeNft, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FlowAssetTypeNft$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FlowAssetTypeNft' from JSON`,
  );
}
