/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const Field = {
  Name: "NAME",
  Description: "DESCRIPTION",
  TraitValue: "TRAIT_VALUE",
} as const;
export type Field = ClosedEnum<typeof Field>;

export type ItemSearchFullText = {
  text: string;
  fields?: Array<Field> | undefined;
};

/** @internal */
export const Field$inboundSchema: z.ZodNativeEnum<typeof Field> = z.nativeEnum(
  Field,
);

/** @internal */
export const Field$outboundSchema: z.ZodNativeEnum<typeof Field> =
  Field$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Field$ {
  /** @deprecated use `Field$inboundSchema` instead. */
  export const inboundSchema = Field$inboundSchema;
  /** @deprecated use `Field$outboundSchema` instead. */
  export const outboundSchema = Field$outboundSchema;
}

/** @internal */
export const ItemSearchFullText$inboundSchema: z.ZodType<
  ItemSearchFullText,
  z.ZodTypeDef,
  unknown
> = z.object({
  text: z.string(),
  fields: z.array(Field$inboundSchema).optional(),
});

/** @internal */
export type ItemSearchFullText$Outbound = {
  text: string;
  fields?: Array<string> | undefined;
};

/** @internal */
export const ItemSearchFullText$outboundSchema: z.ZodType<
  ItemSearchFullText$Outbound,
  z.ZodTypeDef,
  ItemSearchFullText
> = z.object({
  text: z.string(),
  fields: z.array(Field$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ItemSearchFullText$ {
  /** @deprecated use `ItemSearchFullText$inboundSchema` instead. */
  export const inboundSchema = ItemSearchFullText$inboundSchema;
  /** @deprecated use `ItemSearchFullText$outboundSchema` instead. */
  export const outboundSchema = ItemSearchFullText$outboundSchema;
  /** @deprecated use `ItemSearchFullText$Outbound` instead. */
  export type Outbound = ItemSearchFullText$Outbound;
}

export function itemSearchFullTextToJSON(
  itemSearchFullText: ItemSearchFullText,
): string {
  return JSON.stringify(
    ItemSearchFullText$outboundSchema.parse(itemSearchFullText),
  );
}

export function itemSearchFullTextFromJSON(
  jsonString: string,
): SafeParseResult<ItemSearchFullText, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ItemSearchFullText$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ItemSearchFullText' from JSON`,
  );
}
