/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ItemsSearchFilter,
  ItemsSearchFilter$inboundSchema,
  ItemsSearchFilter$Outbound,
  ItemsSearchFilter$outboundSchema,
} from "./itemssearchfilter.js";
import {
  ItemsSearchSort,
  ItemsSearchSort$inboundSchema,
  ItemsSearchSort$outboundSchema,
} from "./itemssearchsort.js";
import {
  TraitSort,
  TraitSort$inboundSchema,
  TraitSort$Outbound,
  TraitSort$outboundSchema,
} from "./traitsort.js";

/**
 * Complex search request for items
 */
export type ItemsSearchRequest = {
  /**
   * Number of entities returned
   */
  size?: number | undefined;
  /**
   * Continuation token to paginate items search result
   */
  continuation?: string | undefined;
  /**
   * Filter for items search query
   */
  filter: ItemsSearchFilter;
  /**
   * Used when the search sort is set as TRAIT
   */
  traitSort?: TraitSort | undefined;
  sort?: ItemsSearchSort | undefined;
};

/** @internal */
export const ItemsSearchRequest$inboundSchema: z.ZodType<
  ItemsSearchRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  size: z.number().int().default(50),
  continuation: z.string().optional(),
  filter: ItemsSearchFilter$inboundSchema,
  traitSort: TraitSort$inboundSchema.optional(),
  sort: ItemsSearchSort$inboundSchema.optional(),
});

/** @internal */
export type ItemsSearchRequest$Outbound = {
  size: number;
  continuation?: string | undefined;
  filter: ItemsSearchFilter$Outbound;
  traitSort?: TraitSort$Outbound | undefined;
  sort?: string | undefined;
};

/** @internal */
export const ItemsSearchRequest$outboundSchema: z.ZodType<
  ItemsSearchRequest$Outbound,
  z.ZodTypeDef,
  ItemsSearchRequest
> = z.object({
  size: z.number().int().default(50),
  continuation: z.string().optional(),
  filter: ItemsSearchFilter$outboundSchema,
  traitSort: TraitSort$outboundSchema.optional(),
  sort: ItemsSearchSort$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ItemsSearchRequest$ {
  /** @deprecated use `ItemsSearchRequest$inboundSchema` instead. */
  export const inboundSchema = ItemsSearchRequest$inboundSchema;
  /** @deprecated use `ItemsSearchRequest$outboundSchema` instead. */
  export const outboundSchema = ItemsSearchRequest$outboundSchema;
  /** @deprecated use `ItemsSearchRequest$Outbound` instead. */
  export type Outbound = ItemsSearchRequest$Outbound;
}

export function itemsSearchRequestToJSON(
  itemsSearchRequest: ItemsSearchRequest,
): string {
  return JSON.stringify(
    ItemsSearchRequest$outboundSchema.parse(itemsSearchRequest),
  );
}

export function itemsSearchRequestFromJSON(
  jsonString: string,
): SafeParseResult<ItemsSearchRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ItemsSearchRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ItemsSearchRequest' from JSON`,
  );
}
