/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Royalty,
  Royalty$inboundSchema,
  Royalty$Outbound,
  Royalty$outboundSchema,
} from "./royalty.js";

export const ItemHistoryAtTypeTransfer = {
  Transfer: "TRANSFER",
} as const;
export type ItemHistoryAtTypeTransfer = ClosedEnum<
  typeof ItemHistoryAtTypeTransfer
>;

export type ItemHistoryItemTransfer = {
  atType: ItemHistoryAtTypeTransfer;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  from: string;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  owner: string;
  /**
   * Blockchain contract address in Union format `ETHEREUM:${token}`
   */
  contract: string;
  tokenId: string;
  value: string;
  date: Date;
};

export const AtTypeRoyalty = {
  Royalty: "ROYALTY",
} as const;
export type AtTypeRoyalty = ClosedEnum<typeof AtTypeRoyalty>;

export type ItemRoyalty = {
  atType: AtTypeRoyalty;
  royalties: Array<Royalty>;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  owner?: string | undefined;
  /**
   * Blockchain contract address in Union format `ETHEREUM:${token}`
   */
  contract: string;
  tokenId: string;
  value?: string | undefined;
  date: Date;
};

/**
 * History of item
 */
export type ItemHistory = ItemRoyalty | ItemHistoryItemTransfer;

/** @internal */
export const ItemHistoryAtTypeTransfer$inboundSchema: z.ZodNativeEnum<
  typeof ItemHistoryAtTypeTransfer
> = z.nativeEnum(ItemHistoryAtTypeTransfer);

/** @internal */
export const ItemHistoryAtTypeTransfer$outboundSchema: z.ZodNativeEnum<
  typeof ItemHistoryAtTypeTransfer
> = ItemHistoryAtTypeTransfer$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ItemHistoryAtTypeTransfer$ {
  /** @deprecated use `ItemHistoryAtTypeTransfer$inboundSchema` instead. */
  export const inboundSchema = ItemHistoryAtTypeTransfer$inboundSchema;
  /** @deprecated use `ItemHistoryAtTypeTransfer$outboundSchema` instead. */
  export const outboundSchema = ItemHistoryAtTypeTransfer$outboundSchema;
}

/** @internal */
export const ItemHistoryItemTransfer$inboundSchema: z.ZodType<
  ItemHistoryItemTransfer,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": ItemHistoryAtTypeTransfer$inboundSchema,
  from: z.string(),
  owner: z.string(),
  contract: z.string(),
  tokenId: z.string(),
  value: z.string(),
  date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type ItemHistoryItemTransfer$Outbound = {
  "@type": string;
  from: string;
  owner: string;
  contract: string;
  tokenId: string;
  value: string;
  date: string;
};

/** @internal */
export const ItemHistoryItemTransfer$outboundSchema: z.ZodType<
  ItemHistoryItemTransfer$Outbound,
  z.ZodTypeDef,
  ItemHistoryItemTransfer
> = z.object({
  atType: ItemHistoryAtTypeTransfer$outboundSchema,
  from: z.string(),
  owner: z.string(),
  contract: z.string(),
  tokenId: z.string(),
  value: z.string(),
  date: z.date().transform(v => v.toISOString()),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ItemHistoryItemTransfer$ {
  /** @deprecated use `ItemHistoryItemTransfer$inboundSchema` instead. */
  export const inboundSchema = ItemHistoryItemTransfer$inboundSchema;
  /** @deprecated use `ItemHistoryItemTransfer$outboundSchema` instead. */
  export const outboundSchema = ItemHistoryItemTransfer$outboundSchema;
  /** @deprecated use `ItemHistoryItemTransfer$Outbound` instead. */
  export type Outbound = ItemHistoryItemTransfer$Outbound;
}

export function itemHistoryItemTransferToJSON(
  itemHistoryItemTransfer: ItemHistoryItemTransfer,
): string {
  return JSON.stringify(
    ItemHistoryItemTransfer$outboundSchema.parse(itemHistoryItemTransfer),
  );
}

export function itemHistoryItemTransferFromJSON(
  jsonString: string,
): SafeParseResult<ItemHistoryItemTransfer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ItemHistoryItemTransfer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ItemHistoryItemTransfer' from JSON`,
  );
}

/** @internal */
export const AtTypeRoyalty$inboundSchema: z.ZodNativeEnum<
  typeof AtTypeRoyalty
> = z.nativeEnum(AtTypeRoyalty);

/** @internal */
export const AtTypeRoyalty$outboundSchema: z.ZodNativeEnum<
  typeof AtTypeRoyalty
> = AtTypeRoyalty$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AtTypeRoyalty$ {
  /** @deprecated use `AtTypeRoyalty$inboundSchema` instead. */
  export const inboundSchema = AtTypeRoyalty$inboundSchema;
  /** @deprecated use `AtTypeRoyalty$outboundSchema` instead. */
  export const outboundSchema = AtTypeRoyalty$outboundSchema;
}

/** @internal */
export const ItemRoyalty$inboundSchema: z.ZodType<
  ItemRoyalty,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": AtTypeRoyalty$inboundSchema,
  royalties: z.array(Royalty$inboundSchema),
  owner: z.string().optional(),
  contract: z.string(),
  tokenId: z.string(),
  value: z.string().optional(),
  date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type ItemRoyalty$Outbound = {
  "@type": string;
  royalties: Array<Royalty$Outbound>;
  owner?: string | undefined;
  contract: string;
  tokenId: string;
  value?: string | undefined;
  date: string;
};

/** @internal */
export const ItemRoyalty$outboundSchema: z.ZodType<
  ItemRoyalty$Outbound,
  z.ZodTypeDef,
  ItemRoyalty
> = z.object({
  atType: AtTypeRoyalty$outboundSchema,
  royalties: z.array(Royalty$outboundSchema),
  owner: z.string().optional(),
  contract: z.string(),
  tokenId: z.string(),
  value: z.string().optional(),
  date: z.date().transform(v => v.toISOString()),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ItemRoyalty$ {
  /** @deprecated use `ItemRoyalty$inboundSchema` instead. */
  export const inboundSchema = ItemRoyalty$inboundSchema;
  /** @deprecated use `ItemRoyalty$outboundSchema` instead. */
  export const outboundSchema = ItemRoyalty$outboundSchema;
  /** @deprecated use `ItemRoyalty$Outbound` instead. */
  export type Outbound = ItemRoyalty$Outbound;
}

export function itemRoyaltyToJSON(itemRoyalty: ItemRoyalty): string {
  return JSON.stringify(ItemRoyalty$outboundSchema.parse(itemRoyalty));
}

export function itemRoyaltyFromJSON(
  jsonString: string,
): SafeParseResult<ItemRoyalty, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ItemRoyalty$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ItemRoyalty' from JSON`,
  );
}

/** @internal */
export const ItemHistory$inboundSchema: z.ZodType<
  ItemHistory,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => ItemRoyalty$inboundSchema),
  z.lazy(() => ItemHistoryItemTransfer$inboundSchema),
]);

/** @internal */
export type ItemHistory$Outbound =
  | ItemRoyalty$Outbound
  | ItemHistoryItemTransfer$Outbound;

/** @internal */
export const ItemHistory$outboundSchema: z.ZodType<
  ItemHistory$Outbound,
  z.ZodTypeDef,
  ItemHistory
> = z.union([
  z.lazy(() => ItemRoyalty$outboundSchema),
  z.lazy(() => ItemHistoryItemTransfer$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ItemHistory$ {
  /** @deprecated use `ItemHistory$inboundSchema` instead. */
  export const inboundSchema = ItemHistory$inboundSchema;
  /** @deprecated use `ItemHistory$outboundSchema` instead. */
  export const outboundSchema = ItemHistory$outboundSchema;
  /** @deprecated use `ItemHistory$Outbound` instead. */
  export type Outbound = ItemHistory$Outbound;
}

export function itemHistoryToJSON(itemHistory: ItemHistory): string {
  return JSON.stringify(ItemHistory$outboundSchema.parse(itemHistory));
}

export function itemHistoryFromJSON(
  jsonString: string,
): SafeParseResult<ItemHistory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ItemHistory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ItemHistory' from JSON`,
  );
}
