/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Blockchain,
  Blockchain$inboundSchema,
  Blockchain$outboundSchema,
} from "./blockchain.js";
import {
  Creator,
  Creator$inboundSchema,
  Creator$Outbound,
  Creator$outboundSchema,
} from "./creator.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ItemCollection,
  ItemCollection$inboundSchema,
  ItemCollection$Outbound,
  ItemCollection$outboundSchema,
} from "./itemcollection.js";
import {
  ItemLastSale,
  ItemLastSale$inboundSchema,
  ItemLastSale$Outbound,
  ItemLastSale$outboundSchema,
} from "./itemlastsale.js";
import {
  ItemTransfer,
  ItemTransfer$inboundSchema,
  ItemTransfer$Outbound,
  ItemTransfer$outboundSchema,
} from "./itemtransfer.js";
import {
  Meta,
  Meta$inboundSchema,
  Meta$Outbound,
  Meta$outboundSchema,
} from "./meta.js";
import {
  Order,
  Order$inboundSchema,
  Order$Outbound,
  Order$outboundSchema,
} from "./order.js";
import {
  OriginOrders,
  OriginOrders$inboundSchema,
  OriginOrders$Outbound,
  OriginOrders$outboundSchema,
} from "./originorders.js";

export const ItemFeature = {
  NotForSale: "NOT_FOR_SALE",
} as const;
export type ItemFeature = ClosedEnum<typeof ItemFeature>;

export type Item = {
  /**
   * Item Id, has format `ETHEREUM:${token}:${tokenId}`
   */
  id: string;
  blockchain: Blockchain;
  /**
   * Collection id
   */
  collection?: string | undefined;
  /**
   * Blockchain contract address in Union format `ETHEREUM:${token}`
   */
  contract?: string | undefined;
  tokenId?: string | undefined;
  /**
   * Creators of the target item
   */
  creators: Array<Creator>;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  ownerIfSingle?: string | undefined;
  ownerChangeDate?: Date | undefined;
  lazySupply: string;
  /**
   * Pending information about the item
   */
  pending: Array<ItemTransfer>;
  /**
   * Date and time of the item minting
   */
  mintedAt: Date;
  /**
   * Filter condition to return only items that have been updated at this date
   */
  lastUpdatedAt: Date;
  supply: string;
  meta?: Meta | undefined;
  /**
   * Item was deleted or not
   */
  deleted: boolean;
  bestSellOrder?: Order | undefined;
  bestBidOrder?: Order | undefined;
  /**
   * Contains best bid order for each currency if exists
   */
  bestBidOrdersByCurrency?: Array<Order> | undefined;
  originOrders?: Array<OriginOrders> | undefined;
  totalStock?: string | undefined;
  /**
   * Total count of users selling this item ATM
   */
  sellers: number;
  lastSale?: ItemLastSale | undefined;
  self?: boolean | undefined;
  suspicious?: boolean | undefined;
  itemCollection?: ItemCollection | undefined;
  features?: Array<ItemFeature> | undefined;
  /**
   * Blockchain-specific information about this NFT item particular to that blockchain's data model
   */
  extra?: { [k: string]: string } | undefined;
  version?: number | undefined;
};

/** @internal */
export const ItemFeature$inboundSchema: z.ZodNativeEnum<typeof ItemFeature> = z
  .nativeEnum(ItemFeature);

/** @internal */
export const ItemFeature$outboundSchema: z.ZodNativeEnum<typeof ItemFeature> =
  ItemFeature$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ItemFeature$ {
  /** @deprecated use `ItemFeature$inboundSchema` instead. */
  export const inboundSchema = ItemFeature$inboundSchema;
  /** @deprecated use `ItemFeature$outboundSchema` instead. */
  export const outboundSchema = ItemFeature$outboundSchema;
}

/** @internal */
export const Item$inboundSchema: z.ZodType<Item, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string(),
    blockchain: Blockchain$inboundSchema,
    collection: z.string().optional(),
    contract: z.string().optional(),
    tokenId: z.string().optional(),
    creators: z.array(Creator$inboundSchema),
    ownerIfSingle: z.string().optional(),
    ownerChangeDate: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    lazySupply: z.string(),
    pending: z.array(ItemTransfer$inboundSchema),
    mintedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
    lastUpdatedAt: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    supply: z.string(),
    meta: Meta$inboundSchema.optional(),
    deleted: z.boolean(),
    bestSellOrder: Order$inboundSchema.optional(),
    bestBidOrder: Order$inboundSchema.optional(),
    bestBidOrdersByCurrency: z.array(Order$inboundSchema).optional(),
    originOrders: z.array(OriginOrders$inboundSchema).optional(),
    totalStock: z.string().optional(),
    sellers: z.number().int(),
    lastSale: ItemLastSale$inboundSchema.optional(),
    self: z.boolean().optional(),
    suspicious: z.boolean().optional(),
    itemCollection: ItemCollection$inboundSchema.optional(),
    features: z.array(ItemFeature$inboundSchema).optional(),
    extra: z.record(z.string()).optional(),
    version: z.number().int().optional(),
  });

/** @internal */
export type Item$Outbound = {
  id: string;
  blockchain: string;
  collection?: string | undefined;
  contract?: string | undefined;
  tokenId?: string | undefined;
  creators: Array<Creator$Outbound>;
  ownerIfSingle?: string | undefined;
  ownerChangeDate?: string | undefined;
  lazySupply: string;
  pending: Array<ItemTransfer$Outbound>;
  mintedAt: string;
  lastUpdatedAt: string;
  supply: string;
  meta?: Meta$Outbound | undefined;
  deleted: boolean;
  bestSellOrder?: Order$Outbound | undefined;
  bestBidOrder?: Order$Outbound | undefined;
  bestBidOrdersByCurrency?: Array<Order$Outbound> | undefined;
  originOrders?: Array<OriginOrders$Outbound> | undefined;
  totalStock?: string | undefined;
  sellers: number;
  lastSale?: ItemLastSale$Outbound | undefined;
  self?: boolean | undefined;
  suspicious?: boolean | undefined;
  itemCollection?: ItemCollection$Outbound | undefined;
  features?: Array<string> | undefined;
  extra?: { [k: string]: string } | undefined;
  version?: number | undefined;
};

/** @internal */
export const Item$outboundSchema: z.ZodType<Item$Outbound, z.ZodTypeDef, Item> =
  z.object({
    id: z.string(),
    blockchain: Blockchain$outboundSchema,
    collection: z.string().optional(),
    contract: z.string().optional(),
    tokenId: z.string().optional(),
    creators: z.array(Creator$outboundSchema),
    ownerIfSingle: z.string().optional(),
    ownerChangeDate: z.date().transform(v => v.toISOString()).optional(),
    lazySupply: z.string(),
    pending: z.array(ItemTransfer$outboundSchema),
    mintedAt: z.date().transform(v => v.toISOString()),
    lastUpdatedAt: z.date().transform(v => v.toISOString()),
    supply: z.string(),
    meta: Meta$outboundSchema.optional(),
    deleted: z.boolean(),
    bestSellOrder: Order$outboundSchema.optional(),
    bestBidOrder: Order$outboundSchema.optional(),
    bestBidOrdersByCurrency: z.array(Order$outboundSchema).optional(),
    originOrders: z.array(OriginOrders$outboundSchema).optional(),
    totalStock: z.string().optional(),
    sellers: z.number().int(),
    lastSale: ItemLastSale$outboundSchema.optional(),
    self: z.boolean().optional(),
    suspicious: z.boolean().optional(),
    itemCollection: ItemCollection$outboundSchema.optional(),
    features: z.array(ItemFeature$outboundSchema).optional(),
    extra: z.record(z.string()).optional(),
    version: z.number().int().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Item$ {
  /** @deprecated use `Item$inboundSchema` instead. */
  export const inboundSchema = Item$inboundSchema;
  /** @deprecated use `Item$outboundSchema` instead. */
  export const outboundSchema = Item$outboundSchema;
  /** @deprecated use `Item$Outbound` instead. */
  export type Outbound = Item$Outbound;
}

export function itemToJSON(item: Item): string {
  return JSON.stringify(Item$outboundSchema.parse(item));
}

export function itemFromJSON(
  jsonString: string,
): SafeParseResult<Item, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item' from JSON`,
  );
}
