/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Blockchain,
  Blockchain$inboundSchema,
  Blockchain$outboundSchema,
} from "./blockchain.js";
import {
  Creator,
  Creator$inboundSchema,
  Creator$Outbound,
  Creator$outboundSchema,
} from "./creator.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ItemOwnership = {
  id: string;
  blockchain: Blockchain;
  /**
   * Collection id
   */
  collection?: string | undefined;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  owner: string;
  value: string;
  createdAt: Date;
  /**
   * Creators of the target item
   */
  creators: Array<Creator>;
  lazyValue: string;
  version?: number | undefined;
};

/** @internal */
export const ItemOwnership$inboundSchema: z.ZodType<
  ItemOwnership,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  blockchain: Blockchain$inboundSchema,
  collection: z.string().optional(),
  owner: z.string(),
  value: z.string(),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  creators: z.array(Creator$inboundSchema),
  lazyValue: z.string(),
  version: z.number().int().optional(),
});

/** @internal */
export type ItemOwnership$Outbound = {
  id: string;
  blockchain: string;
  collection?: string | undefined;
  owner: string;
  value: string;
  createdAt: string;
  creators: Array<Creator$Outbound>;
  lazyValue: string;
  version?: number | undefined;
};

/** @internal */
export const ItemOwnership$outboundSchema: z.ZodType<
  ItemOwnership$Outbound,
  z.ZodTypeDef,
  ItemOwnership
> = z.object({
  id: z.string(),
  blockchain: Blockchain$outboundSchema,
  collection: z.string().optional(),
  owner: z.string(),
  value: z.string(),
  createdAt: z.date().transform(v => v.toISOString()),
  creators: z.array(Creator$outboundSchema),
  lazyValue: z.string(),
  version: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ItemOwnership$ {
  /** @deprecated use `ItemOwnership$inboundSchema` instead. */
  export const inboundSchema = ItemOwnership$inboundSchema;
  /** @deprecated use `ItemOwnership$outboundSchema` instead. */
  export const outboundSchema = ItemOwnership$outboundSchema;
  /** @deprecated use `ItemOwnership$Outbound` instead. */
  export type Outbound = ItemOwnership$Outbound;
}

export function itemOwnershipToJSON(itemOwnership: ItemOwnership): string {
  return JSON.stringify(ItemOwnership$outboundSchema.parse(itemOwnership));
}

export function itemOwnershipFromJSON(
  jsonString: string,
): SafeParseResult<ItemOwnership, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ItemOwnership$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ItemOwnership' from JSON`,
  );
}
