/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ItemIds = {
  /**
   * List of the item id
   */
  ids: Array<string>;
};

/** @internal */
export const ItemIds$inboundSchema: z.ZodType<ItemIds, z.ZodTypeDef, unknown> =
  z.object({
    ids: z.array(z.string()),
  });

/** @internal */
export type ItemIds$Outbound = {
  ids: Array<string>;
};

/** @internal */
export const ItemIds$outboundSchema: z.ZodType<
  ItemIds$Outbound,
  z.ZodTypeDef,
  ItemIds
> = z.object({
  ids: z.array(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ItemIds$ {
  /** @deprecated use `ItemIds$inboundSchema` instead. */
  export const inboundSchema = ItemIds$inboundSchema;
  /** @deprecated use `ItemIds$outboundSchema` instead. */
  export const outboundSchema = ItemIds$outboundSchema;
  /** @deprecated use `ItemIds$Outbound` instead. */
  export type Outbound = ItemIds$Outbound;
}

export function itemIdsToJSON(itemIds: ItemIds): string {
  return JSON.stringify(ItemIds$outboundSchema.parse(itemIds));
}

export function itemIdsFromJSON(
  jsonString: string,
): SafeParseResult<ItemIds, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ItemIds$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ItemIds' from JSON`,
  );
}
