/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ItemWithOwnership,
  ItemWithOwnership$inboundSchema,
  ItemWithOwnership$Outbound,
  ItemWithOwnership$outboundSchema,
} from "./itemwithownership.js";

export type ItemsWithOwnership = {
  /**
   * Number of items were found by request
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  total?: number | undefined;
  /**
   * Continuation token to paginate items search result
   */
  continuation?: string | undefined;
  /**
   * List of found items
   */
  items: Array<ItemWithOwnership>;
};

/** @internal */
export const ItemsWithOwnership$inboundSchema: z.ZodType<
  ItemsWithOwnership,
  z.ZodTypeDef,
  unknown
> = z.object({
  total: z.number().int().optional(),
  continuation: z.string().optional(),
  items: z.array(ItemWithOwnership$inboundSchema),
});

/** @internal */
export type ItemsWithOwnership$Outbound = {
  total?: number | undefined;
  continuation?: string | undefined;
  items: Array<ItemWithOwnership$Outbound>;
};

/** @internal */
export const ItemsWithOwnership$outboundSchema: z.ZodType<
  ItemsWithOwnership$Outbound,
  z.ZodTypeDef,
  ItemsWithOwnership
> = z.object({
  total: z.number().int().optional(),
  continuation: z.string().optional(),
  items: z.array(ItemWithOwnership$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ItemsWithOwnership$ {
  /** @deprecated use `ItemsWithOwnership$inboundSchema` instead. */
  export const inboundSchema = ItemsWithOwnership$inboundSchema;
  /** @deprecated use `ItemsWithOwnership$outboundSchema` instead. */
  export const outboundSchema = ItemsWithOwnership$outboundSchema;
  /** @deprecated use `ItemsWithOwnership$Outbound` instead. */
  export type Outbound = ItemsWithOwnership$Outbound;
}

export function itemsWithOwnershipToJSON(
  itemsWithOwnership: ItemsWithOwnership,
): string {
  return JSON.stringify(
    ItemsWithOwnership$outboundSchema.parse(itemsWithOwnership),
  );
}

export function itemsWithOwnershipFromJSON(
  jsonString: string,
): SafeParseResult<ItemsWithOwnership, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ItemsWithOwnership$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ItemsWithOwnership' from JSON`,
  );
}
