/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AssetType,
  AssetType$inboundSchema,
  AssetType$Outbound,
  AssetType$outboundSchema,
} from "./assettype.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ItemLastSale = {
  date: Date;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  seller?: string | undefined;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  buyer?: string | undefined;
  value: string;
  currency: AssetType;
  price: string;
};

/** @internal */
export const ItemLastSale$inboundSchema: z.ZodType<
  ItemLastSale,
  z.ZodTypeDef,
  unknown
> = z.object({
  date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  seller: z.string().optional(),
  buyer: z.string().optional(),
  value: z.string(),
  currency: AssetType$inboundSchema,
  price: z.string(),
});

/** @internal */
export type ItemLastSale$Outbound = {
  date: string;
  seller?: string | undefined;
  buyer?: string | undefined;
  value: string;
  currency: AssetType$Outbound;
  price: string;
};

/** @internal */
export const ItemLastSale$outboundSchema: z.ZodType<
  ItemLastSale$Outbound,
  z.ZodTypeDef,
  ItemLastSale
> = z.object({
  date: z.date().transform(v => v.toISOString()),
  seller: z.string().optional(),
  buyer: z.string().optional(),
  value: z.string(),
  currency: AssetType$outboundSchema,
  price: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ItemLastSale$ {
  /** @deprecated use `ItemLastSale$inboundSchema` instead. */
  export const inboundSchema = ItemLastSale$inboundSchema;
  /** @deprecated use `ItemLastSale$outboundSchema` instead. */
  export const outboundSchema = ItemLastSale$outboundSchema;
  /** @deprecated use `ItemLastSale$Outbound` instead. */
  export type Outbound = ItemLastSale$Outbound;
}

export function itemLastSaleToJSON(itemLastSale: ItemLastSale): string {
  return JSON.stringify(ItemLastSale$outboundSchema.parse(itemLastSale));
}

export function itemLastSaleFromJSON(
  jsonString: string,
): SafeParseResult<ItemLastSale, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ItemLastSale$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ItemLastSale' from JSON`,
  );
}
