/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type LazyItemBurnForm = {
  /**
   * Item Id, has format `ETHEREUM:${token}:${tokenId}`
   */
  id: string;
  /**
   * Address of the NFT item creators
   */
  creators: Array<string>;
  /**
   * Digital signatures
   */
  signatures: Array<string>;
};

/** @internal */
export const LazyItemBurnForm$inboundSchema: z.ZodType<
  LazyItemBurnForm,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  creators: z.array(z.string()),
  signatures: z.array(z.string()),
});

/** @internal */
export type LazyItemBurnForm$Outbound = {
  id: string;
  creators: Array<string>;
  signatures: Array<string>;
};

/** @internal */
export const LazyItemBurnForm$outboundSchema: z.ZodType<
  LazyItemBurnForm$Outbound,
  z.ZodTypeDef,
  LazyItemBurnForm
> = z.object({
  id: z.string(),
  creators: z.array(z.string()),
  signatures: z.array(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LazyItemBurnForm$ {
  /** @deprecated use `LazyItemBurnForm$inboundSchema` instead. */
  export const inboundSchema = LazyItemBurnForm$inboundSchema;
  /** @deprecated use `LazyItemBurnForm$outboundSchema` instead. */
  export const outboundSchema = LazyItemBurnForm$outboundSchema;
  /** @deprecated use `LazyItemBurnForm$Outbound` instead. */
  export type Outbound = LazyItemBurnForm$Outbound;
}

export function lazyItemBurnFormToJSON(
  lazyItemBurnForm: LazyItemBurnForm,
): string {
  return JSON.stringify(
    LazyItemBurnForm$outboundSchema.parse(lazyItemBurnForm),
  );
}

export function lazyItemBurnFormFromJSON(
  jsonString: string,
): SafeParseResult<LazyItemBurnForm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LazyItemBurnForm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LazyItemBurnForm' from JSON`,
  );
}
