/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Creator,
  Creator$inboundSchema,
  Creator$Outbound,
  Creator$outboundSchema,
} from "./creator.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Royalty,
  Royalty$inboundSchema,
  Royalty$Outbound,
  Royalty$outboundSchema,
} from "./royalty.js";

export const AtTypeEthErc1155 = {
  EthErc1155: "ETH_ERC1155",
} as const;
export type AtTypeEthErc1155 = ClosedEnum<typeof AtTypeEthErc1155>;

export type EthLazyItemErc1155 = {
  atType: AtTypeEthErc1155;
  supply: string;
  /**
   * Item Id, has format `ETHEREUM:${token}:${tokenId}`
   */
  id: string;
  uri: string;
  /**
   * Addresses of the NFT item creators
   */
  creators: Array<Creator>;
  /**
   * List of royalties
   */
  royalties: Array<Royalty>;
  /**
   * Digital signatures
   */
  signatures: Array<string>;
};

export const AtTypeEthErc721 = {
  EthErc721: "ETH_ERC721",
} as const;
export type AtTypeEthErc721 = ClosedEnum<typeof AtTypeEthErc721>;

export type EthLazyItemErc721 = {
  atType: AtTypeEthErc721;
  /**
   * Item Id, has format `ETHEREUM:${token}:${tokenId}`
   */
  id: string;
  uri: string;
  /**
   * Addresses of the NFT item creators
   */
  creators: Array<Creator>;
  /**
   * List of royalties
   */
  royalties: Array<Royalty>;
  /**
   * Digital signatures
   */
  signatures: Array<string>;
};

export type EthLazyItem = EthLazyItemErc721 | EthLazyItemErc1155;

/**
 * Type of an Asset
 */
export type LazyItem = EthLazyItemErc721 | EthLazyItemErc1155;

/** @internal */
export const AtTypeEthErc1155$inboundSchema: z.ZodNativeEnum<
  typeof AtTypeEthErc1155
> = z.nativeEnum(AtTypeEthErc1155);

/** @internal */
export const AtTypeEthErc1155$outboundSchema: z.ZodNativeEnum<
  typeof AtTypeEthErc1155
> = AtTypeEthErc1155$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AtTypeEthErc1155$ {
  /** @deprecated use `AtTypeEthErc1155$inboundSchema` instead. */
  export const inboundSchema = AtTypeEthErc1155$inboundSchema;
  /** @deprecated use `AtTypeEthErc1155$outboundSchema` instead. */
  export const outboundSchema = AtTypeEthErc1155$outboundSchema;
}

/** @internal */
export const EthLazyItemErc1155$inboundSchema: z.ZodType<
  EthLazyItemErc1155,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": AtTypeEthErc1155$inboundSchema,
  supply: z.string(),
  id: z.string(),
  uri: z.string(),
  creators: z.array(Creator$inboundSchema),
  royalties: z.array(Royalty$inboundSchema),
  signatures: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type EthLazyItemErc1155$Outbound = {
  "@type": string;
  supply: string;
  id: string;
  uri: string;
  creators: Array<Creator$Outbound>;
  royalties: Array<Royalty$Outbound>;
  signatures: Array<string>;
};

/** @internal */
export const EthLazyItemErc1155$outboundSchema: z.ZodType<
  EthLazyItemErc1155$Outbound,
  z.ZodTypeDef,
  EthLazyItemErc1155
> = z.object({
  atType: AtTypeEthErc1155$outboundSchema,
  supply: z.string(),
  id: z.string(),
  uri: z.string(),
  creators: z.array(Creator$outboundSchema),
  royalties: z.array(Royalty$outboundSchema),
  signatures: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthLazyItemErc1155$ {
  /** @deprecated use `EthLazyItemErc1155$inboundSchema` instead. */
  export const inboundSchema = EthLazyItemErc1155$inboundSchema;
  /** @deprecated use `EthLazyItemErc1155$outboundSchema` instead. */
  export const outboundSchema = EthLazyItemErc1155$outboundSchema;
  /** @deprecated use `EthLazyItemErc1155$Outbound` instead. */
  export type Outbound = EthLazyItemErc1155$Outbound;
}

export function ethLazyItemErc1155ToJSON(
  ethLazyItemErc1155: EthLazyItemErc1155,
): string {
  return JSON.stringify(
    EthLazyItemErc1155$outboundSchema.parse(ethLazyItemErc1155),
  );
}

export function ethLazyItemErc1155FromJSON(
  jsonString: string,
): SafeParseResult<EthLazyItemErc1155, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EthLazyItemErc1155$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EthLazyItemErc1155' from JSON`,
  );
}

/** @internal */
export const AtTypeEthErc721$inboundSchema: z.ZodNativeEnum<
  typeof AtTypeEthErc721
> = z.nativeEnum(AtTypeEthErc721);

/** @internal */
export const AtTypeEthErc721$outboundSchema: z.ZodNativeEnum<
  typeof AtTypeEthErc721
> = AtTypeEthErc721$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AtTypeEthErc721$ {
  /** @deprecated use `AtTypeEthErc721$inboundSchema` instead. */
  export const inboundSchema = AtTypeEthErc721$inboundSchema;
  /** @deprecated use `AtTypeEthErc721$outboundSchema` instead. */
  export const outboundSchema = AtTypeEthErc721$outboundSchema;
}

/** @internal */
export const EthLazyItemErc721$inboundSchema: z.ZodType<
  EthLazyItemErc721,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": AtTypeEthErc721$inboundSchema,
  id: z.string(),
  uri: z.string(),
  creators: z.array(Creator$inboundSchema),
  royalties: z.array(Royalty$inboundSchema),
  signatures: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type EthLazyItemErc721$Outbound = {
  "@type": string;
  id: string;
  uri: string;
  creators: Array<Creator$Outbound>;
  royalties: Array<Royalty$Outbound>;
  signatures: Array<string>;
};

/** @internal */
export const EthLazyItemErc721$outboundSchema: z.ZodType<
  EthLazyItemErc721$Outbound,
  z.ZodTypeDef,
  EthLazyItemErc721
> = z.object({
  atType: AtTypeEthErc721$outboundSchema,
  id: z.string(),
  uri: z.string(),
  creators: z.array(Creator$outboundSchema),
  royalties: z.array(Royalty$outboundSchema),
  signatures: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthLazyItemErc721$ {
  /** @deprecated use `EthLazyItemErc721$inboundSchema` instead. */
  export const inboundSchema = EthLazyItemErc721$inboundSchema;
  /** @deprecated use `EthLazyItemErc721$outboundSchema` instead. */
  export const outboundSchema = EthLazyItemErc721$outboundSchema;
  /** @deprecated use `EthLazyItemErc721$Outbound` instead. */
  export type Outbound = EthLazyItemErc721$Outbound;
}

export function ethLazyItemErc721ToJSON(
  ethLazyItemErc721: EthLazyItemErc721,
): string {
  return JSON.stringify(
    EthLazyItemErc721$outboundSchema.parse(ethLazyItemErc721),
  );
}

export function ethLazyItemErc721FromJSON(
  jsonString: string,
): SafeParseResult<EthLazyItemErc721, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EthLazyItemErc721$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EthLazyItemErc721' from JSON`,
  );
}

/** @internal */
export const EthLazyItem$inboundSchema: z.ZodType<
  EthLazyItem,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => EthLazyItemErc721$inboundSchema),
  z.lazy(() => EthLazyItemErc1155$inboundSchema),
]);

/** @internal */
export type EthLazyItem$Outbound =
  | EthLazyItemErc721$Outbound
  | EthLazyItemErc1155$Outbound;

/** @internal */
export const EthLazyItem$outboundSchema: z.ZodType<
  EthLazyItem$Outbound,
  z.ZodTypeDef,
  EthLazyItem
> = z.union([
  z.lazy(() => EthLazyItemErc721$outboundSchema),
  z.lazy(() => EthLazyItemErc1155$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EthLazyItem$ {
  /** @deprecated use `EthLazyItem$inboundSchema` instead. */
  export const inboundSchema = EthLazyItem$inboundSchema;
  /** @deprecated use `EthLazyItem$outboundSchema` instead. */
  export const outboundSchema = EthLazyItem$outboundSchema;
  /** @deprecated use `EthLazyItem$Outbound` instead. */
  export type Outbound = EthLazyItem$Outbound;
}

export function ethLazyItemToJSON(ethLazyItem: EthLazyItem): string {
  return JSON.stringify(EthLazyItem$outboundSchema.parse(ethLazyItem));
}

export function ethLazyItemFromJSON(
  jsonString: string,
): SafeParseResult<EthLazyItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EthLazyItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EthLazyItem' from JSON`,
  );
}

/** @internal */
export const LazyItem$inboundSchema: z.ZodType<
  LazyItem,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => EthLazyItemErc721$inboundSchema),
  z.lazy(() => EthLazyItemErc1155$inboundSchema),
]);

/** @internal */
export type LazyItem$Outbound =
  | EthLazyItemErc721$Outbound
  | EthLazyItemErc1155$Outbound;

/** @internal */
export const LazyItem$outboundSchema: z.ZodType<
  LazyItem$Outbound,
  z.ZodTypeDef,
  LazyItem
> = z.union([
  z.lazy(() => EthLazyItemErc721$outboundSchema),
  z.lazy(() => EthLazyItemErc1155$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LazyItem$ {
  /** @deprecated use `LazyItem$inboundSchema` instead. */
  export const inboundSchema = LazyItem$inboundSchema;
  /** @deprecated use `LazyItem$outboundSchema` instead. */
  export const outboundSchema = LazyItem$outboundSchema;
  /** @deprecated use `LazyItem$Outbound` instead. */
  export type Outbound = LazyItem$Outbound;
}

export function lazyItemToJSON(lazyItem: LazyItem): string {
  return JSON.stringify(LazyItem$outboundSchema.parse(lazyItem));
}

export function lazyItemFromJSON(
  jsonString: string,
): SafeParseResult<LazyItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LazyItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LazyItem' from JSON`,
  );
}
