/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  LazyItem,
  LazyItem$inboundSchema,
  LazyItem$Outbound,
  LazyItem$outboundSchema,
} from "./lazyitem.js";

export type LazyItemMintForm = {
  /**
   * Type of an Asset
   */
  item: LazyItem;
};

/** @internal */
export const LazyItemMintForm$inboundSchema: z.ZodType<
  LazyItemMintForm,
  z.ZodTypeDef,
  unknown
> = z.object({
  item: LazyItem$inboundSchema,
});

/** @internal */
export type LazyItemMintForm$Outbound = {
  item: LazyItem$Outbound;
};

/** @internal */
export const LazyItemMintForm$outboundSchema: z.ZodType<
  LazyItemMintForm$Outbound,
  z.ZodTypeDef,
  LazyItemMintForm
> = z.object({
  item: LazyItem$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LazyItemMintForm$ {
  /** @deprecated use `LazyItemMintForm$inboundSchema` instead. */
  export const inboundSchema = LazyItemMintForm$inboundSchema;
  /** @deprecated use `LazyItemMintForm$outboundSchema` instead. */
  export const outboundSchema = LazyItemMintForm$outboundSchema;
  /** @deprecated use `LazyItemMintForm$Outbound` instead. */
  export type Outbound = LazyItemMintForm$Outbound;
}

export function lazyItemMintFormToJSON(
  lazyItemMintForm: LazyItemMintForm,
): string {
  return JSON.stringify(
    LazyItemMintForm$outboundSchema.parse(lazyItemMintForm),
  );
}

export function lazyItemMintFormFromJSON(
  jsonString: string,
): SafeParseResult<LazyItemMintForm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LazyItemMintForm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LazyItemMintForm' from JSON`,
  );
}
