/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Blockchain,
  Blockchain$inboundSchema,
  Blockchain$outboundSchema,
} from "./blockchain.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const NativeCurrencyAssetTypeAtType = {
  CurrencyNative: "CURRENCY_NATIVE",
} as const;
export type NativeCurrencyAssetTypeAtType = ClosedEnum<
  typeof NativeCurrencyAssetTypeAtType
>;

export type NativeCurrencyAssetType = {
  blockchain: Blockchain;
  /**
   * Blockchain contract address in Union format `ETHEREUM:${token}`
   */
  contract?: string | undefined;
  atType: NativeCurrencyAssetTypeAtType;
};

/** @internal */
export const NativeCurrencyAssetTypeAtType$inboundSchema: z.ZodNativeEnum<
  typeof NativeCurrencyAssetTypeAtType
> = z.nativeEnum(NativeCurrencyAssetTypeAtType);

/** @internal */
export const NativeCurrencyAssetTypeAtType$outboundSchema: z.ZodNativeEnum<
  typeof NativeCurrencyAssetTypeAtType
> = NativeCurrencyAssetTypeAtType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NativeCurrencyAssetTypeAtType$ {
  /** @deprecated use `NativeCurrencyAssetTypeAtType$inboundSchema` instead. */
  export const inboundSchema = NativeCurrencyAssetTypeAtType$inboundSchema;
  /** @deprecated use `NativeCurrencyAssetTypeAtType$outboundSchema` instead. */
  export const outboundSchema = NativeCurrencyAssetTypeAtType$outboundSchema;
}

/** @internal */
export const NativeCurrencyAssetType$inboundSchema: z.ZodType<
  NativeCurrencyAssetType,
  z.ZodTypeDef,
  unknown
> = z.object({
  blockchain: Blockchain$inboundSchema,
  contract: z.string().optional(),
  "@type": NativeCurrencyAssetTypeAtType$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type NativeCurrencyAssetType$Outbound = {
  blockchain: string;
  contract?: string | undefined;
  "@type": string;
};

/** @internal */
export const NativeCurrencyAssetType$outboundSchema: z.ZodType<
  NativeCurrencyAssetType$Outbound,
  z.ZodTypeDef,
  NativeCurrencyAssetType
> = z.object({
  blockchain: Blockchain$outboundSchema,
  contract: z.string().optional(),
  atType: NativeCurrencyAssetTypeAtType$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NativeCurrencyAssetType$ {
  /** @deprecated use `NativeCurrencyAssetType$inboundSchema` instead. */
  export const inboundSchema = NativeCurrencyAssetType$inboundSchema;
  /** @deprecated use `NativeCurrencyAssetType$outboundSchema` instead. */
  export const outboundSchema = NativeCurrencyAssetType$outboundSchema;
  /** @deprecated use `NativeCurrencyAssetType$Outbound` instead. */
  export type Outbound = NativeCurrencyAssetType$Outbound;
}

export function nativeCurrencyAssetTypeToJSON(
  nativeCurrencyAssetType: NativeCurrencyAssetType,
): string {
  return JSON.stringify(
    NativeCurrencyAssetType$outboundSchema.parse(nativeCurrencyAssetType),
  );
}

export function nativeCurrencyAssetTypeFromJSON(
  jsonString: string,
): SafeParseResult<NativeCurrencyAssetType, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NativeCurrencyAssetType$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NativeCurrencyAssetType' from JSON`,
  );
}
