/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const NftOfCollectionAssetTypeAtType = {
  NftOfCollection: "NFT_OF_COLLECTION",
} as const;
export type NftOfCollectionAssetTypeAtType = ClosedEnum<
  typeof NftOfCollectionAssetTypeAtType
>;

export type NftOfCollectionAssetType = {
  atType: NftOfCollectionAssetTypeAtType;
  /**
   * Collection id
   */
  collectionId: string;
};

/** @internal */
export const NftOfCollectionAssetTypeAtType$inboundSchema: z.ZodNativeEnum<
  typeof NftOfCollectionAssetTypeAtType
> = z.nativeEnum(NftOfCollectionAssetTypeAtType);

/** @internal */
export const NftOfCollectionAssetTypeAtType$outboundSchema: z.ZodNativeEnum<
  typeof NftOfCollectionAssetTypeAtType
> = NftOfCollectionAssetTypeAtType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NftOfCollectionAssetTypeAtType$ {
  /** @deprecated use `NftOfCollectionAssetTypeAtType$inboundSchema` instead. */
  export const inboundSchema = NftOfCollectionAssetTypeAtType$inboundSchema;
  /** @deprecated use `NftOfCollectionAssetTypeAtType$outboundSchema` instead. */
  export const outboundSchema = NftOfCollectionAssetTypeAtType$outboundSchema;
}

/** @internal */
export const NftOfCollectionAssetType$inboundSchema: z.ZodType<
  NftOfCollectionAssetType,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": NftOfCollectionAssetTypeAtType$inboundSchema,
  collectionId: z.string(),
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type NftOfCollectionAssetType$Outbound = {
  "@type": string;
  collectionId: string;
};

/** @internal */
export const NftOfCollectionAssetType$outboundSchema: z.ZodType<
  NftOfCollectionAssetType$Outbound,
  z.ZodTypeDef,
  NftOfCollectionAssetType
> = z.object({
  atType: NftOfCollectionAssetTypeAtType$outboundSchema,
  collectionId: z.string(),
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NftOfCollectionAssetType$ {
  /** @deprecated use `NftOfCollectionAssetType$inboundSchema` instead. */
  export const inboundSchema = NftOfCollectionAssetType$inboundSchema;
  /** @deprecated use `NftOfCollectionAssetType$outboundSchema` instead. */
  export const outboundSchema = NftOfCollectionAssetType$outboundSchema;
  /** @deprecated use `NftOfCollectionAssetType$Outbound` instead. */
  export type Outbound = NftOfCollectionAssetType$Outbound;
}

export function nftOfCollectionAssetTypeToJSON(
  nftOfCollectionAssetType: NftOfCollectionAssetType,
): string {
  return JSON.stringify(
    NftOfCollectionAssetType$outboundSchema.parse(nftOfCollectionAssetType),
  );
}

export function nftOfCollectionAssetTypeFromJSON(
  jsonString: string,
): SafeParseResult<NftOfCollectionAssetType, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NftOfCollectionAssetType$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NftOfCollectionAssetType' from JSON`,
  );
}
