/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type OlapPriceWithUsd = {
  currency: string;
  /**
   * Amount of currency
   */
  value: number;
  /**
   * Amount in USD
   */
  valueUsd?: number | undefined;
};

/** @internal */
export const OlapPriceWithUsd$inboundSchema: z.ZodType<
  OlapPriceWithUsd,
  z.ZodTypeDef,
  unknown
> = z.object({
  currency: z.string(),
  value: z.number(),
  valueUsd: z.number().optional(),
});

/** @internal */
export type OlapPriceWithUsd$Outbound = {
  currency: string;
  value: number;
  valueUsd?: number | undefined;
};

/** @internal */
export const OlapPriceWithUsd$outboundSchema: z.ZodType<
  OlapPriceWithUsd$Outbound,
  z.ZodTypeDef,
  OlapPriceWithUsd
> = z.object({
  currency: z.string(),
  value: z.number(),
  valueUsd: z.number().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OlapPriceWithUsd$ {
  /** @deprecated use `OlapPriceWithUsd$inboundSchema` instead. */
  export const inboundSchema = OlapPriceWithUsd$inboundSchema;
  /** @deprecated use `OlapPriceWithUsd$outboundSchema` instead. */
  export const outboundSchema = OlapPriceWithUsd$outboundSchema;
  /** @deprecated use `OlapPriceWithUsd$Outbound` instead. */
  export type Outbound = OlapPriceWithUsd$Outbound;
}

export function olapPriceWithUsdToJSON(
  olapPriceWithUsd: OlapPriceWithUsd,
): string {
  return JSON.stringify(
    OlapPriceWithUsd$outboundSchema.parse(olapPriceWithUsd),
  );
}

export function olapPriceWithUsdFromJSON(
  jsonString: string,
): SafeParseResult<OlapPriceWithUsd, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OlapPriceWithUsd$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OlapPriceWithUsd' from JSON`,
  );
}
