/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OlapCurrencyAmount,
  OlapCurrencyAmount$inboundSchema,
  OlapCurrencyAmount$Outbound,
  OlapCurrencyAmount$outboundSchema,
} from "./olapcurrencyamount.js";

export type OlapCollectionStatisticsResponse = {
  /**
   * Highest worth transaction in collection
   */
  highestSale: Array<OlapCurrencyAmount>;
  /**
   * Minimal price of nft in this collection available on rarible
   */
  floorPrice: Array<OlapCurrencyAmount>;
  /**
   * Market cap of collection (floor price * total item supply)
   */
  marketCap: Array<OlapCurrencyAmount>;
  /**
   * Total worth of all transactions were made with nfts in this collection
   */
  volume: Array<OlapCurrencyAmount>;
  /**
   * Amount of currently listed items
   */
  listed: number;
  /**
   * Total item supply of all nfts in the collection
   */
  items: number;
  /**
   * Current amount of unique owners who hold nfts of this collection
   */
  owners: number;
};

/** @internal */
export const OlapCollectionStatisticsResponse$inboundSchema: z.ZodType<
  OlapCollectionStatisticsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  highestSale: z.array(OlapCurrencyAmount$inboundSchema),
  floorPrice: z.array(OlapCurrencyAmount$inboundSchema),
  marketCap: z.array(OlapCurrencyAmount$inboundSchema),
  volume: z.array(OlapCurrencyAmount$inboundSchema),
  listed: z.number().int(),
  items: z.number().int(),
  owners: z.number().int(),
});

/** @internal */
export type OlapCollectionStatisticsResponse$Outbound = {
  highestSale: Array<OlapCurrencyAmount$Outbound>;
  floorPrice: Array<OlapCurrencyAmount$Outbound>;
  marketCap: Array<OlapCurrencyAmount$Outbound>;
  volume: Array<OlapCurrencyAmount$Outbound>;
  listed: number;
  items: number;
  owners: number;
};

/** @internal */
export const OlapCollectionStatisticsResponse$outboundSchema: z.ZodType<
  OlapCollectionStatisticsResponse$Outbound,
  z.ZodTypeDef,
  OlapCollectionStatisticsResponse
> = z.object({
  highestSale: z.array(OlapCurrencyAmount$outboundSchema),
  floorPrice: z.array(OlapCurrencyAmount$outboundSchema),
  marketCap: z.array(OlapCurrencyAmount$outboundSchema),
  volume: z.array(OlapCurrencyAmount$outboundSchema),
  listed: z.number().int(),
  items: z.number().int(),
  owners: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OlapCollectionStatisticsResponse$ {
  /** @deprecated use `OlapCollectionStatisticsResponse$inboundSchema` instead. */
  export const inboundSchema = OlapCollectionStatisticsResponse$inboundSchema;
  /** @deprecated use `OlapCollectionStatisticsResponse$outboundSchema` instead. */
  export const outboundSchema = OlapCollectionStatisticsResponse$outboundSchema;
  /** @deprecated use `OlapCollectionStatisticsResponse$Outbound` instead. */
  export type Outbound = OlapCollectionStatisticsResponse$Outbound;
}

export function olapCollectionStatisticsResponseToJSON(
  olapCollectionStatisticsResponse: OlapCollectionStatisticsResponse,
): string {
  return JSON.stringify(
    OlapCollectionStatisticsResponse$outboundSchema.parse(
      olapCollectionStatisticsResponse,
    ),
  );
}

export function olapCollectionStatisticsResponseFromJSON(
  jsonString: string,
): SafeParseResult<OlapCollectionStatisticsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OlapCollectionStatisticsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OlapCollectionStatisticsResponse' from JSON`,
  );
}
