/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const OlapBidsByPriceSort = {
  Price: "PRICE",
  VolumeNative: "VOLUME_NATIVE",
} as const;
export type OlapBidsByPriceSort = ClosedEnum<typeof OlapBidsByPriceSort>;

/** @internal */
export const OlapBidsByPriceSort$inboundSchema: z.ZodNativeEnum<
  typeof OlapBidsByPriceSort
> = z.nativeEnum(OlapBidsByPriceSort);

/** @internal */
export const OlapBidsByPriceSort$outboundSchema: z.ZodNativeEnum<
  typeof OlapBidsByPriceSort
> = OlapBidsByPriceSort$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OlapBidsByPriceSort$ {
  /** @deprecated use `OlapBidsByPriceSort$inboundSchema` instead. */
  export const inboundSchema = OlapBidsByPriceSort$inboundSchema;
  /** @deprecated use `OlapBidsByPriceSort$outboundSchema` instead. */
  export const outboundSchema = OlapBidsByPriceSort$outboundSchema;
}
