/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Period:
 *
 * @remarks
 *   * `MIN5` - Last 5 minutes
 *   * `MIN30` - Last 30 minutes
 *   * `H1` - Last 1 hour
 *   * `H6` - Last 6 hours
 *   * `D1` - Last 1 day
 *   * `D7` - Last 7 days
 *   * `D30` - Last 30 days
 *   * `D180` - Last 180 days (roughly 6 months)
 *   * `D365` - Last 365 days (roughly 1 year)
 *   * `ALL` - For all time
 */
export const OlapPeriod = {
  Min5: "MIN5",
  Min30: "MIN30",
  H1: "H1",
  H6: "H6",
  D1: "D1",
  D7: "D7",
  D30: "D30",
  D180: "D180",
  D365: "D365",
  All: "ALL",
} as const;
/**
 * Period:
 *
 * @remarks
 *   * `MIN5` - Last 5 minutes
 *   * `MIN30` - Last 30 minutes
 *   * `H1` - Last 1 hour
 *   * `H6` - Last 6 hours
 *   * `D1` - Last 1 day
 *   * `D7` - Last 7 days
 *   * `D30` - Last 30 days
 *   * `D180` - Last 180 days (roughly 6 months)
 *   * `D365` - Last 365 days (roughly 1 year)
 *   * `ALL` - For all time
 */
export type OlapPeriod = ClosedEnum<typeof OlapPeriod>;

/** @internal */
export const OlapPeriod$inboundSchema: z.ZodNativeEnum<typeof OlapPeriod> = z
  .nativeEnum(OlapPeriod);

/** @internal */
export const OlapPeriod$outboundSchema: z.ZodNativeEnum<typeof OlapPeriod> =
  OlapPeriod$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OlapPeriod$ {
  /** @deprecated use `OlapPeriod$inboundSchema` instead. */
  export const inboundSchema = OlapPeriod$inboundSchema;
  /** @deprecated use `OlapPeriod$outboundSchema` instead. */
  export const outboundSchema = OlapPeriod$outboundSchema;
}
