/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OlapCurrencyAmount,
  OlapCurrencyAmount$inboundSchema,
  OlapCurrencyAmount$Outbound,
  OlapCurrencyAmount$outboundSchema,
} from "./olapcurrencyamount.js";
import {
  OlapCurrencyAmountWithChange,
  OlapCurrencyAmountWithChange$inboundSchema,
  OlapCurrencyAmountWithChange$Outbound,
  OlapCurrencyAmountWithChange$outboundSchema,
} from "./olapcurrencyamountwithchange.js";

export type OlapCollectionLeaderboardEntry = {
  /**
   * Identifier of collection
   */
  id: string;
  volumeUsd: OlapCurrencyAmountWithChange;
  volumeNative: OlapCurrencyAmount;
  itemsBought: number;
  floorPrice?: OlapCurrencyAmountWithChange | undefined;
  listed: number;
  totalItemSupply: number;
  ownersCount: number;
};

/** @internal */
export const OlapCollectionLeaderboardEntry$inboundSchema: z.ZodType<
  OlapCollectionLeaderboardEntry,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  volumeUsd: OlapCurrencyAmountWithChange$inboundSchema,
  volumeNative: OlapCurrencyAmount$inboundSchema,
  itemsBought: z.number().int(),
  floorPrice: OlapCurrencyAmountWithChange$inboundSchema.optional(),
  listed: z.number().int(),
  totalItemSupply: z.number().int(),
  ownersCount: z.number().int(),
});

/** @internal */
export type OlapCollectionLeaderboardEntry$Outbound = {
  id: string;
  volumeUsd: OlapCurrencyAmountWithChange$Outbound;
  volumeNative: OlapCurrencyAmount$Outbound;
  itemsBought: number;
  floorPrice?: OlapCurrencyAmountWithChange$Outbound | undefined;
  listed: number;
  totalItemSupply: number;
  ownersCount: number;
};

/** @internal */
export const OlapCollectionLeaderboardEntry$outboundSchema: z.ZodType<
  OlapCollectionLeaderboardEntry$Outbound,
  z.ZodTypeDef,
  OlapCollectionLeaderboardEntry
> = z.object({
  id: z.string(),
  volumeUsd: OlapCurrencyAmountWithChange$outboundSchema,
  volumeNative: OlapCurrencyAmount$outboundSchema,
  itemsBought: z.number().int(),
  floorPrice: OlapCurrencyAmountWithChange$outboundSchema.optional(),
  listed: z.number().int(),
  totalItemSupply: z.number().int(),
  ownersCount: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OlapCollectionLeaderboardEntry$ {
  /** @deprecated use `OlapCollectionLeaderboardEntry$inboundSchema` instead. */
  export const inboundSchema = OlapCollectionLeaderboardEntry$inboundSchema;
  /** @deprecated use `OlapCollectionLeaderboardEntry$outboundSchema` instead. */
  export const outboundSchema = OlapCollectionLeaderboardEntry$outboundSchema;
  /** @deprecated use `OlapCollectionLeaderboardEntry$Outbound` instead. */
  export type Outbound = OlapCollectionLeaderboardEntry$Outbound;
}

export function olapCollectionLeaderboardEntryToJSON(
  olapCollectionLeaderboardEntry: OlapCollectionLeaderboardEntry,
): string {
  return JSON.stringify(
    OlapCollectionLeaderboardEntry$outboundSchema.parse(
      olapCollectionLeaderboardEntry,
    ),
  );
}

export function olapCollectionLeaderboardEntryFromJSON(
  jsonString: string,
): SafeParseResult<OlapCollectionLeaderboardEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OlapCollectionLeaderboardEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OlapCollectionLeaderboardEntry' from JSON`,
  );
}
