/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OlapCurrencyAmount,
  OlapCurrencyAmount$inboundSchema,
  OlapCurrencyAmount$Outbound,
  OlapCurrencyAmount$outboundSchema,
} from "./olapcurrencyamount.js";

export type OlapUserLeaderboardEntry = {
  /**
   * Identifier of user
   */
  id: string;
  volumeUsd: OlapCurrencyAmount;
  volumeNative: OlapCurrencyAmount;
  /**
   * (non-unique) amount of traded items
   */
  items: number;
  /**
   * Amount of transactions were made
   */
  transactions: number;
};

/** @internal */
export const OlapUserLeaderboardEntry$inboundSchema: z.ZodType<
  OlapUserLeaderboardEntry,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  volumeUsd: OlapCurrencyAmount$inboundSchema,
  volumeNative: OlapCurrencyAmount$inboundSchema,
  items: z.number().int(),
  transactions: z.number().int(),
});

/** @internal */
export type OlapUserLeaderboardEntry$Outbound = {
  id: string;
  volumeUsd: OlapCurrencyAmount$Outbound;
  volumeNative: OlapCurrencyAmount$Outbound;
  items: number;
  transactions: number;
};

/** @internal */
export const OlapUserLeaderboardEntry$outboundSchema: z.ZodType<
  OlapUserLeaderboardEntry$Outbound,
  z.ZodTypeDef,
  OlapUserLeaderboardEntry
> = z.object({
  id: z.string(),
  volumeUsd: OlapCurrencyAmount$outboundSchema,
  volumeNative: OlapCurrencyAmount$outboundSchema,
  items: z.number().int(),
  transactions: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OlapUserLeaderboardEntry$ {
  /** @deprecated use `OlapUserLeaderboardEntry$inboundSchema` instead. */
  export const inboundSchema = OlapUserLeaderboardEntry$inboundSchema;
  /** @deprecated use `OlapUserLeaderboardEntry$outboundSchema` instead. */
  export const outboundSchema = OlapUserLeaderboardEntry$outboundSchema;
  /** @deprecated use `OlapUserLeaderboardEntry$Outbound` instead. */
  export type Outbound = OlapUserLeaderboardEntry$Outbound;
}

export function olapUserLeaderboardEntryToJSON(
  olapUserLeaderboardEntry: OlapUserLeaderboardEntry,
): string {
  return JSON.stringify(
    OlapUserLeaderboardEntry$outboundSchema.parse(olapUserLeaderboardEntry),
  );
}

export function olapUserLeaderboardEntryFromJSON(
  jsonString: string,
): SafeParseResult<OlapUserLeaderboardEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OlapUserLeaderboardEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OlapUserLeaderboardEntry' from JSON`,
  );
}
