/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OlapPeriod,
  OlapPeriod$inboundSchema,
  OlapPeriod$outboundSchema,
} from "./olapperiod.js";

export type OlapPeriodCollectionsByIdsStatisticsRequest = {
  collectionIds: Array<string>;
  /**
   * Period:
   *
   * @remarks
   *   * `MIN5` - Last 5 minutes
   *   * `MIN30` - Last 30 minutes
   *   * `H1` - Last 1 hour
   *   * `H6` - Last 6 hours
   *   * `D1` - Last 1 day
   *   * `D7` - Last 7 days
   *   * `D30` - Last 30 days
   *   * `D180` - Last 180 days (roughly 6 months)
   *   * `D365` - Last 365 days (roughly 1 year)
   *   * `ALL` - For all time
   */
  period: OlapPeriod;
};

/** @internal */
export const OlapPeriodCollectionsByIdsStatisticsRequest$inboundSchema:
  z.ZodType<
    OlapPeriodCollectionsByIdsStatisticsRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    collectionIds: z.array(z.string()),
    period: OlapPeriod$inboundSchema,
  });

/** @internal */
export type OlapPeriodCollectionsByIdsStatisticsRequest$Outbound = {
  collectionIds: Array<string>;
  period: string;
};

/** @internal */
export const OlapPeriodCollectionsByIdsStatisticsRequest$outboundSchema:
  z.ZodType<
    OlapPeriodCollectionsByIdsStatisticsRequest$Outbound,
    z.ZodTypeDef,
    OlapPeriodCollectionsByIdsStatisticsRequest
  > = z.object({
    collectionIds: z.array(z.string()),
    period: OlapPeriod$outboundSchema,
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OlapPeriodCollectionsByIdsStatisticsRequest$ {
  /** @deprecated use `OlapPeriodCollectionsByIdsStatisticsRequest$inboundSchema` instead. */
  export const inboundSchema =
    OlapPeriodCollectionsByIdsStatisticsRequest$inboundSchema;
  /** @deprecated use `OlapPeriodCollectionsByIdsStatisticsRequest$outboundSchema` instead. */
  export const outboundSchema =
    OlapPeriodCollectionsByIdsStatisticsRequest$outboundSchema;
  /** @deprecated use `OlapPeriodCollectionsByIdsStatisticsRequest$Outbound` instead. */
  export type Outbound = OlapPeriodCollectionsByIdsStatisticsRequest$Outbound;
}

export function olapPeriodCollectionsByIdsStatisticsRequestToJSON(
  olapPeriodCollectionsByIdsStatisticsRequest:
    OlapPeriodCollectionsByIdsStatisticsRequest,
): string {
  return JSON.stringify(
    OlapPeriodCollectionsByIdsStatisticsRequest$outboundSchema.parse(
      olapPeriodCollectionsByIdsStatisticsRequest,
    ),
  );
}

export function olapPeriodCollectionsByIdsStatisticsRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  OlapPeriodCollectionsByIdsStatisticsRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OlapPeriodCollectionsByIdsStatisticsRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'OlapPeriodCollectionsByIdsStatisticsRequest' from JSON`,
  );
}
