/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OlapUserLeaderboardEntry,
  OlapUserLeaderboardEntry$inboundSchema,
  OlapUserLeaderboardEntry$Outbound,
  OlapUserLeaderboardEntry$outboundSchema,
} from "./olapuserleaderboardentry.js";

export type OlapUserVolumeRankingResponse = {
  result?: Array<OlapUserLeaderboardEntry> | undefined;
};

/** @internal */
export const OlapUserVolumeRankingResponse$inboundSchema: z.ZodType<
  OlapUserVolumeRankingResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  result: z.array(OlapUserLeaderboardEntry$inboundSchema).optional(),
});

/** @internal */
export type OlapUserVolumeRankingResponse$Outbound = {
  result?: Array<OlapUserLeaderboardEntry$Outbound> | undefined;
};

/** @internal */
export const OlapUserVolumeRankingResponse$outboundSchema: z.ZodType<
  OlapUserVolumeRankingResponse$Outbound,
  z.ZodTypeDef,
  OlapUserVolumeRankingResponse
> = z.object({
  result: z.array(OlapUserLeaderboardEntry$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OlapUserVolumeRankingResponse$ {
  /** @deprecated use `OlapUserVolumeRankingResponse$inboundSchema` instead. */
  export const inboundSchema = OlapUserVolumeRankingResponse$inboundSchema;
  /** @deprecated use `OlapUserVolumeRankingResponse$outboundSchema` instead. */
  export const outboundSchema = OlapUserVolumeRankingResponse$outboundSchema;
  /** @deprecated use `OlapUserVolumeRankingResponse$Outbound` instead. */
  export type Outbound = OlapUserVolumeRankingResponse$Outbound;
}

export function olapUserVolumeRankingResponseToJSON(
  olapUserVolumeRankingResponse: OlapUserVolumeRankingResponse,
): string {
  return JSON.stringify(
    OlapUserVolumeRankingResponse$outboundSchema.parse(
      olapUserVolumeRankingResponse,
    ),
  );
}

export function olapUserVolumeRankingResponseFromJSON(
  jsonString: string,
): SafeParseResult<OlapUserVolumeRankingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OlapUserVolumeRankingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OlapUserVolumeRankingResponse' from JSON`,
  );
}
