/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OlapCollectionLeaderboardEntry,
  OlapCollectionLeaderboardEntry$inboundSchema,
  OlapCollectionLeaderboardEntry$Outbound,
  OlapCollectionLeaderboardEntry$outboundSchema,
} from "./olapcollectionleaderboardentry.js";

export type OlapCollectionVolumeRankingResponse = {
  continuation?: string | undefined;
  result?: Array<OlapCollectionLeaderboardEntry> | undefined;
};

/** @internal */
export const OlapCollectionVolumeRankingResponse$inboundSchema: z.ZodType<
  OlapCollectionVolumeRankingResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  continuation: z.string().optional(),
  result: z.array(OlapCollectionLeaderboardEntry$inboundSchema).optional(),
});

/** @internal */
export type OlapCollectionVolumeRankingResponse$Outbound = {
  continuation?: string | undefined;
  result?: Array<OlapCollectionLeaderboardEntry$Outbound> | undefined;
};

/** @internal */
export const OlapCollectionVolumeRankingResponse$outboundSchema: z.ZodType<
  OlapCollectionVolumeRankingResponse$Outbound,
  z.ZodTypeDef,
  OlapCollectionVolumeRankingResponse
> = z.object({
  continuation: z.string().optional(),
  result: z.array(OlapCollectionLeaderboardEntry$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OlapCollectionVolumeRankingResponse$ {
  /** @deprecated use `OlapCollectionVolumeRankingResponse$inboundSchema` instead. */
  export const inboundSchema =
    OlapCollectionVolumeRankingResponse$inboundSchema;
  /** @deprecated use `OlapCollectionVolumeRankingResponse$outboundSchema` instead. */
  export const outboundSchema =
    OlapCollectionVolumeRankingResponse$outboundSchema;
  /** @deprecated use `OlapCollectionVolumeRankingResponse$Outbound` instead. */
  export type Outbound = OlapCollectionVolumeRankingResponse$Outbound;
}

export function olapCollectionVolumeRankingResponseToJSON(
  olapCollectionVolumeRankingResponse: OlapCollectionVolumeRankingResponse,
): string {
  return JSON.stringify(
    OlapCollectionVolumeRankingResponse$outboundSchema.parse(
      olapCollectionVolumeRankingResponse,
    ),
  );
}

export function olapCollectionVolumeRankingResponseFromJSON(
  jsonString: string,
): SafeParseResult<OlapCollectionVolumeRankingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      OlapCollectionVolumeRankingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OlapCollectionVolumeRankingResponse' from JSON`,
  );
}
