/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Code
 */
export const OlapErrorCode = {
  InvalidInput: "INVALID_INPUT",
  NotFound: "NOT_FOUND",
  Unknown: "UNKNOWN",
} as const;
/**
 * Code
 */
export type OlapErrorCode = ClosedEnum<typeof OlapErrorCode>;

/** @internal */
export const OlapErrorCode$inboundSchema: z.ZodNativeEnum<
  typeof OlapErrorCode
> = z.nativeEnum(OlapErrorCode);

/** @internal */
export const OlapErrorCode$outboundSchema: z.ZodNativeEnum<
  typeof OlapErrorCode
> = OlapErrorCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OlapErrorCode$ {
  /** @deprecated use `OlapErrorCode$inboundSchema` instead. */
  export const inboundSchema = OlapErrorCode$inboundSchema;
  /** @deprecated use `OlapErrorCode$outboundSchema` instead. */
  export const outboundSchema = OlapErrorCode$outboundSchema;
}
