/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OlapCollectionLeaderboardItem,
  OlapCollectionLeaderboardItem$inboundSchema,
  OlapCollectionLeaderboardItem$Outbound,
  OlapCollectionLeaderboardItem$outboundSchema,
} from "./olapcollectionleaderboarditem.js";

export type OlapCollectionLeaderboardResponse = {
  continuation?: string | undefined;
  result?: Array<OlapCollectionLeaderboardItem> | undefined;
};

/** @internal */
export const OlapCollectionLeaderboardResponse$inboundSchema: z.ZodType<
  OlapCollectionLeaderboardResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  continuation: z.string().optional(),
  result: z.array(OlapCollectionLeaderboardItem$inboundSchema).optional(),
});

/** @internal */
export type OlapCollectionLeaderboardResponse$Outbound = {
  continuation?: string | undefined;
  result?: Array<OlapCollectionLeaderboardItem$Outbound> | undefined;
};

/** @internal */
export const OlapCollectionLeaderboardResponse$outboundSchema: z.ZodType<
  OlapCollectionLeaderboardResponse$Outbound,
  z.ZodTypeDef,
  OlapCollectionLeaderboardResponse
> = z.object({
  continuation: z.string().optional(),
  result: z.array(OlapCollectionLeaderboardItem$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OlapCollectionLeaderboardResponse$ {
  /** @deprecated use `OlapCollectionLeaderboardResponse$inboundSchema` instead. */
  export const inboundSchema = OlapCollectionLeaderboardResponse$inboundSchema;
  /** @deprecated use `OlapCollectionLeaderboardResponse$outboundSchema` instead. */
  export const outboundSchema =
    OlapCollectionLeaderboardResponse$outboundSchema;
  /** @deprecated use `OlapCollectionLeaderboardResponse$Outbound` instead. */
  export type Outbound = OlapCollectionLeaderboardResponse$Outbound;
}

export function olapCollectionLeaderboardResponseToJSON(
  olapCollectionLeaderboardResponse: OlapCollectionLeaderboardResponse,
): string {
  return JSON.stringify(
    OlapCollectionLeaderboardResponse$outboundSchema.parse(
      olapCollectionLeaderboardResponse,
    ),
  );
}

export function olapCollectionLeaderboardResponseFromJSON(
  jsonString: string,
): SafeParseResult<OlapCollectionLeaderboardResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OlapCollectionLeaderboardResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OlapCollectionLeaderboardResponse' from JSON`,
  );
}
