/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const OlapBlockchain = {
  Ethereum: "ETHEREUM",
  Flow: "FLOW",
  Polygon: "POLYGON",
  Solana: "SOLANA",
  Immutablex: "IMMUTABLEX",
  Mantle: "MANTLE",
  Arbitrum: "ARBITRUM",
  Chiliz: "CHILIZ",
  Lightlink: "LIGHTLINK",
  Zksync: "ZKSYNC",
  Astarzkevm: "ASTARZKEVM",
  Base: "BASE",
  Rari: "RARI",
  Celo: "CELO",
  Fief: "FIEF",
  Xai: "XAI",
  Kroma: "KROMA",
  Aptos: "APTOS",
  Zklink: "ZKLINK",
  Oasys: "OASYS",
  Quai: "QUAI",
  Eclipse: "ECLIPSE",
  Saakuru: "SAAKURU",
  Oasis: "OASIS",
  Palm: "PALM",
  Match: "MATCH",
  Fivire: "FIVIRE",
  Sei: "SEI",
  Camp: "CAMP",
  Lisk: "LISK",
  Moonbeam: "MOONBEAM",
  Etherlink: "ETHERLINK",
  Zkcandy: "ZKCANDY",
  Alephzero: "ALEPHZERO",
  Berachain: "BERACHAIN",
  Abstract: "ABSTRACT",
  Shape: "SHAPE",
  Telos: "TELOS",
  Hederaevm: "HEDERAEVM",
  Viction: "VICTION",
  Settlus: "SETTLUS",
  Goat: "GOAT",
  Hyperevm: "HYPEREVM",
  Crossfi: "CROSSFI",
  Megaeth: "MEGAETH",
  Megaethtestnet: "MEGAETHTESTNET",
  Basecamp: "BASECAMP",
  Basecamptestnet: "BASECAMPTESTNET",
  Somnia: "SOMNIA",
} as const;
export type OlapBlockchain = ClosedEnum<typeof OlapBlockchain>;

/** @internal */
export const OlapBlockchain$inboundSchema: z.ZodNativeEnum<
  typeof OlapBlockchain
> = z.nativeEnum(OlapBlockchain);

/** @internal */
export const OlapBlockchain$outboundSchema: z.ZodNativeEnum<
  typeof OlapBlockchain
> = OlapBlockchain$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OlapBlockchain$ {
  /** @deprecated use `OlapBlockchain$inboundSchema` instead. */
  export const inboundSchema = OlapBlockchain$inboundSchema;
  /** @deprecated use `OlapBlockchain$outboundSchema` instead. */
  export const outboundSchema = OlapBlockchain$outboundSchema;
}
