/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OlapHistoryValuesByTimestamps,
  OlapHistoryValuesByTimestamps$inboundSchema,
  OlapHistoryValuesByTimestamps$Outbound,
  OlapHistoryValuesByTimestamps$outboundSchema,
} from "./olaphistoryvaluesbytimestamps.js";

export type OlapChartResponse = {
  dataPoints: OlapHistoryValuesByTimestamps;
};

/** @internal */
export const OlapChartResponse$inboundSchema: z.ZodType<
  OlapChartResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  dataPoints: OlapHistoryValuesByTimestamps$inboundSchema,
});

/** @internal */
export type OlapChartResponse$Outbound = {
  dataPoints: OlapHistoryValuesByTimestamps$Outbound;
};

/** @internal */
export const OlapChartResponse$outboundSchema: z.ZodType<
  OlapChartResponse$Outbound,
  z.ZodTypeDef,
  OlapChartResponse
> = z.object({
  dataPoints: OlapHistoryValuesByTimestamps$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OlapChartResponse$ {
  /** @deprecated use `OlapChartResponse$inboundSchema` instead. */
  export const inboundSchema = OlapChartResponse$inboundSchema;
  /** @deprecated use `OlapChartResponse$outboundSchema` instead. */
  export const outboundSchema = OlapChartResponse$outboundSchema;
  /** @deprecated use `OlapChartResponse$Outbound` instead. */
  export type Outbound = OlapChartResponse$Outbound;
}

export function olapChartResponseToJSON(
  olapChartResponse: OlapChartResponse,
): string {
  return JSON.stringify(
    OlapChartResponse$outboundSchema.parse(olapChartResponse),
  );
}

export function olapChartResponseFromJSON(
  jsonString: string,
): SafeParseResult<OlapChartResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OlapChartResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OlapChartResponse' from JSON`,
  );
}
