/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OlapCurrencyType,
  OlapCurrencyType$inboundSchema,
  OlapCurrencyType$outboundSchema,
} from "./olapcurrencytype.js";

export type OlapCurrencyAmount = {
  currency?: OlapCurrencyType | undefined;
  /**
   * Amount of currency
   */
  value: number;
};

/** @internal */
export const OlapCurrencyAmount$inboundSchema: z.ZodType<
  OlapCurrencyAmount,
  z.ZodTypeDef,
  unknown
> = z.object({
  currency: OlapCurrencyType$inboundSchema.default("USD"),
  value: z.number(),
});

/** @internal */
export type OlapCurrencyAmount$Outbound = {
  currency: string;
  value: number;
};

/** @internal */
export const OlapCurrencyAmount$outboundSchema: z.ZodType<
  OlapCurrencyAmount$Outbound,
  z.ZodTypeDef,
  OlapCurrencyAmount
> = z.object({
  currency: OlapCurrencyType$outboundSchema.default("USD"),
  value: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OlapCurrencyAmount$ {
  /** @deprecated use `OlapCurrencyAmount$inboundSchema` instead. */
  export const inboundSchema = OlapCurrencyAmount$inboundSchema;
  /** @deprecated use `OlapCurrencyAmount$outboundSchema` instead. */
  export const outboundSchema = OlapCurrencyAmount$outboundSchema;
  /** @deprecated use `OlapCurrencyAmount$Outbound` instead. */
  export type Outbound = OlapCurrencyAmount$Outbound;
}

export function olapCurrencyAmountToJSON(
  olapCurrencyAmount: OlapCurrencyAmount,
): string {
  return JSON.stringify(
    OlapCurrencyAmount$outboundSchema.parse(olapCurrencyAmount),
  );
}

export function olapCurrencyAmountFromJSON(
  jsonString: string,
): SafeParseResult<OlapCurrencyAmount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OlapCurrencyAmount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OlapCurrencyAmount' from JSON`,
  );
}
