/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Base fees
 */
export type OrderFees = {
  fees: { [k: string]: number };
};

/** @internal */
export const OrderFees$inboundSchema: z.ZodType<
  OrderFees,
  z.ZodTypeDef,
  unknown
> = z.object({
  fees: z.record(z.number().int()),
});

/** @internal */
export type OrderFees$Outbound = {
  fees: { [k: string]: number };
};

/** @internal */
export const OrderFees$outboundSchema: z.ZodType<
  OrderFees$Outbound,
  z.ZodTypeDef,
  OrderFees
> = z.object({
  fees: z.record(z.number().int()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrderFees$ {
  /** @deprecated use `OrderFees$inboundSchema` instead. */
  export const inboundSchema = OrderFees$inboundSchema;
  /** @deprecated use `OrderFees$outboundSchema` instead. */
  export const outboundSchema = OrderFees$outboundSchema;
  /** @deprecated use `OrderFees$Outbound` instead. */
  export type Outbound = OrderFees$Outbound;
}

export function orderFeesToJSON(orderFees: OrderFees): string {
  return JSON.stringify(OrderFees$outboundSchema.parse(orderFees));
}

export function orderFeesFromJSON(
  jsonString: string,
): SafeParseResult<OrderFees, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrderFees$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrderFees' from JSON`,
  );
}
