/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type OrderIds = {
  /**
   * Array of the orders Ids in format 'ETHEREUM:${id}'
   */
  ids: Array<string>;
};

/** @internal */
export const OrderIds$inboundSchema: z.ZodType<
  OrderIds,
  z.ZodTypeDef,
  unknown
> = z.object({
  ids: z.array(z.string()),
});

/** @internal */
export type OrderIds$Outbound = {
  ids: Array<string>;
};

/** @internal */
export const OrderIds$outboundSchema: z.ZodType<
  OrderIds$Outbound,
  z.ZodTypeDef,
  OrderIds
> = z.object({
  ids: z.array(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrderIds$ {
  /** @deprecated use `OrderIds$inboundSchema` instead. */
  export const inboundSchema = OrderIds$inboundSchema;
  /** @deprecated use `OrderIds$outboundSchema` instead. */
  export const outboundSchema = OrderIds$outboundSchema;
  /** @deprecated use `OrderIds$Outbound` instead. */
  export type Outbound = OrderIds$Outbound;
}

export function orderIdsToJSON(orderIds: OrderIds): string {
  return JSON.stringify(OrderIds$outboundSchema.parse(orderIds));
}

export function orderIdsFromJSON(
  jsonString: string,
): SafeParseResult<OrderIds, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrderIds$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrderIds' from JSON`,
  );
}
