/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Order,
  Order$inboundSchema,
  Order$Outbound,
  Order$outboundSchema,
} from "./order.js";

export type Orders = {
  /**
   * Continuation token to paginate orders search result
   */
  continuation?: string | undefined;
  /**
   * List of found orders
   */
  orders: Array<Order>;
};

/** @internal */
export const Orders$inboundSchema: z.ZodType<Orders, z.ZodTypeDef, unknown> = z
  .object({
    continuation: z.string().optional(),
    orders: z.array(Order$inboundSchema),
  });

/** @internal */
export type Orders$Outbound = {
  continuation?: string | undefined;
  orders: Array<Order$Outbound>;
};

/** @internal */
export const Orders$outboundSchema: z.ZodType<
  Orders$Outbound,
  z.ZodTypeDef,
  Orders
> = z.object({
  continuation: z.string().optional(),
  orders: z.array(Order$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Orders$ {
  /** @deprecated use `Orders$inboundSchema` instead. */
  export const inboundSchema = Orders$inboundSchema;
  /** @deprecated use `Orders$outboundSchema` instead. */
  export const outboundSchema = Orders$outboundSchema;
  /** @deprecated use `Orders$Outbound` instead. */
  export type Outbound = Orders$Outbound;
}

export function ordersToJSON(orders: Orders): string {
  return JSON.stringify(Orders$outboundSchema.parse(orders));
}

export function ordersFromJSON(
  jsonString: string,
): SafeParseResult<Orders, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Orders$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Orders' from JSON`,
  );
}
