/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const OrderSort = {
  LastUpdateAsc: "LAST_UPDATE_ASC",
  LastUpdateDesc: "LAST_UPDATE_DESC",
} as const;
export type OrderSort = ClosedEnum<typeof OrderSort>;

/** @internal */
export const OrderSort$inboundSchema: z.ZodNativeEnum<typeof OrderSort> = z
  .nativeEnum(OrderSort);

/** @internal */
export const OrderSort$outboundSchema: z.ZodNativeEnum<typeof OrderSort> =
  OrderSort$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrderSort$ {
  /** @deprecated use `OrderSort$inboundSchema` instead. */
  export const inboundSchema = OrderSort$inboundSchema;
  /** @deprecated use `OrderSort$outboundSchema` instead. */
  export const outboundSchema = OrderSort$outboundSchema;
}
