/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Asset,
  Asset$inboundSchema,
  Asset$Outbound,
  Asset$outboundSchema,
} from "./asset.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OrderData,
  OrderData$inboundSchema,
  OrderData$Outbound,
  OrderData$outboundSchema,
} from "./orderdata.js";
import {
  OrderStatus,
  OrderStatus$inboundSchema,
  OrderStatus$outboundSchema,
} from "./orderstatus.js";
import {
  Platform,
  Platform$inboundSchema,
  Platform$outboundSchema,
} from "./platform.js";

export type Order = {
  id: string;
  fill: string;
  platform: Platform;
  status: OrderStatus;
  startedAt?: Date | undefined;
  endedAt?: Date | undefined;
  makeStock: string;
  cancelled: boolean;
  /**
   * True if the execution of this order does not guarantee that the royalties will be paid. In this case, it is up to the buyer to pay the royalties.
   */
  optionalRoyalties?: boolean | undefined;
  createdAt: Date;
  lastUpdatedAt: Date;
  dbUpdatedAt?: Date | undefined;
  makePrice?: string | undefined;
  takePrice?: string | undefined;
  makePriceUsd?: string | undefined;
  takePriceUsd?: string | undefined;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  maker: string;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  taker?: string | undefined;
  make: Asset;
  take: Asset;
  salt: string;
  signature?: string | undefined;
  feeTakers?: Array<string> | undefined;
  data: OrderData;
  version?: number | undefined;
};

/** @internal */
export const Order$inboundSchema: z.ZodType<Order, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string(),
    fill: z.string(),
    platform: Platform$inboundSchema,
    status: OrderStatus$inboundSchema,
    startedAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
      .optional(),
    endedAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
      .optional(),
    makeStock: z.string(),
    cancelled: z.boolean(),
    optionalRoyalties: z.boolean().default(false),
    createdAt: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    lastUpdatedAt: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    dbUpdatedAt: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    makePrice: z.string().optional(),
    takePrice: z.string().optional(),
    makePriceUsd: z.string().optional(),
    takePriceUsd: z.string().optional(),
    maker: z.string(),
    taker: z.string().optional(),
    make: Asset$inboundSchema,
    take: Asset$inboundSchema,
    salt: z.string(),
    signature: z.string().optional(),
    feeTakers: z.array(z.string()).optional(),
    data: OrderData$inboundSchema,
    version: z.number().int().optional(),
  });

/** @internal */
export type Order$Outbound = {
  id: string;
  fill: string;
  platform: string;
  status: string;
  startedAt?: string | undefined;
  endedAt?: string | undefined;
  makeStock: string;
  cancelled: boolean;
  optionalRoyalties: boolean;
  createdAt: string;
  lastUpdatedAt: string;
  dbUpdatedAt?: string | undefined;
  makePrice?: string | undefined;
  takePrice?: string | undefined;
  makePriceUsd?: string | undefined;
  takePriceUsd?: string | undefined;
  maker: string;
  taker?: string | undefined;
  make: Asset$Outbound;
  take: Asset$Outbound;
  salt: string;
  signature?: string | undefined;
  feeTakers?: Array<string> | undefined;
  data: OrderData$Outbound;
  version?: number | undefined;
};

/** @internal */
export const Order$outboundSchema: z.ZodType<
  Order$Outbound,
  z.ZodTypeDef,
  Order
> = z.object({
  id: z.string(),
  fill: z.string(),
  platform: Platform$outboundSchema,
  status: OrderStatus$outboundSchema,
  startedAt: z.date().transform(v => v.toISOString()).optional(),
  endedAt: z.date().transform(v => v.toISOString()).optional(),
  makeStock: z.string(),
  cancelled: z.boolean(),
  optionalRoyalties: z.boolean().default(false),
  createdAt: z.date().transform(v => v.toISOString()),
  lastUpdatedAt: z.date().transform(v => v.toISOString()),
  dbUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  makePrice: z.string().optional(),
  takePrice: z.string().optional(),
  makePriceUsd: z.string().optional(),
  takePriceUsd: z.string().optional(),
  maker: z.string(),
  taker: z.string().optional(),
  make: Asset$outboundSchema,
  take: Asset$outboundSchema,
  salt: z.string(),
  signature: z.string().optional(),
  feeTakers: z.array(z.string()).optional(),
  data: OrderData$outboundSchema,
  version: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Order$ {
  /** @deprecated use `Order$inboundSchema` instead. */
  export const inboundSchema = Order$inboundSchema;
  /** @deprecated use `Order$outboundSchema` instead. */
  export const outboundSchema = Order$outboundSchema;
  /** @deprecated use `Order$Outbound` instead. */
  export type Outbound = Order$Outbound;
}

export function orderToJSON(order: Order): string {
  return JSON.stringify(Order$outboundSchema.parse(order));
}

export function orderFromJSON(
  jsonString: string,
): SafeParseResult<Order, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Order$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Order' from JSON`,
  );
}
