/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const OwnershipSearchSort = {
  Latest: "LATEST",
  Earliest: "EARLIEST",
  HighestSell: "HIGHEST_SELL",
  LowestSell: "LOWEST_SELL",
} as const;
export type OwnershipSearchSort = ClosedEnum<typeof OwnershipSearchSort>;

/** @internal */
export const OwnershipSearchSort$inboundSchema: z.ZodNativeEnum<
  typeof OwnershipSearchSort
> = z.nativeEnum(OwnershipSearchSort);

/** @internal */
export const OwnershipSearchSort$outboundSchema: z.ZodNativeEnum<
  typeof OwnershipSearchSort
> = OwnershipSearchSort$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OwnershipSearchSort$ {
  /** @deprecated use `OwnershipSearchSort$inboundSchema` instead. */
  export const inboundSchema = OwnershipSearchSort$inboundSchema;
  /** @deprecated use `OwnershipSearchSort$outboundSchema` instead. */
  export const outboundSchema = OwnershipSearchSort$outboundSchema;
}
