/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Blockchain,
  Blockchain$inboundSchema,
  Blockchain$outboundSchema,
} from "./blockchain.js";
import {
  Creator,
  Creator$inboundSchema,
  Creator$Outbound,
  Creator$outboundSchema,
} from "./creator.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ItemHistory,
  ItemHistory$inboundSchema,
  ItemHistory$Outbound,
  ItemHistory$outboundSchema,
} from "./itemhistory.js";
import {
  Order,
  Order$inboundSchema,
  Order$Outbound,
  Order$outboundSchema,
} from "./order.js";
import {
  OriginOrders,
  OriginOrders$inboundSchema,
  OriginOrders$Outbound,
  OriginOrders$outboundSchema,
} from "./originorders.js";
import {
  OwnershipSource,
  OwnershipSource$inboundSchema,
  OwnershipSource$outboundSchema,
} from "./ownershipsource.js";

export type Ownership = {
  id: string;
  blockchain: Blockchain;
  /**
   * Item Id, has format `ETHEREUM:${token}:${tokenId}`
   */
  itemId?: string | undefined;
  /**
   * Blockchain contract address in Union format `ETHEREUM:${token}`
   */
  contract?: string | undefined;
  /**
   * Collection id
   */
  collection?: string | undefined;
  tokenId?: string | undefined;
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  owner: string;
  value: string;
  source?: OwnershipSource | undefined;
  createdAt: Date;
  lastUpdatedAt?: Date | undefined;
  /**
   * Creators of the target item
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  creators?: Array<Creator> | undefined;
  lazyValue: string;
  /**
   * Pending information about the item
   */
  pending: Array<ItemHistory>;
  bestSellOrder?: Order | undefined;
  originOrders?: Array<OriginOrders> | undefined;
  version?: number | undefined;
};

/** @internal */
export const Ownership$inboundSchema: z.ZodType<
  Ownership,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  blockchain: Blockchain$inboundSchema,
  itemId: z.string().optional(),
  contract: z.string().optional(),
  collection: z.string().optional(),
  tokenId: z.string().optional(),
  owner: z.string(),
  value: z.string(),
  source: OwnershipSource$inboundSchema.optional(),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  lastUpdatedAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  creators: z.array(Creator$inboundSchema).optional(),
  lazyValue: z.string(),
  pending: z.array(ItemHistory$inboundSchema),
  bestSellOrder: Order$inboundSchema.optional(),
  originOrders: z.array(OriginOrders$inboundSchema).optional(),
  version: z.number().int().optional(),
});

/** @internal */
export type Ownership$Outbound = {
  id: string;
  blockchain: string;
  itemId?: string | undefined;
  contract?: string | undefined;
  collection?: string | undefined;
  tokenId?: string | undefined;
  owner: string;
  value: string;
  source?: string | undefined;
  createdAt: string;
  lastUpdatedAt?: string | undefined;
  creators?: Array<Creator$Outbound> | undefined;
  lazyValue: string;
  pending: Array<ItemHistory$Outbound>;
  bestSellOrder?: Order$Outbound | undefined;
  originOrders?: Array<OriginOrders$Outbound> | undefined;
  version?: number | undefined;
};

/** @internal */
export const Ownership$outboundSchema: z.ZodType<
  Ownership$Outbound,
  z.ZodTypeDef,
  Ownership
> = z.object({
  id: z.string(),
  blockchain: Blockchain$outboundSchema,
  itemId: z.string().optional(),
  contract: z.string().optional(),
  collection: z.string().optional(),
  tokenId: z.string().optional(),
  owner: z.string(),
  value: z.string(),
  source: OwnershipSource$outboundSchema.optional(),
  createdAt: z.date().transform(v => v.toISOString()),
  lastUpdatedAt: z.date().transform(v => v.toISOString()).optional(),
  creators: z.array(Creator$outboundSchema).optional(),
  lazyValue: z.string(),
  pending: z.array(ItemHistory$outboundSchema),
  bestSellOrder: Order$outboundSchema.optional(),
  originOrders: z.array(OriginOrders$outboundSchema).optional(),
  version: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Ownership$ {
  /** @deprecated use `Ownership$inboundSchema` instead. */
  export const inboundSchema = Ownership$inboundSchema;
  /** @deprecated use `Ownership$outboundSchema` instead. */
  export const outboundSchema = Ownership$outboundSchema;
  /** @deprecated use `Ownership$Outbound` instead. */
  export type Outbound = Ownership$Outbound;
}

export function ownershipToJSON(ownership: Ownership): string {
  return JSON.stringify(Ownership$outboundSchema.parse(ownership));
}

export function ownershipFromJSON(
  jsonString: string,
): SafeParseResult<Ownership, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ownership$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ownership' from JSON`,
  );
}
