/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const OwnershipSource = {
  Mint: "MINT",
  Purchase: "PURCHASE",
  Transfer: "TRANSFER",
} as const;
export type OwnershipSource = ClosedEnum<typeof OwnershipSource>;

/** @internal */
export const OwnershipSource$inboundSchema: z.ZodNativeEnum<
  typeof OwnershipSource
> = z.nativeEnum(OwnershipSource);

/** @internal */
export const OwnershipSource$outboundSchema: z.ZodNativeEnum<
  typeof OwnershipSource
> = OwnershipSource$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OwnershipSource$ {
  /** @deprecated use `OwnershipSource$inboundSchema` instead. */
  export const inboundSchema = OwnershipSource$inboundSchema;
  /** @deprecated use `OwnershipSource$outboundSchema` instead. */
  export const outboundSchema = OwnershipSource$outboundSchema;
}
