/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type OwnershipIds = {
  /**
   * List of the Ownerships ids
   */
  ids: Array<string>;
};

/** @internal */
export const OwnershipIds$inboundSchema: z.ZodType<
  OwnershipIds,
  z.ZodTypeDef,
  unknown
> = z.object({
  ids: z.array(z.string()),
});

/** @internal */
export type OwnershipIds$Outbound = {
  ids: Array<string>;
};

/** @internal */
export const OwnershipIds$outboundSchema: z.ZodType<
  OwnershipIds$Outbound,
  z.ZodTypeDef,
  OwnershipIds
> = z.object({
  ids: z.array(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OwnershipIds$ {
  /** @deprecated use `OwnershipIds$inboundSchema` instead. */
  export const inboundSchema = OwnershipIds$inboundSchema;
  /** @deprecated use `OwnershipIds$outboundSchema` instead. */
  export const outboundSchema = OwnershipIds$outboundSchema;
  /** @deprecated use `OwnershipIds$Outbound` instead. */
  export type Outbound = OwnershipIds$Outbound;
}

export function ownershipIdsToJSON(ownershipIds: OwnershipIds): string {
  return JSON.stringify(OwnershipIds$outboundSchema.parse(ownershipIds));
}

export function ownershipIdsFromJSON(
  jsonString: string,
): SafeParseResult<OwnershipIds, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OwnershipIds$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OwnershipIds' from JSON`,
  );
}
