/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ReconciliationEntity,
  ReconciliationEntity$inboundSchema,
  ReconciliationEntity$Outbound,
  ReconciliationEntity$outboundSchema,
} from "./reconciliationentity.js";

export type ReconciliationEntities = {
  entities: Array<ReconciliationEntity>;
  continuation?: string | undefined;
};

/** @internal */
export const ReconciliationEntities$inboundSchema: z.ZodType<
  ReconciliationEntities,
  z.ZodTypeDef,
  unknown
> = z.object({
  entities: z.array(ReconciliationEntity$inboundSchema),
  continuation: z.string().optional(),
});

/** @internal */
export type ReconciliationEntities$Outbound = {
  entities: Array<ReconciliationEntity$Outbound>;
  continuation?: string | undefined;
};

/** @internal */
export const ReconciliationEntities$outboundSchema: z.ZodType<
  ReconciliationEntities$Outbound,
  z.ZodTypeDef,
  ReconciliationEntities
> = z.object({
  entities: z.array(ReconciliationEntity$outboundSchema),
  continuation: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReconciliationEntities$ {
  /** @deprecated use `ReconciliationEntities$inboundSchema` instead. */
  export const inboundSchema = ReconciliationEntities$inboundSchema;
  /** @deprecated use `ReconciliationEntities$outboundSchema` instead. */
  export const outboundSchema = ReconciliationEntities$outboundSchema;
  /** @deprecated use `ReconciliationEntities$Outbound` instead. */
  export type Outbound = ReconciliationEntities$Outbound;
}

export function reconciliationEntitiesToJSON(
  reconciliationEntities: ReconciliationEntities,
): string {
  return JSON.stringify(
    ReconciliationEntities$outboundSchema.parse(reconciliationEntities),
  );
}

export function reconciliationEntitiesFromJSON(
  jsonString: string,
): SafeParseResult<ReconciliationEntities, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReconciliationEntities$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReconciliationEntities' from JSON`,
  );
}
