/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const SearchEngine = {
  Legacy: "LEGACY",
  V1: "V1",
} as const;
export type SearchEngine = ClosedEnum<typeof SearchEngine>;

/** @internal */
export const SearchEngine$inboundSchema: z.ZodNativeEnum<typeof SearchEngine> =
  z.nativeEnum(SearchEngine);

/** @internal */
export const SearchEngine$outboundSchema: z.ZodNativeEnum<typeof SearchEngine> =
  SearchEngine$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SearchEngine$ {
  /** @deprecated use `SearchEngine$inboundSchema` instead. */
  export const inboundSchema = SearchEngine$inboundSchema;
  /** @deprecated use `SearchEngine$outboundSchema` instead. */
  export const outboundSchema = SearchEngine$outboundSchema;
}
