/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type SignatureValidationForm = {
  /**
   * Blockchain address in Union format `${blockchainGroup}:${token}`
   */
  signer: string;
  /**
   * The creator's public key
   */
  publicKey?: string | undefined;
  message: string;
  /**
   * Digital signature of the signer
   */
  signature: string;
  /**
   * Algorithm used for signature generation (don't specify if default algo is used)
   */
  algorithm?: string | undefined;
  /**
   * Weight arg (only for Flow)
   */
  weight?: number | undefined;
};

/** @internal */
export const SignatureValidationForm$inboundSchema: z.ZodType<
  SignatureValidationForm,
  z.ZodTypeDef,
  unknown
> = z.object({
  signer: z.string(),
  publicKey: z.string().optional(),
  message: z.string(),
  signature: z.string(),
  algorithm: z.string().optional(),
  weight: z.number().int().optional(),
});

/** @internal */
export type SignatureValidationForm$Outbound = {
  signer: string;
  publicKey?: string | undefined;
  message: string;
  signature: string;
  algorithm?: string | undefined;
  weight?: number | undefined;
};

/** @internal */
export const SignatureValidationForm$outboundSchema: z.ZodType<
  SignatureValidationForm$Outbound,
  z.ZodTypeDef,
  SignatureValidationForm
> = z.object({
  signer: z.string(),
  publicKey: z.string().optional(),
  message: z.string(),
  signature: z.string(),
  algorithm: z.string().optional(),
  weight: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SignatureValidationForm$ {
  /** @deprecated use `SignatureValidationForm$inboundSchema` instead. */
  export const inboundSchema = SignatureValidationForm$inboundSchema;
  /** @deprecated use `SignatureValidationForm$outboundSchema` instead. */
  export const outboundSchema = SignatureValidationForm$outboundSchema;
  /** @deprecated use `SignatureValidationForm$Outbound` instead. */
  export type Outbound = SignatureValidationForm$Outbound;
}

export function signatureValidationFormToJSON(
  signatureValidationForm: SignatureValidationForm,
): string {
  return JSON.stringify(
    SignatureValidationForm$outboundSchema.parse(signatureValidationForm),
  );
}

export function signatureValidationFormFromJSON(
  jsonString: string,
): SafeParseResult<SignatureValidationForm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SignatureValidationForm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SignatureValidationForm' from JSON`,
  );
}
