/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const SolanaSolAssetTypeAtType = {
  SolanaSol: "SOLANA_SOL",
} as const;
export type SolanaSolAssetTypeAtType = ClosedEnum<
  typeof SolanaSolAssetTypeAtType
>;

export type SolanaSolAssetType = {
  atType: SolanaSolAssetTypeAtType;
};

/** @internal */
export const SolanaSolAssetTypeAtType$inboundSchema: z.ZodNativeEnum<
  typeof SolanaSolAssetTypeAtType
> = z.nativeEnum(SolanaSolAssetTypeAtType);

/** @internal */
export const SolanaSolAssetTypeAtType$outboundSchema: z.ZodNativeEnum<
  typeof SolanaSolAssetTypeAtType
> = SolanaSolAssetTypeAtType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SolanaSolAssetTypeAtType$ {
  /** @deprecated use `SolanaSolAssetTypeAtType$inboundSchema` instead. */
  export const inboundSchema = SolanaSolAssetTypeAtType$inboundSchema;
  /** @deprecated use `SolanaSolAssetTypeAtType$outboundSchema` instead. */
  export const outboundSchema = SolanaSolAssetTypeAtType$outboundSchema;
}

/** @internal */
export const SolanaSolAssetType$inboundSchema: z.ZodType<
  SolanaSolAssetType,
  z.ZodTypeDef,
  unknown
> = z.object({
  "@type": SolanaSolAssetTypeAtType$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type SolanaSolAssetType$Outbound = {
  "@type": string;
};

/** @internal */
export const SolanaSolAssetType$outboundSchema: z.ZodType<
  SolanaSolAssetType$Outbound,
  z.ZodTypeDef,
  SolanaSolAssetType
> = z.object({
  atType: SolanaSolAssetTypeAtType$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    atType: "@type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SolanaSolAssetType$ {
  /** @deprecated use `SolanaSolAssetType$inboundSchema` instead. */
  export const inboundSchema = SolanaSolAssetType$inboundSchema;
  /** @deprecated use `SolanaSolAssetType$outboundSchema` instead. */
  export const outboundSchema = SolanaSolAssetType$outboundSchema;
  /** @deprecated use `SolanaSolAssetType$Outbound` instead. */
  export type Outbound = SolanaSolAssetType$Outbound;
}

export function solanaSolAssetTypeToJSON(
  solanaSolAssetType: SolanaSolAssetType,
): string {
  return JSON.stringify(
    SolanaSolAssetType$outboundSchema.parse(solanaSolAssetType),
  );
}

export function solanaSolAssetTypeFromJSON(
  jsonString: string,
): SafeParseResult<SolanaSolAssetType, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SolanaSolAssetType$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SolanaSolAssetType' from JSON`,
  );
}
