/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const SyncSort = {
  DbUpdateAsc: "DB_UPDATE_ASC",
  DbUpdateDesc: "DB_UPDATE_DESC",
} as const;
export type SyncSort = ClosedEnum<typeof SyncSort>;

/** @internal */
export const SyncSort$inboundSchema: z.ZodNativeEnum<typeof SyncSort> = z
  .nativeEnum(SyncSort);

/** @internal */
export const SyncSort$outboundSchema: z.ZodNativeEnum<typeof SyncSort> =
  SyncSort$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SyncSort$ {
  /** @deprecated use `SyncSort$inboundSchema` instead. */
  export const inboundSchema = SyncSort$inboundSchema;
  /** @deprecated use `SyncSort$outboundSchema` instead. */
  export const outboundSchema = SyncSort$outboundSchema;
}
