/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  TraitProperty,
  TraitProperty$inboundSchema,
  TraitProperty$Outbound,
  TraitProperty$outboundSchema,
} from "./traitproperty.js";

/**
 * Request rarity of the properties in the collection
 */
export type TraitsRarityRequest = {
  collectionId: string;
  properties: Array<TraitProperty>;
};

/** @internal */
export const TraitsRarityRequest$inboundSchema: z.ZodType<
  TraitsRarityRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  collectionId: z.string(),
  properties: z.array(TraitProperty$inboundSchema),
});

/** @internal */
export type TraitsRarityRequest$Outbound = {
  collectionId: string;
  properties: Array<TraitProperty$Outbound>;
};

/** @internal */
export const TraitsRarityRequest$outboundSchema: z.ZodType<
  TraitsRarityRequest$Outbound,
  z.ZodTypeDef,
  TraitsRarityRequest
> = z.object({
  collectionId: z.string(),
  properties: z.array(TraitProperty$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TraitsRarityRequest$ {
  /** @deprecated use `TraitsRarityRequest$inboundSchema` instead. */
  export const inboundSchema = TraitsRarityRequest$inboundSchema;
  /** @deprecated use `TraitsRarityRequest$outboundSchema` instead. */
  export const outboundSchema = TraitsRarityRequest$outboundSchema;
  /** @deprecated use `TraitsRarityRequest$Outbound` instead. */
  export type Outbound = TraitsRarityRequest$Outbound;
}

export function traitsRarityRequestToJSON(
  traitsRarityRequest: TraitsRarityRequest,
): string {
  return JSON.stringify(
    TraitsRarityRequest$outboundSchema.parse(traitsRarityRequest),
  );
}

export function traitsRarityRequestFromJSON(
  jsonString: string,
): SafeParseResult<TraitsRarityRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TraitsRarityRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TraitsRarityRequest' from JSON`,
  );
}
