/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  TraitEntry,
  TraitEntry$inboundSchema,
  TraitEntry$Outbound,
  TraitEntry$outboundSchema,
} from "./traitentry.js";

/**
 * Combination of Item attribute key with list of values
 */
export type Trait = {
  /**
   * Combination of Item attribute key/value with it's count
   */
  key: TraitEntry;
  values: Array<TraitEntry>;
};

/** @internal */
export const Trait$inboundSchema: z.ZodType<Trait, z.ZodTypeDef, unknown> = z
  .object({
    key: TraitEntry$inboundSchema,
    values: z.array(TraitEntry$inboundSchema),
  });

/** @internal */
export type Trait$Outbound = {
  key: TraitEntry$Outbound;
  values: Array<TraitEntry$Outbound>;
};

/** @internal */
export const Trait$outboundSchema: z.ZodType<
  Trait$Outbound,
  z.ZodTypeDef,
  Trait
> = z.object({
  key: TraitEntry$outboundSchema,
  values: z.array(TraitEntry$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Trait$ {
  /** @deprecated use `Trait$inboundSchema` instead. */
  export const inboundSchema = Trait$inboundSchema;
  /** @deprecated use `Trait$outboundSchema` instead. */
  export const outboundSchema = Trait$outboundSchema;
  /** @deprecated use `Trait$Outbound` instead. */
  export type Outbound = Trait$Outbound;
}

export function traitToJSON(trait: Trait): string {
  return JSON.stringify(Trait$outboundSchema.parse(trait));
}

export function traitFromJSON(
  jsonString: string,
): SafeParseResult<Trait, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Trait$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Trait' from JSON`,
  );
}
