/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Combination of Item attribute key/value with it's count
 */
export type TraitEntry = {
  value: string;
  count: number;
};

/** @internal */
export const TraitEntry$inboundSchema: z.ZodType<
  TraitEntry,
  z.ZodTypeDef,
  unknown
> = z.object({
  value: z.string(),
  count: z.number().int(),
});

/** @internal */
export type TraitEntry$Outbound = {
  value: string;
  count: number;
};

/** @internal */
export const TraitEntry$outboundSchema: z.ZodType<
  TraitEntry$Outbound,
  z.ZodTypeDef,
  TraitEntry
> = z.object({
  value: z.string(),
  count: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TraitEntry$ {
  /** @deprecated use `TraitEntry$inboundSchema` instead. */
  export const inboundSchema = TraitEntry$inboundSchema;
  /** @deprecated use `TraitEntry$outboundSchema` instead. */
  export const outboundSchema = TraitEntry$outboundSchema;
  /** @deprecated use `TraitEntry$Outbound` instead. */
  export type Outbound = TraitEntry$Outbound;
}

export function traitEntryToJSON(traitEntry: TraitEntry): string {
  return JSON.stringify(TraitEntry$outboundSchema.parse(traitEntry));
}

export function traitEntryFromJSON(
  jsonString: string,
): SafeParseResult<TraitEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TraitEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TraitEntry' from JSON`,
  );
}
