/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Trait,
  Trait$inboundSchema,
  Trait$Outbound,
  Trait$outboundSchema,
} from "./trait.js";

export type Traits = {
  /**
   * Continuation token to paginate traits search result
   */
  continuation?: string | undefined;
  /**
   * List of found traits
   */
  traits: Array<Trait>;
};

/** @internal */
export const Traits$inboundSchema: z.ZodType<Traits, z.ZodTypeDef, unknown> = z
  .object({
    continuation: z.string().optional(),
    traits: z.array(Trait$inboundSchema),
  });

/** @internal */
export type Traits$Outbound = {
  continuation?: string | undefined;
  traits: Array<Trait$Outbound>;
};

/** @internal */
export const Traits$outboundSchema: z.ZodType<
  Traits$Outbound,
  z.ZodTypeDef,
  Traits
> = z.object({
  continuation: z.string().optional(),
  traits: z.array(Trait$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Traits$ {
  /** @deprecated use `Traits$inboundSchema` instead. */
  export const inboundSchema = Traits$inboundSchema;
  /** @deprecated use `Traits$outboundSchema` instead. */
  export const outboundSchema = Traits$outboundSchema;
  /** @deprecated use `Traits$Outbound` instead. */
  export type Outbound = Traits$Outbound;
}

export function traitsToJSON(traits: Traits): string {
  return JSON.stringify(Traits$outboundSchema.parse(traits));
}

export function traitsFromJSON(
  jsonString: string,
): SafeParseResult<Traits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Traits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Traits' from JSON`,
  );
}
