/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Item trait property
 */
export type TraitProperty = {
  key: string;
  value: string;
};

/** @internal */
export const TraitProperty$inboundSchema: z.ZodType<
  TraitProperty,
  z.ZodTypeDef,
  unknown
> = z.object({
  key: z.string(),
  value: z.string(),
});

/** @internal */
export type TraitProperty$Outbound = {
  key: string;
  value: string;
};

/** @internal */
export const TraitProperty$outboundSchema: z.ZodType<
  TraitProperty$Outbound,
  z.ZodTypeDef,
  TraitProperty
> = z.object({
  key: z.string(),
  value: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TraitProperty$ {
  /** @deprecated use `TraitProperty$inboundSchema` instead. */
  export const inboundSchema = TraitProperty$inboundSchema;
  /** @deprecated use `TraitProperty$outboundSchema` instead. */
  export const outboundSchema = TraitProperty$outboundSchema;
  /** @deprecated use `TraitProperty$Outbound` instead. */
  export type Outbound = TraitProperty$Outbound;
}

export function traitPropertyToJSON(traitProperty: TraitProperty): string {
  return JSON.stringify(TraitProperty$outboundSchema.parse(traitProperty));
}

export function traitPropertyFromJSON(
  jsonString: string,
): SafeParseResult<TraitProperty, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TraitProperty$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TraitProperty' from JSON`,
  );
}
