/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Range,
  Range$inboundSchema,
  Range$Outbound,
  Range$outboundSchema,
} from "./range.js";

/**
 * Trait value range
 */
export type TraitRange = {
  key: string;
  valueRange: Range;
};

/** @internal */
export const TraitRange$inboundSchema: z.ZodType<
  TraitRange,
  z.ZodTypeDef,
  unknown
> = z.object({
  key: z.string(),
  valueRange: Range$inboundSchema,
});

/** @internal */
export type TraitRange$Outbound = {
  key: string;
  valueRange: Range$Outbound;
};

/** @internal */
export const TraitRange$outboundSchema: z.ZodType<
  TraitRange$Outbound,
  z.ZodTypeDef,
  TraitRange
> = z.object({
  key: z.string(),
  valueRange: Range$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TraitRange$ {
  /** @deprecated use `TraitRange$inboundSchema` instead. */
  export const inboundSchema = TraitRange$inboundSchema;
  /** @deprecated use `TraitRange$outboundSchema` instead. */
  export const outboundSchema = TraitRange$outboundSchema;
  /** @deprecated use `TraitRange$Outbound` instead. */
  export type Outbound = TraitRange$Outbound;
}

export function traitRangeToJSON(traitRange: TraitRange): string {
  return JSON.stringify(TraitRange$outboundSchema.parse(traitRange));
}

export function traitRangeFromJSON(
  jsonString: string,
): SafeParseResult<TraitRange, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TraitRange$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TraitRange' from JSON`,
  );
}
