/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const UnionApiErrorBadRequestCode = {
  BadRequest: "BAD_REQUEST",
  Validation: "VALIDATION",
} as const;
export type UnionApiErrorBadRequestCode = ClosedEnum<
  typeof UnionApiErrorBadRequestCode
>;

/** @internal */
export const UnionApiErrorBadRequestCode$inboundSchema: z.ZodNativeEnum<
  typeof UnionApiErrorBadRequestCode
> = z.nativeEnum(UnionApiErrorBadRequestCode);

/** @internal */
export const UnionApiErrorBadRequestCode$outboundSchema: z.ZodNativeEnum<
  typeof UnionApiErrorBadRequestCode
> = UnionApiErrorBadRequestCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnionApiErrorBadRequestCode$ {
  /** @deprecated use `UnionApiErrorBadRequestCode$inboundSchema` instead. */
  export const inboundSchema = UnionApiErrorBadRequestCode$inboundSchema;
  /** @deprecated use `UnionApiErrorBadRequestCode$outboundSchema` instead. */
  export const outboundSchema = UnionApiErrorBadRequestCode$outboundSchema;
}
