/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const UserActivityType = {
  TransferFrom: "TRANSFER_FROM",
  TransferTo: "TRANSFER_TO",
  Mint: "MINT",
  Burn: "BURN",
  MakeBid: "MAKE_BID",
  GetBid: "GET_BID",
  List: "LIST",
  Buy: "BUY",
  Sell: "SELL",
  CancelList: "CANCEL_LIST",
  CancelBid: "CANCEL_BID",
  BridgeTo: "BRIDGE_TO",
  BridgeFrom: "BRIDGE_FROM",
} as const;
export type UserActivityType = ClosedEnum<typeof UserActivityType>;

/** @internal */
export const UserActivityType$inboundSchema: z.ZodNativeEnum<
  typeof UserActivityType
> = z.nativeEnum(UserActivityType);

/** @internal */
export const UserActivityType$outboundSchema: z.ZodNativeEnum<
  typeof UserActivityType
> = UserActivityType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserActivityType$ {
  /** @deprecated use `UserActivityType$inboundSchema` instead. */
  export const inboundSchema = UserActivityType$inboundSchema;
  /** @deprecated use `UserActivityType$outboundSchema` instead. */
  export const outboundSchema = UserActivityType$outboundSchema;
}
